package knowledgev1

// kcesProfiles 构建 KCES 二进制记录、VirtualDirectory、MessagePack 资源容器和文本资源的源码审核指南
// kcesProfiles builds source-reviewed guides for KCES binary records, VirtualDirectory data, MessagePack asset containers, and text resources
func kcesProfiles() map[string]Guide {
	bridgeSource := source("KCES 1.34.4", "game/KCES 1.34.4/Assembly-CSharp/ExportCM.cs", "ExportCM.ExportMaidToCOM3D2", 597, 617, "The KCES export path writes GP03_BRIDGE, version 2001, the maid GUID, and two length-delimited preset blobs before emitting the .brd file.")
	bridgeReverseSource := source("COM3D2_5 3.48.0", "game/COM3D2_5 3.48.0/Assembly-CSharp/Maid.cs", "Maid.ExportBridgeGP03", 1687, 1711, "The reverse bridge writes GP03_BRIDGE version 2000, the maid GUID, and an optional CRC preset blob before saving 0.brd.")
	bridgeImportSource := source("COM3D2_5 3.48.0", "game/COM3D2_5 3.48.0/Assembly-CSharp/ImportCM.cs", "ImportCM.ImportPresetGP03", 1225, 1282, "The bridge reader checks GP03_BRIDGE, consumes the version and GUID, reads the two declared byte lengths, and sends the embedded legacy preset to the preset loader.")
	field := fieldFrom(bridgeSource, bridgeReverseSource, bridgeImportSource)

	brd := guide(
		"KCES .brd GP03 bridge guide",
		"A GP03_BRIDGE transfer record carrying a GUID and two length-delimited typed preset payloads between KCES and COM3D2_5.",
		"runtime_verified",
		"The shared outer layout was compared with the KCES 1.34.4 exporter and the COM3D2_5 reverse exporter. The service fully decodes the two embedded blocks with their COM3D2 and KCES preset codecs.",
		[]Source{bridgeSource, bridgeReverseSource, bridgeImportSource},
		[]Field{
			field("/format", "Editing format marker", "The MeidoSerialization marker for the GP03 bridge editing envelope.", "This marker belongs to the editing representation and is not written as a native game field.", "editing_metadata", "Keep kces-gp03-bridge when using the JSON codec; the native writer emits only the binary bridge fields.", "low"),
			field("/signature", "Bridge signature", "The BinaryWriter string identifying a GP03 bridge file.", "The KCES and COM3D2_5 bridge readers require GP03_BRIDGE before consuming the remaining record.", "format_marker", "Keep the exact value GP03_BRIDGE.", "critical"),
			field("/version", "Bridge version", "The outer bridge generation: KCES writes 2001 and COM3D2_5 writes 2000 for the reverse direction.", "The reader consumes this integer for the outer layout but the reviewed ImportPresetGP03 path does not branch on its value.", "version_marker", "Preserve the source value. Use 2001 for a new KCES-to-COM3D2_5 bridge and 2000 only when reproducing the reverse exporter.", "critical"),
			field("/guid", "Character transfer GUID", "The string identifying the character transfer session.", "The bridge reader consumes the GUID in the outer record; surrounding export/import paths use the same GUID in filenames and maid status.", "resource_identity", "Keep it stable across the paired preset payloads and use a valid GUID generated by the game when creating a new bridge.", "high"),
			field("/legacyPreset", "Legacy preset", "The fully typed COM3D2 preset carried by the v2001 bridge or null for the v2000 reverse bridge.", "The service decodes the declared bridge block with the COM3D2 preset codec before exposing editing JSON.", "runtime_configuration", "Use null for the mandatory empty v2000 legacy block and edit a populated preset through its typed fields.", "critical"),
			field("/currentPreset", "Current preset", "The fully typed KCES preset carried by the bridge, or null when the declared block is empty.", "The service decodes the declared bridge block with the KCES preset codec before exposing editing JSON.", "runtime_configuration", "Edit a populated preset through its typed fields and use null only for an empty declared block.", "critical"),
		},
	)
	brd.Rules = []Rule{{ID: "bridge-payload-boundaries", AppliesTo: []string{"/legacyPreset", "/currentPreset"}, Severity: "error", Summary: "The two preset blobs are length-delimited and independent.", Details: "Changing either payload requires its own preset codec. Do not concatenate, decompress, or reinterpret one blob using the other blob's format.", Evidence: []Source{bridgeSource, bridgeImportSource}}}
	brd.Invariants = []string{"signature is GP03_BRIDGE.", "version is normally 2001 for KCES output or 2000 for COM3D2_5 reverse output.", "Both preset lengths must describe exactly the following byte strings."}

	sessionSource := source("KCES 1.34.4", "game/KCES 1.34.4/Assembly-CSharp/CRCEdit/EditBridgeSessionData.cs", "EditBridgeSessionData.Deserialize/Serialize", 23, 109, "The bridge session is a VirtualDirectory containing session_data and session_id; session_data stores an indexed version, session ID, and hidden menu-file hash set.")
	vdSource := source("KCES 1.34.4", "game/KCES 1.34.4/WfSystem.Serialization/VirtualDirectory.cs", "VirtualDirectory.Serialize/Deserialize", 409, 575, "VirtualDirectory writes virtual-file byte payloads followed by compressed MessagePack directory metadata using the fixed current indexed layouts.")
	field = fieldFrom(sessionSource, vdSource)
	bridgeSession := guide(
		"KCES bridge_session.vd guide",
		"A VirtualDirectory session container used by the character-edit bridge. The reserved files session_data and session_id carry the editable session identity and hidden-menu state.",
		"runtime_verified",
		"EditBridgeSessionData and VirtualDirectory were reviewed in KCES 1.34.4. The reserved session files use fixed typed layouts, while only independently named virtual files outside those reserved paths remain byte payloads.",
		[]Source{sessionSource, vdSource},
		[]Field{
			field("/format", "Editing format marker", "The marker for the bridge-session editing envelope.", "It identifies the JSON wrapper and is not a native VirtualDirectory field.", "editing_metadata", "Keep kces-bridge-session.", "low"),
			field("/containerVersion", "VirtualDirectory version", "The outer container version, normally 1000 for KCES bridge sessions.", "VirtualDirectory uses this version during MessagePack serialization and migration callbacks.", "version_marker", "Preserve the decoded value; use 1000 for a newly created current session.", "high"),
			field("/sessionData", "session_data payload", "The typed MessagePack indexed object stored under the reserved session_data virtual file.", "EditBridgeSessionData reads its version, sessionId, and hidden menu-file IDs when opening the bridge.", "runtime_configuration", "Use normal nullable sessionId JSON semantics; the writer derives the required session_id UTF-8 file from this field.", "critical"),
			serializationField("/extraFiles", "Additional virtual files", "Independent virtual files whose names are neither session_data nor session_id.", "EditBridgeSessionData ignores these files, while VirtualDirectory stores their real byte-array payloads.", "binary_virtual_file", "Retain names and bytes only for independent files outside the two reserved paths; a reserved file must use its typed field and may never fall back here.", "high"),
		},
	)
	bridgeSession.FieldPatterns = []FieldPattern{
		pattern("/sessionData/{version,sessionId,hideMenuFileIds}", "Session state", "The indexed session version, identifier, and set of hidden menu-file hashes.", "EditBridgeSessionData uses the identifier and hash set to restore editor state.", "runtime_state", "Edit the ID and hidden hash list together; do not replace hashes with file names without recomputing the game's FNV values.", sessionSource),
	}
	bridgeSession.Rules = []Rule{{ID: "session-id-consistency", AppliesTo: []string{"/sessionData/sessionId"}, Severity: "error", Summary: "session_id is derived from sessionData.sessionId.", Details: "The editing representation exposes one typed session identifier. The writer encodes it as UTF-8 session_id bytes and rejects a missing session ID when serializing the bridge container.", Evidence: []Source{sessionSource}}}

	enmSource := source("KCES 1.34.4", "game/KCES 1.34.4/Assembly-CSharp/ExportCMUtility/ExportFileNameMap.cs", "ExportFileNameMap.LoadExportNameMap/Add/GetFileName/GetInternalName", 20, 132, "The exporter loads export_map.enm, stores a lower-case internal-name to file-name dictionary, and serializes the dictionary as a nested JSON string in serializeData.")
	field = fieldFrom(enmSource)
	enm := guide(
		"KCES export_map.enm guide",
		"A Unity JsonUtility filename map used during KCES to COM3D2 export. Each entry maps an internal resource name to the short file name emitted beside the export.",
		"runtime_verified",
		"ExportFileNameMap was reviewed in KCES 1.34.4, including FixVersion 1000, lower-case normalization, and the nested dictionary JSON representation.",
		[]Source{enmSource},
		[]Field{
			field("/format", "Editing format marker", "The marker for the normalized filename-map representation.", "This is an editing-layer value; native JsonUtility stores version and serializeData instead.", "editing_metadata", "Keep kces-export-name-map.", "low"),
			field("/version", "Name-map version", "The JsonUtility FixVersion value, normally 1000.", "ExportFileNameMap uses the version-control base class while loading and saving export_map.enm.", "version_marker", "Preserve the source value and use 1000 for KCES 1.34.4 output.", "high"),
			field("/entries", "Filename map entries", "Ordered internal-name and file-name pairs extracted from the nested serializeData dictionary.", "The exporter resolves internal names and file names through this map when writing bridge resources.", "runtime_mapping", "Keep entries unique, lower-case both names as the game does, and preserve order when round-tripping an existing file.", "high"),
		},
	)
	enm.FieldPatterns = []FieldPattern{pattern("/entries/*/{internalName,fileName}", "Filename-map pair", "One case-normalized mapping between an internal resource key and an exported filename.", "GetFileName and GetInternalName perform case-insensitive lookup over these pairs.", "runtime_mapping", "Use relative resource names and keep the mapping one-to-one for the files being exported.", enmSource)}
	enm.Rules = []Rule{{ID: "name-map-normalization", AppliesTo: []string{"/entries"}, Severity: "error", Summary: "Map keys and values follow the game's lower-case convention.", Details: "ExportFileNameMap.Add lowercases both internalName and fileName. A mixed-case duplicate can therefore collapse into one runtime entry.", Evidence: []Source{enmSource}}}
	enm.Invariants = []string{"version is 1000 for KCES 1.34.4.", "Each entry has a non-empty internal name and file name.", "The native wrapper's nested keys and values have equal lengths."}

	sadExportSource := source("KCES 1.34.4", "game/KCES 1.34.4/Assembly-CSharp/ExportCM.cs", "ExportCM.ExportAttachData", 1101, 1151, "ExportCM writes SAVED_ATTACH_DATA version 2000, filters records by slot, serializes each SavedAttachData record, and writes the .sad payload.")
	sadSource := source("KCES 1.34.4", "game/KCES 1.34.4/Assembly-CSharp/SavedAttachData.cs", "SavedAttachData.Serialize/Deserialize", 41, 126, "SavedAttachData records source and target RID/slot identities, optional vertex attachment data, two position-rotation-scale values, and an attached-bone hierarchy; version 2001 adds TargetSlotNo after the explicit marker.")
	sadImportSource := source("COM3D2_5 3.48.0", "game/COM3D2_5 3.48.0/Assembly-CSharp/ImportCM.cs", "ImportCM.ImportSavedAttachDataGP03", 1313, 1344, "The GP03 importer checks SAVED_ATTACH_DATA, reads the item count, deserializes each record, and appends it to the target body skin's saved-attachment list.")
	field = fieldFrom(sadExportSource, sadSource, sadImportSource)
	sad := guide(
		"KCES .sad saved-attachment guide",
		"The SAVED_ATTACH_DATA file emitted by KCES/GP03 export to preserve mesh-part attachment relationships and their transforms.",
		"runtime_verified",
		"SavedAttachData serialization and the current record version 2001 were reviewed in KCES 1.34.4. Legacy implicit version-2000 records remain readable and normalize to an explicit typed version when written.",
		[]Source{sadExportSource, sadSource, sadImportSource},
		[]Field{
			field("/format", "Editing format marker", "The marker for the normalized saved-attachment envelope.", "It identifies the editing JSON and is not written to the native BinaryWriter stream.", "editing_metadata", "Keep kces-saved-attach.", "low"),
			field("/signature", "Attachment signature", "The BinaryWriter string identifying saved attachment data.", "The game requires SAVED_ATTACH_DATA before reading the file version and item count.", "format_marker", "Keep the exact value SAVED_ATTACH_DATA.", "critical"),
			field("/version", "File version", "The supported outer saved-attachment version is 2000.", "ExportCM writes 2000 before the record count.", "version_marker", "Keep 2000; other outer layouts are unsupported.", "high"),
			field("/items", "Attachment records", "Ordered records describing a source part, target slot, optional vertex attachment, transforms, and attached-bone hierarchy.", "The importer applies each record to the target maid and mesh attachment point.", "runtime_collection", "Preserve order and keep every RID, slot ID, vertex index, and transform reference valid for the target export.", "critical"),
		},
	)
	sad.FieldPatterns = []FieldPattern{
		pattern("/items/*/{partName,enabled,myRid,targetRid,mySlotId,targetSlotId,targetSlotNo}", "Attachment identity", "The source part, enabled flag, source/target resource IDs, and slot identity used to resolve the attachment.", "The GP03 importer matches these values to a maid part and destination slot before applying geometry changes.", "runtime_reference", "Use IDs and slot strings from the same export; do not invent a slot name or change case casually.", sadSource, sadImportSource),
		pattern("/items/*/{targetAttachPointName,targetVertexCount,targetVertexIndex,newAttachVertexIndices}", "Attachment geometry reference", "Optional attach-point and vertex-selection data used when a part is attached to a mesh surface.", "The target body and mesh attachment code use these values to select the attach point or vertex.", "runtime_geometry_reference", "Keep indices within the target mesh and retain null attach-point state when the source record used it.", sadSource, sadImportSource),
		pattern("/items/*/{prs2,prs3,boneAttachedHierarchy}", "Attachment transforms", "Position/rotation/scale values and the hierarchy transforms keyed by attached-bone name.", "The importer traverses its transform hierarchy and looks up each saved transform by bone name, so dictionary wire order has no runtime meaning.", "runtime_transform", "Use finite vectors/quaternions and keep every map key aligned with a bone name in the target hierarchy.", sadSource, sadImportSource),
	}
	sad.Rules = []Rule{{ID: "attachment-version-layout", AppliesTo: []string{"/version", "/items"}, Severity: "error", Summary: "Only the verified outer and record layouts are supported.", Details: "The outer version must be 2000. Record versions 2000 and 2001 are supported; 2001 includes TargetSlotNo, while 2000 does not. Legacy implicit-2000 input is normalized to the explicit typed-version layout when written.", Evidence: []Source{sadSource}}}

	pathsSource := source("KCES 1.34.4", "game/KCES 1.34.4/WfSystem.FileSystem/ResourceManagement/NativeFileManager.cs", "NativeFileManager.ReadAutoPathFile", 656, 685, "NativeFileManager reads paths.dat to obtain additional resource search paths before creating compatible catalogs.")
	field = fieldFrom(pathsSource)
	paths := guide(
		"KCES paths.dat guide",
		"The CM3D2_PATHS search-path list used by KCES resource initialization.",
		"runtime_verified",
		"The BinaryWriter layout and NativeFileManager.ReadAutoPathFile consumer were reviewed in KCES 1.34.4.",
		[]Source{pathsSource},
		[]Field{
			field("/format", "Editing format marker", "The marker for the paths.dat editing envelope.", "It identifies the JSON representation and is not a native field.", "editing_metadata", "Keep kces-auto-paths.", "low"),
			field("/signature", "Paths signature", "The BinaryWriter string identifying a paths.dat file.", "NativeFileManager expects CM3D2_PATHS before reading version, count, and path strings.", "format_marker", "Keep the exact value CM3D2_PATHS.", "critical"),
			field("/version", "Paths version", "The path-list version, normally 1000.", "NativeFileManager reads the value as part of the file header before using the list.", "version_marker", "Preserve the source value; use 1000 for a new KCES file.", "high"),
			field("/paths", "Search paths", "Ordered resource directories or archive-related paths added to catalog discovery.", "NativeFileManager inserts these paths into the resource search configuration.", "runtime_resource_search", "Use existing relative or installation-specific paths from the target build; preserve order and casing conventions.", "critical"),
		},
	)
	paths.FieldPatterns = []FieldPattern{pattern("/paths/*", "Resource search path", "One BinaryWriter string in the ordered path list.", "ReadAutoPathFile adds each path to the native catalog search set.", "runtime_resource_reference", "Do not use absolute paths from another installation when the file is intended to be portable; verify every path exists in the target layout.", pathsSource)}
	paths.Invariants = []string{"signature is CM3D2_PATHS.", "The declared path count equals paths.length.", "Path order is preserved because catalog precedence can depend on insertion order."}

	maidColliderSource := source("KCES 1.34.4", "game/KCES 1.34.4/Assembly-CSharp/MaidColliderCollect.cs", "MaidColliderCollect.Read/ReadCapsuleCollider", 144, 223, "The system resources maid_collider.bytes and maid_collider_touch.bytes contain a count, bone path, center, direction, height, and radius for each capsule collider.")
	field = fieldFrom(maidColliderSource)
	maidCollider := guide(
		"KCES maid collider bytes guide",
		"The signatureless capsule-collider list used by MaidColliderCollect for maid body and touch collision resources.",
		"runtime_verified",
		"MaidColliderCollect.Read and its BinaryReader field order were reviewed in KCES 1.34.4. The same layout is used for maid_collider.bytes and maid_collider_touch.bytes.",
		[]Source{maidColliderSource},
		[]Field{
			field("/format", "Editing format marker", "The marker for the normalized maid-collider list.", "It identifies the editing representation; the native payload has no signature or format string.", "editing_metadata", "Keep kces-maid-capsule-colliders.", "low"),
			field("/colliders", "Maid capsule colliders", "The ordered capsule entries attached to named body-bone paths.", "MaidColliderCollect creates a Unity CapsuleCollider for each entry and applies its geometry.", "runtime_collection", "Use bone paths present in the target maid and preserve entry order.", "critical"),
		},
	)
	maidCollider.FieldPatterns = []FieldPattern{
		pattern("/colliders/*/bonePath", "Collider bone path", "A slash-separated transform path used to find the collider parent.", "Read resolves the path and attaches a CapsuleCollider to the matching object.", "runtime_resource_reference", "Use the exact path from the target body hierarchy.", maidColliderSource),
		pattern("/colliders/*/{center,direction,height,radius}", "Capsule geometry", "Center, axis direction, height, and radius written as fixed-width values.", "Unity CapsuleCollider receives these values directly.", "runtime_geometry", "Use direction values accepted by Unity and keep height >= 2*radius for the intended shape.", maidColliderSource),
	}

	assetSource := source("KCES 1.34.4", "game/KCES 1.34.4/Assembly-CSharp/Parts/SerializPartsAssets.cs", "SerializPartsAssets<T>", 9, 47, "MenuAssets, MaterialAssets, and PriorityMaterialAssets share the indexed fields Key(0) fileName and Key(1) assetArray; name lookup removes the extension, lower-cases the name, and hashes it.")
	menuAssetSource := source("KCES 1.34.4", "game/KCES 1.34.4/Assembly-CSharp/PartsMenuManager.cs", "PartsMenuManager.Reload", 64, 210, "The menu manager merges asset arrays, derives IDs from lower-case file names, and resolves menu commands and category metadata at runtime.")
	materialAssetSource := source("KCES 1.34.4", "game/KCES 1.34.4/Assembly-CSharp/PartsMaterialManager.cs", "PartsMaterialManager.CreateMaterial/GetMaterial", 36, 126, "The material manager resolves shader, texture, color, vector, and float properties from Material assets and their referenced resources.")
	priorityAssetSource := source("KCES 1.34.4", "game/KCES 1.34.4/Assembly-CSharp/PartsPriorityMaterialManager.cs", "PartsPriorityMaterialManager.SetPriorityMaterial/Reload", 33, 66, "The priority-material manager indexes overrides by target ID, verifies the material name, and applies the manual render-queue property and renderQueue value.")

	field = fieldFrom(assetSource, menuAssetSource)
	menuAssets := guide(
		"KCES .menuassets guide",
		"An LZ4 Block Array-compressed MessagePack container of Parts.Menu records stored in an .aba TextAsset.",
		"runtime_verified",
		"SerializPartsAssets and PartsMenuManager were reviewed in KCES 1.34.4. The container and nested objects use fixed current indexed layouts; unknown keys or wider arrays are rejected.",
		[]Source{assetSource, menuAssetSource},
		[]Field{
			field("/fileName", "Asset-container file name", "The container name stored at MessagePack Key(0).", "The manager uses it as the source identity while merging menu assets.", "resource_identity", "Keep the expected .menuassets name and preserve the source case when round-tripping.", "high"),
			field("/assetArray", "Menu asset array", "The ordered Parts.Menu values stored at MessagePack Key(1).", "PartsMenuManager registers each menu, derives lookup IDs, and later executes its command list.", "runtime_collection", "Preserve array order and edit each menu's identity, category, and command references coherently.", "critical"),
		},
	)
	menuAssets.FieldPatterns = []FieldPattern{
		pattern("/assetArray/*/{version,guid,id,fileName,itemName,iconFileName,infoText,categoryText,colorSetText,parentId}", "Menu identity and metadata", "The indexed Parts.Menu identity, display text, icon, category, and parent-menu relationship.", "PartsMenuManager derives lookup IDs from file names and SceneEdit uses the metadata while presenting menu items.", "runtime_resource_reference", "Keep fileName, id, guid, categoryText, and parentId coherent with the deployed menu graph.", menuAssetSource),
		pattern("/assetArray/*/commandList/*", "Compiled menu command", "A typed command and positional argument list inside one Parts.Menu record.", "The menu manager and maid editor execute or interpret these commands to change character parts.", "runtime_program", "Preserve command order and edit arguments only with the command's source contract in hand.", menuAssetSource),
	}
	menuAssets.Rules = []Rule{{ID: "menu-id-coherence", AppliesTo: []string{"/assetArray/*/{fileName,id,guid,parentId,commandList}"}, Severity: "error", Summary: "Menu identity fields and commands form one runtime record.", Details: "Changing a file name can change its FNV lookup ID and parent relationship. Update all references and preserve the command stream order.", Evidence: []Source{menuAssetSource}}}

	field = fieldFrom(assetSource, materialAssetSource)
	materialAssets := guide(
		"KCES .materialassets guide",
		"An LZ4 Block Array-compressed MessagePack container of Parts.Material records stored in an .aba TextAsset.",
		"runtime_verified",
		"SerializPartsAssets and PartsMaterialManager were reviewed in KCES 1.34.4. Material properties use their typed current layouts; unknown keys, wider arrays, and unsupported property variants are rejected.",
		[]Source{assetSource, materialAssetSource},
		[]Field{
			field("/fileName", "Asset-container file name", "The container name at MessagePack Key(0).", "The material manager uses it while merging material assets into its lookup table.", "resource_identity", "Keep the expected .materialassets name.", "high"),
			field("/assetArray", "Material asset array", "The ordered Parts.Material records at MessagePack Key(1).", "PartsMaterialManager resolves each material by file name and applies its shader and property arrays to Unity materials.", "runtime_collection", "Keep material IDs, file names, shader names, and property references coherent.", "critical"),
		},
	)
	materialAssets.FieldPatterns = []FieldPattern{
		pattern("/assetArray/*/{version,id,fileName,shaderName}", "Material identity", "The material version, FNV-derived ID, file name, and Unity shader name.", "PartsMaterialManager resolves the material and loads the named shader before applying properties.", "runtime_resource_reference", "Use a shader and material resource present in the target build; keep id consistent with the game's hash convention.", materialAssetSource),
		pattern("/assetArray/*/{textureProps,colorProps,vectorProps,floatProps}", "Typed material properties", "Texture, color, vector, and float property arrays applied to a Unity Material.", "The manager resolves referenced textures and assigns each property to the corresponding shader slot.", "runtime_configuration", "Keep every typed property ID and value compatible with the target shader; unsupported property representations must be rejected.", materialAssetSource),
	}

	field = fieldFrom(assetSource, priorityAssetSource)
	pmatAssets := guide(
		"KCES .pmatassets guide",
		"An LZ4 Block Array-compressed MessagePack container of Parts.PriorityMaterial records stored in an .aba TextAsset.",
		"runtime_verified",
		"SerializPartsAssets and PartsPriorityMaterialManager were reviewed in KCES 1.34.4. Priority-material records are indexed by ID and apply render-queue overrides to matching materials.",
		[]Source{assetSource, priorityAssetSource},
		[]Field{
			field("/fileName", "Asset-container file name", "The container name at MessagePack Key(0).", "The priority-material manager uses it while merging override records.", "resource_identity", "Keep the expected .pmatassets name.", "high"),
			field("/assetArray", "Priority-material asset array", "The ordered Parts.PriorityMaterial records at MessagePack Key(1).", "PartsPriorityMaterialManager finds matching materials by ID and applies render-queue overrides.", "runtime_collection", "Keep IDs, target IDs, file names, and render queues coherent with the matching .mate resources.", "critical"),
		},
	)
	pmatAssets.FieldPatterns = []FieldPattern{
		pattern("/assetArray/*/{version,id,fileName,renderQueue,targetId}", "Priority-material override", "A material ID, file name, render queue, and target-material ID.", "PartsPriorityMaterialManager applies the override when the target material ID resolves.", "runtime_material_override", "Use IDs generated by the target build and verify the render queue against the material's transparency needs.", priorityAssetSource),
	}
	pmatAssets.Rules = []Rule{{ID: "priority-material-target", AppliesTo: []string{"/assetArray/*/{id,targetId,fileName,renderQueue}"}, Severity: "error", Summary: "An override must resolve to the intended material.", Details: "The manager indexes records by ID and then applies the render queue to a matching material. A stale or duplicated hash can silently affect another material or do nothing.", Evidence: []Source{priorityAssetSource}}}

	modelSource := source("KCES 1.34.4", "game/KCES 1.34.4/Assembly-CSharp/Parts/Model.cs", "Parts.Model", 10, 175, "Parts.Model is a MessagePack indexed object with fixed version 1001, model and mesh file names, bone transforms, material names, morphs, skin-thickness data, and shadow flags.")
	modelManagerSource := source("KCES 1.34.4", "game/KCES 1.34.4/Assembly-CSharp/PartsModelManager.cs", "PartsModelManager.CreateModel", 24, 243, "PartsModelManager loads and deserializes the model, constructs the transform hierarchy, applies local transforms, loads the separate mesh, binds bones and materials, and forwards morph and skin-thickness data.")
	field = fieldFrom(modelSource, modelManagerSource)
	model := guide(
		"KCES .model guide",
		"A compressed Parts.Model description. It references a separate mesh resource and carries the skeleton, material slots, morphs, skin-thickness data, and shadow mode used by PartsModelManager.",
		"runtime_verified",
		"Parts.Model and PartsModelManager were reviewed in KCES 1.34.4. The model description does not embed mesh bytes; meshfileName resolves a separate resource.",
		[]Source{modelSource, modelManagerSource},
		[]Field{
			field("/version", "Model version", "The indexed MessagePack version, fixed at 1001 by the current Parts.Model constructor.", "PartsUtility.Deserialize<Model> uses the versioned object while loading model metadata.", "version_marker", "Preserve the source value and do not mix fields from a different model generation.", "critical"),
			field("/id", "Model resource ID", "The unsigned identifier used by parts resource lookup.", "PartsModelManager registers and resolves model records by their resource identity.", "resource_identity", "Keep it consistent with the target file-name/hash convention.", "high"),
			field("/fileName", "Model file name", "The logical .model file name stored in the record.", "The parts manager uses it as the model resource name.", "resource_identity", "Use the deployed .model name with its expected extension and case convention.", "critical"),
			field("/meshfileName", "Mesh resource name", "The separate mesh resource referenced by the model description, normally a .mmesh asset.", "The loader resolves this resource to obtain vertex, index, and skin data.", "resource_reference", "Ensure the referenced mesh exists in the same target catalog and keep the spelling exact.", "critical"),
			field("/modelName", "Render-root transform selector", "The exact transData[].name selected as the VirtualHierarchy that receives the SkinnedMeshRenderer.", "PartsModelManager names the outer object from fileName, then compares every created transform name with modelName and dereferences the selected hierarchy without a null check.", "runtime_selector", "Keep it equal to exactly one transData[].name. It is not a display name; when renaming the selected transform, update modelName and every dependent bone/reference together.", "critical"),
			field("/transData", "Bone transform records", "Indexed local transform and parent-index records for the model skeleton.", "The loader builds the bone hierarchy from these records before skinning.", "runtime_skeleton", "Preserve order, valid parent indices, and finite position/rotation/scale values.", "critical"),
			field("/boneNames", "Bone name table", "The ordered names paired with bone indices in the mesh and transform data.", "Skinning and attachment code resolves weighted bones through this table.", "runtime_skeleton", "Do not reorder or rename entries without rewriting all dependent weights and paths.", "critical"),
			field("/materialFileName", "Material resource names", "The ordered material file-name slots used by the model renderer.", "PartsModelManager resolves these names through the material manager.", "runtime_resource_reference", "Keep the number and order aligned with mesh submaterials and deploy the referenced .mate files.", "high"),
			field("/morphs", "Morph records", "Blend-shape records containing named vertex deltas and ranges.", "The model loader applies these records to facial or body deformation targets.", "runtime_morph", "Preserve vertex indices and delta-array lengths; edit only with the companion mesh in view.", "critical"),
			field("/skinThick", "Skin-thickness data", "Optional groups and angle-dependent distance values used by skin-thickness processing.", "The model system uses this data to adjust surface thickness around selected bones or vertices.", "runtime_geometry", "Keep group names, point indices, and angle ranges coherent with the mesh.", "high"),
			field("/shadowModeFlags", "Shadow mode", "The shadow enum value: 0 Default, 1 CastShadow, or 2 NoCastShadow.", "The renderer applies this value when configuring model shadow behavior.", "runtime_enum", "Use only values supported by the target build and verify the resulting renderer mode.", "medium"),
		},
	)
	model.FieldPatterns = []FieldPattern{
		pattern("/transData/*/{name,paretnNo,isSCL,pos,rot,scale}", "Bone transform entry", "A bone name, parent index, scale-bone flag, and local transform.", "PartsModelManager builds the hierarchy and applies these transforms before binding the mesh.", "runtime_skeleton", "Keep paretnNo valid and preserve the game's misspelled JSON key paretnNo.", modelSource, modelManagerSource),
		pattern("/morphs/*", "Blend-shape entry", "One morph target and its vertex delta data.", "The model loader forwards the entry to the mesh deformation system.", "runtime_morph", "Keep referenced vertex indices within the companion mesh and preserve array lengths.", modelSource, modelManagerSource),
		pattern("/skinThick/groups/*", "Skin-thickness group", "A named group of thickness points and angle-dependent distances.", "PartsModelManager forwards the skin-thickness object to the runtime mesh state.", "runtime_geometry", "Use only bones and points present in the target model.", modelSource, modelManagerSource),
	}
	model.Rules = []Rule{{ID: "model-render-root-selector", AppliesTo: []string{"/modelName", "/transData/*/name"}, Severity: "error", Summary: "modelName selects the transform that receives the renderer.", Details: "modelName must match exactly one transData[].name. A missing match leaves PartsModelManager's VirtualHierarchy null before AddComponent<SkinnedMeshRenderer>; changing modelName alone is not a display-name edit.", Evidence: []Source{modelManagerSource}}}
	model.Invariants = []string{"modelName matches exactly one transData[].name and selects the hierarchy that receives the SkinnedMeshRenderer.", "The outer model GameObject name is derived from fileName, not modelName."}

	hitSource := source("KCES 1.34.4", "game/KCES 1.34.4/Assembly-CSharp/TBodyHit.cs", "TBodyHit.Load", 84, 160, "TBodyHit reads HitCheck, derives radiusSqr from radius, resolves parent bone names, and uses SKRT/RL flags to classify skirt and bust collision spheres.")
	field = fieldFrom(hitSource)
	hit := guide(
		"KCES .hitcheck guide",
		"A BinaryWriter list of spherical hit-check entries used by body and hair collision logic.",
		"runtime_verified",
		"TBodyHit.Load and the corresponding HitCheck binary writer were reviewed in KCES 1.34.4. The file has no version field.",
		[]Source{hitSource},
		[]Field{
			field("/signature", "Hit-check signature", "The BinaryWriter string identifying a hitcheck file.", "TBodyHit requires HitCheck before reading the entry count.", "format_marker", "Keep the exact value HitCheck.", "critical"),
			field("/entries", "Hit sphere entries", "Ordered spherical collision records containing type, radius, parent/name, local position, and usage flags.", "TBodyHit resolves each parent bone and tests sphere intersections during body and skirt movement.", "runtime_collection", "Use valid parent bone names, finite positions, and radii appropriate to the target body scale.", "critical"),
		},
	)
	hit.FieldPatterns = []FieldPattern{
		pattern("/entries/*/{type,radius,radiusSqr,name,parent,position}", "Hit sphere geometry", "The sphere response type, radius, cached squared radius, object name, parent bone, and local position.", "TBodyHit uses the parent transform and squared-radius comparison for collision tests.", "runtime_geometry", "Keep radiusSqr equal to radius squared; use parent names present in the body hierarchy.", hitSource),
		pattern("/entries/*/{skrt,rl}", "Hit sphere usage flags", "Skirt/bust classification and left/right marker values.", "TBodyHit uses SKRT and RL to select special skirt and bust collision paths.", "runtime_enum", "Preserve the source flag convention; do not normalize unknown values to zero.", hitSource),
	}
	hit.Rules = []Rule{{ID: "hit-radius-cache", AppliesTo: []string{"/entries/*/radius", "/entries/*/radiusSqr"}, Severity: "error", Summary: "radiusSqr is a derived cache.", Details: "The game recomputes the squared radius while loading. Writers should recalculate it whenever radius changes instead of leaving a stale value.", Evidence: []Source{hitSource}}}

	jsonSource := source("KCES 1.34.4", "game/KCES 1.34.4/Assembly-CSharp/CsvManager.cs", "CsvManager.GetCsvText/CreateCsvIdManager", 43, 115, "CsvManager loads .nson resources as TextAsset.text and parses the enabled-list JSON with JsonUtility; this profile does not claim a domain schema for arbitrary resource fields.")
	field = fieldFrom(jsonSource)
	nson := guide(
		"KCES .nson guide",
		"A plain JSON resource used by CsvManager as a replacement for selected legacy .nei or CSV data.",
		"serialization_verified",
		"The KCES loader entry point and semantic JSON boundary were reviewed. The editing form retains the parsed JSON value but deliberately normalizes BOM, whitespace, and formatting; domain fields vary by resource.",
		[]Source{jsonSource},
		[]Field{
			field("/extension", "Resource extension", "The fixed extension marker .nson.", "The dispatcher uses it to select the plain-JSON resource path.", "format_marker", "Keep the exact value .nson.", "critical"),
			field("/json", "Normalized JSON value", "The parsed JSON value exposed for editing.", "CsvManager supplies JSON text to the consuming resource code; whitespace and BOM have no independent game meaning and this library does not infer the domain schema.", "opaque_domain_data", "Change only keys documented by the specific resource or game feature; retain unknown semantic members and types.", "critical"),
		},
	)
	nson.FieldPatterns = []FieldPattern{pattern("/json/*", "Resource-specific JSON member", "A member of the arbitrary JSON document consumed by a particular KCES subsystem.", "The consuming subsystem, not CsvManager, defines the meaning of this member.", "schema_dependent", "Require a source or sample for the exact resource before changing it.", jsonSource)}

	undressSource := source("KCES 1.34.4", "game/KCES 1.34.4/WfSystem.FileSystem/GameResource.cs", "GameResource.LoadBinary", 143, 156, "The game resource layer obtains the resource bytes from the selected file source. No resource-specific undress JSON consumer is established here, so this repository validates one complete JSON value and exposes its semantic content.")
	field = fieldFrom(undressSource)
	undressdat := guide(
		"KCES .undressdat guide",
		"A plain JSON TextAsset describing undress behavior for the KCES resource system.",
		"serialization_verified",
		"Only the extension dispatch and semantic JSON boundary are source-reviewed; resource-specific members remain schema_only and source formatting is intentionally normalized.",
		[]Source{undressSource},
		[]Field{
			field("/extension", "Resource extension", "The fixed extension marker .undressdat.", "The dispatcher uses it to route the TextAsset to the undress-data resource family.", "format_marker", "Keep the exact value .undressdat.", "critical"),
			field("/json", "Undress JSON value", "The parsed JSON document carried by the resource.", "The game-side consumer determines which entries control undress behavior; no universal field contract is established here.", "opaque_domain_data", "Edit only fields confirmed for the exact target resource and preserve unknown members.", "critical"),
		},
	)
	undresspdat := guide(
		"KCES .undresspdat guide",
		"A plain JSON TextAsset describing undress-part behavior for the KCES resource system.",
		"serialization_verified",
		"Only the extension dispatch and semantic JSON boundary are source-reviewed; resource-specific members remain schema_only and source formatting is intentionally normalized.",
		[]Source{undressSource},
		[]Field{
			field("/extension", "Resource extension", "The fixed extension marker .undresspdat.", "The dispatcher uses it to route the TextAsset to the undress-part resource family.", "format_marker", "Keep the exact value .undresspdat.", "critical"),
			field("/json", "Undress-part JSON value", "The parsed JSON document carried by the resource.", "The game-side consumer determines which entries control part removal or restoration.", "opaque_domain_data", "Edit only fields confirmed for the exact target resource and preserve unknown members.", "critical"),
		},
	)

	bytesSource := implementationSource("KCES 1.34.4", "service/KCES/raw_unity_service.go", "RawUnityObjectService", 17, 178, "The .bytes editing envelope preserves raw Unity serialized object bytes and sidecar metadata such as ClassID, PathID, load name, Unity versions, and optional TypeTree previews; the game-specific object schema is not inferred from arbitrary bytes.")
	field = fieldFrom(bytesSource)
	bytesGuide := guide(
		"KCES raw Unity .bytes guide",
		"A lossless envelope for an arbitrary Unity serialized object extracted from an .aba or .bytes resource.",
		"serialization_verified",
		"The service preserves object bytes and context metadata. ClassID and TypeTree can identify a known Unity object, but this profile does not claim a general editable schema for every class.",
		[]Source{bytesSource},
		[]Field{
			field("/format", "Raw-object format marker", "The editing marker kces-unity-raw-object.", "The raw Unity service requires this marker when converting JSON back to bytes.", "format_marker", "Keep the exact value kces-unity-raw-object.", "critical"),
			field("/classId", "Unity class ID", "The signed Unity ClassID associated with the serialized object.", "Unity uses ClassID to choose the object reader and TypeTree interpretation.", "runtime_type_identity", "Preserve the source value; changing it without rewriting dataBase64 makes the object undecodable.", "critical"),
			field("/dataBase64", "Raw object bytes", "The complete serialized Unity object payload encoded as base64.", "The service writes these bytes back unchanged when converting the envelope to a native resource.", "opaque_payload", "Treat as opaque unless a class-specific editor has validated the complete object layout.", "critical"),
			field("/typeName", "Unity type name", "Optional human-readable type name from the serialized asset context.", "It helps choose a TypeTree and diagnose object identity but does not replace ClassID.", "diagnostic_metadata", "Keep synchronized with ClassID and TypeTree when known.", "high"),
			field("/kind", "Asset kind", "The resource kind used by the ABA extractor.", "The service uses it to retain extraction context; Unity's object reader uses the serialized object metadata instead.", "diagnostic_metadata", "Preserve the original kind.", "medium"),
			field("/name", "Object name", "Optional internal Unity object name.", "Some Unity object classes use it for lookup or display.", "runtime_metadata", "Change only with a class-specific editor; preserve when editing raw bytes.", "high"),
			field("/pathId", "Unity PathID", "The serialized-file object identifier.", "AssetBundle lookup and references use PathID to identify the object within a serialized file.", "resource_identity", "Never change it without rewriting every serialized reference to the object.", "critical"),
			field("/loadName", "Asset load name", "The catalog or AssetBundle load name associated with the object.", "Resource management uses this name when resolving an extracted object.", "resource_reference", "Keep it aligned with the catalog entry and source bundle.", "high"),
			field("/unityVersion", "Serialized-file Unity version", "The Unity version string associated with the serialized object.", "TypeTree and serialized field interpretation can depend on this version.", "version_context", "Preserve the source version when editing raw bytes.", "high"),
			field("/engineVersion", "UnityFS engine version", "The engine version recorded by the containing UnityFS file.", "It supplies context for deserialization and diagnostics.", "version_context", "Preserve the source value.", "medium"),
			field("/targetPlatform", "Serialized target platform", "The optional platform identifier from the containing serialized file.", "Unity may use platform metadata while loading the object.", "runtime_metadata", "Preserve the original value unless rebuilding the complete serialized file.", "high"),
			field("/abaVersion", "ABA/UnityFS version", "The container format version recorded by the ABA extractor.", "It identifies the source bundle context rather than changing the object payload itself.", "version_context", "Preserve it when round-tripping extracted data.", "medium"),
			field("/generationVersion", "Generation version", "The UnityFS generation string recorded by the source bundle.", "It helps select compatible serialized-file parsing behavior.", "version_context", "Preserve the source value.", "medium"),
			field("/serializedFileVersion", "Serialized-file version", "The version number of the serialized-file container.", "Unity's serialized-file reader uses it with the type and platform metadata.", "version_context", "Preserve it unless rebuilding the full container.", "high"),
			serializationField("/typeTree", "Optional TypeTree view", "A parsed or partial TypeTree inspection of the raw object.", "It is a diagnostic/editing aid; the game consumes dataBase64 and the original serialized-file metadata.", "diagnostic_metadata", "Do not edit the preview without a class-specific encoder; preserve raw bytes as the authority.", "critical"),
		},
	)
	bytesGuide.Rules = []Rule{{ID: "raw-bytes-authority", AppliesTo: []string{"/dataBase64", "/typeTree"}, Severity: "error", Summary: "Raw bytes are authoritative when no class-specific codec is selected.", Details: "A TypeTree preview can be incomplete or read-only. Never regenerate dataBase64 from a modified preview unless the exact Unity class and versioned layout are supported.", Evidence: []Source{bytesSource}}}

	return map[string]Guide{
		"kces.brd":            brd,
		"kces.bridge_session": bridgeSession,
		"kces.enm":            enm,
		"kces.sad":            sad,
		"kces.paths":          paths,
		"kces.maid_collider":  maidCollider,
		"kces.menuassets":     menuAssets,
		"kces.materialassets": materialAssets,
		"kces.pmatassets":     pmatAssets,
		"kces.model":          model,
		"kces.hitcheck":       hit,
		"kces.nson":           nson,
		"kces.undressdat":     undressdat,
		"kces.undresspdat":    undresspdat,
		"kces.bytes":          bytesGuide,
	}
}
