package knowledgev1

import "strings"

// kces2MenuCommands 构建经过 KCES2 1.36.0 源码审核的菜单命令语义目录（运行时命令与编译时元数据命令）
// kces2MenuCommands builds the KCES2 1.36.0 source-reviewed menu-command semantics catalog: runtime commands and compile-time metadata commands
func kces2MenuCommands() []Command {
	reviewed := []string{"KCES2 1.36.0"}
	runtime := []string{"runtime interpreter (KCES2 1.36.0)"}
	compile := []string{"compile-time metadata (KCES2 1.36.0)"}

	// 证据：运行时解释器、Menu 类型声明、旧版导入路径、属性写入、节点可见性、纹理合成、通用解析等
	// Evidence: runtime interpreter, Menu type catalog, legacy import path, property writer, node visibility, texture layering, shared parsing, hair search, and animation load
	menuSource := source("KCES2 1.36.0", "KCES2 1.36.0/Assembly-CSharp/PartsMenuManager.cs", "PartsMenuManager.Exec", 233, 1819, "The runtime executes Parts.Menu.commandList in order; category, slot, version, attach, sub-prop, and conditional state carry into later records.")
	dataSource := source("KCES2 1.36.0", "KCES2 1.36.0/Assembly-CSharp/Parts/Menu.cs", "Parts.Menu and Parts.Menu.Command", 11, 592, "Defines the MessagePack Menu record, its command-list payload, and the CompileType and Type opcode enums.")
	oldImportSource := source("KCES2 1.36.0", "KCES2 1.36.0/Assembly-CSharp/PartsMenuManager.cs", "PartsMenuManager.CreatePartsMenuFromOldMenu", 59, 172, "The deprecated binary import path extracts compile commands into menu metadata, lower-cases arguments with recognized extensions, and terminates the stream at endcommand.")
	maidSetPropSource := source("KCES2 1.36.0", "KCES2 1.36.0/Assembly-CSharp/Maid.cs", "Maid.SetProp(string,int,bool)", 633, 668, "The property-by-name path parses the tag with case-sensitive Enum.Parse, falls back to null_mpn on failure, and clamps the value to the property min/max range.")
	tbodyMaskSource := source("KCES2 1.36.0", "KCES2 1.36.0/Assembly-CSharp/TBody.cs", "TBody.SetVisibleNodeSlot/AddMask/DelItem", 1632, 1677, "Node visibility resolves the slot by name, addmask silently ignores unknown slot names, and deletion restores all hidden nodes.")
	tbodyPartsNodeSource := source("KCES2 1.36.0", "KCES2 1.36.0/Assembly-CSharp/TBody.cs", "TBody.UpdateVisibleFlagParts consumer", 2337, 2362, "The parts-node visibility dictionary is looked up by another slot's Category, so its key must be an existing slot name.")
	tbodySkinPartsNodeSource := source("KCES2 1.36.0", "KCES2 1.36.0/Assembly-CSharp/TBodySkin.cs", "TBodySkin.SearchAndAddVisibleFlagSlot", 878, 907, "The parts-node writer matches the fourth parameter against node names by IndexOf, supports the _ALL_ marker, and stores results under the second parameter's slot key.")
	materialMgrTexSource := source("KCES2 1.36.0", "KCES2 1.36.0/Assembly-CSharp/MaterialMgr.cs", "MaterialMgr.ChangeTex save-layer handling", 390, 408, "When an infinite-color channel is bound, the saved-layer tag accepts a trailing linkcolor or linkcoloralpha assignment parsed behind the first colon.")
	materialMgrGroupSource := source("KCES2 1.36.0", "KCES2 1.36.0/Assembly-CSharp/MaterialMgr.cs", "MaterialMgr.MulTexSet tag expansion", 884, 924, "The texture-group path defaults an empty save tag to main, parses the same link-color assignment, and expands the infinite-color tag into tag:material:property.")
	parseSource := source("KCES2 1.36.0", "KCES2 1.36.0/Assembly-CSharp/Scourt/Utility/Parse.cs", "Parse.TryParse<T>", 223, 245, "Enum parsing falls back to a lower-cased name comparison, making Parse.TryParse case-insensitive, unlike the direct Enum.TryParse calls in ifdef conditions.")
	hairLengthSource := source("KCES2 1.36.0", "KCES2 1.36.0/Assembly-CSharp/HairLengthCtrl.cs", "HairLengthCtrl.SearchAndAddHairLengthTarget", 44, 66, "The search selector accepts only fbrother, fchild, or all with case-sensitive comparison; the bone name converts * to a regular-expression wildcard.")
	animationSource := source("KCES2 1.36.0", "KCES2 1.36.0/Assembly-CSharp/TBodySkin.cs", "TBodySkin.AnimationLoad", 1123, 1149, "An animation name without an extension is loaded as .anm; a missing clip logs an error and leaves the item unchanged.")

	commands := []Command{
		// 编译时元数据命令：由编辑器编译器提取为 Menu 字段，不进入 commandList。
		// Compile-time metadata commands: extracted by the editor compiler into Menu fields and not stored in commandList.
		menuCommand(
			"メニューフォルダ", nil, compile,
			[]CommandForm{menuForm("メニューフォルダ <folder>", reviewed,
				menuRequiredArgument(1, "folder", "string", "Menu resource search-path metadata consumed by the editor-side compiler."),
			)},
			"The editor compiler treats this record as menu-folder metadata; the reviewed game runtime never executes it.",
			"This opcode exists in the reviewed CompileType catalog, but the game-side source does not contain the text compiler. Keep an existing value as editor metadata only.",
			"medium", dataSource,
		),
		menuCommand(
			"name", nil, compile,
			[]CommandForm{menuForm("name <display-name>", reviewed,
				menuRequiredArgument(1, "display-name", "string", "Item display name stored into the menu itemName field."),
			)},
			"The compiler copies the value into the item display name used by the item browser.",
			"Treat it as item metadata rather than a runtime command; the reviewed runtime has no name unit.",
			"medium", dataSource,
		),
		menuCommand(
			"category", nil, compile,
			[]CommandForm{menuForm("category <mpn>", reviewed,
				menuRequiredArgument(1, "mpn", "MPN enum name", "Category metadata stored into the menu category field."),
			)},
			"The compiler stores the category into the Menu record; runtime slot behavior follows the stored category instead of this stream.",
			"Keep it synchronized with the stored category and use an MPN present in the target build.",
			"critical", dataSource,
		),
		menuCommand(
			"setumei", nil, compile,
			[]CommandForm{menuForm("setumei <description>", reviewed,
				menuRequiredArgument(1, "description", "string", "Item description stored into the menu infoText field."),
			)},
			"The compiler copies the value into the item description display text.",
			"Treat it as item metadata; the reviewed runtime has no setumei unit.",
			"medium", dataSource,
		),
		menuCommand(
			"icon", []string{"icons"}, compile,
			[]CommandForm{menuForm("icon <texture-file>", reviewed,
				menuRequiredArgument(1, "texture-file", "texture resource name", "Icon texture recorded into the menu iconFileName field."),
			)},
			"The legacy import path stores the icon argument, minus extension and lower-cased, into iconFileName; icons is processed identically.",
			"Keep the texture resource available in the target game archives and use either opcode without changing its argument layout.",
			"medium", dataSource, oldImportSource,
		),
		menuCommand(
			"unsetitem", nil, compile,
			[]CommandForm{menuForm("unsetitem", reviewed)},
			"The legacy import path uses the marker, or a _del file name, to set the menu deletion flag.",
			"Use only for an item intended to remove an equipped category entry.",
			"high", dataSource, oldImportSource,
		),
		menuCommand(
			"priority", nil, compile,
			[]CommandForm{menuForm("priority <value>", reviewed,
				menuRequiredArgument(1, "value", "int", "Sorting priority stored into the menu priority field; an empty value imports as zero."),
			)},
			"The legacy import path parses the value into the menu sorting priority.",
			"Use a finite integer and compare nearby items before changing established ordering.",
			"medium", dataSource, oldImportSource,
		),
		menuCommand(
			"color_set", nil, compile,
			[]CommandForm{menuForm("color_set <mpn>", reviewed,
				menuRequiredArgument(1, "mpn", "MPN enum name", "Color-set association parsed into the menu colorSet field."),
			)},
			"The legacy import path parses the argument into the menu colorSet MPN.",
			"Use an MPN present in the target build.",
			"high", dataSource, oldImportSource,
		),
		menuCommand(
			"gender", nil, compile,
			[]CommandForm{menuForm("gender <marker>", reviewed,
				menuRequiredArgument(1, "marker", "literal enum", "The legacy import path maps man_only to the Man target body type and butler to the ManReccomend attribute.", "man_only", "butler"),
			)},
			"The legacy import path converts the marker into the menu target body type and attribute flags.",
			"Use only the two reviewed markers; other values leave the body-type fields untouched.",
			"high", dataSource, oldImportSource,
		),
		menuCommand(
			"define", nil, compile,
			[]CommandForm{menuForm("define <flags>", reviewed,
				menuRequiredArgument(1, "flags", "Menu.DEFINE flags", "Define flags recorded as menu define metadata; ifdef conditions match them at runtime."),
			)},
			"The compiler stores define flags into the Menu record; Exec receives them as the defines bitmask.",
			"Keep the reported flags synchronized with defineTagNames and defineFirst.",
			"high", dataSource,
		),
		menuCommand(
			"colicon", nil, compile,
			[]CommandForm{menuForm("colicon <texture-file>", reviewed,
				menuRequiredArgument(1, "texture-file", "texture resource name", "Color-variation icon consumed by the editor colvari metadata."),
			)},
			"The compile-time catalog maps the value into color-variation metadata; the reviewed runtime never executes it.",
			"Keep an existing value as editor metadata only.",
			"medium", dataSource,
		),
		menuCommand(
			"colreqdefine", nil, compile,
			[]CommandForm{menuForm("colreqdefine <mpn-or-define>", reviewed,
				menuRequiredArgument(1, "mpn-or-define", "string", "Required define recorded with color-variation metadata."),
			)},
			"The compile-time catalog maps the value into color-variation requirements; the reviewed runtime never executes it.",
			"Keep an existing value as editor metadata only.",
			"medium", dataSource,
		),
		menuCommand(
			"colvari", nil, compile,
			[]CommandForm{menuForm("colvari <mpn>", reviewed,
				menuRequiredArgument(1, "mpn", "MPN enum name", "Color-variation data recorded into the menu colvariInfo field."),
			)},
			"The compile-time catalog maps the value into color-variation information.",
			"Keep an existing value as editor metadata only.",
			"medium", dataSource,
		),
		menuCommand(
			"colvarifile", nil, compile,
			[]CommandForm{menuForm("colvarifile <file-pattern>", reviewed,
				menuRequiredArgument(1, "file-pattern", "string", "Color-variation file-name pattern recorded into colvariFileNameExp."),
			)},
			"The compile-time catalog maps the value into the color-variation file-name expression.",
			"Keep an existing value as editor metadata only.",
			"medium", dataSource,
		),
		menuCommand(
			"ver", nil, compile,
			[]CommandForm{menuForm("ver <parts-version>", reviewed,
				menuRequiredArgument(1, "parts-version", "int", "Parts format version recorded as partsVer metadata."),
			)},
			"The compile-time catalog records the parts format version in partsVer; the runtime type=26 ver command is a separate opcode in commandList.",
			"Do not confuse this compile record with the runtime ver command's additem version state.",
			"high", dataSource,
		),
		menuCommand(
			"filter", nil, compile,
			[]CommandForm{menuForm("filter <filter-expression>", reviewed,
				menuRequiredArgument(1, "filter-expression", "string", "Editor-side filtering metadata not consumed by the reviewed game runtime."),
			)},
			"The compile-time catalog carries editor filtering metadata; the reviewed game source has no consumer.",
			"Keep an existing value as editor metadata only.",
			"low", dataSource,
		),
		menuCommand(
			"edit", nil, compile,
			[]CommandForm{menuForm("edit <flag>", reviewed,
				menuRequiredArgument(1, "flag", "string", "Edit visibility marker recorded into the menu hideInEdit field."),
			)},
			"The compile-time catalog maps the marker into the hide-from-editor flag.",
			"Keep an existing value as editor metadata only.",
			"low", dataSource,
		),
		menuCommand(
			"attribute", nil, compile,
			[]CommandForm{menuForm("attribute <flags>", reviewed,
				menuRequiredArgument(1, "flags", "Menu.Attribute flags", "Attribute flags recorded into the menu attribute field."),
			)},
			"The compile-time catalog maps the value into the menu attribute flags.",
			"Keep the stored flags coherent with the target body type.",
			"high", dataSource,
		),
		menuCommand(
			"toelock", nil, compile,
			[]CommandForm{menuForm("toelock <slot>", reviewed,
				menuRequiredArgument(1, "slot", "TBody.SlotID name", "Toe-lock slot recorded into the menu toeLockSlotId field."),
			)},
			"additem registers the stored slot with the toe-lock controller after loading the model; the record itself is compile-time menu metadata.",
			"Use a slot that supports toe locking and keep it synchronized with the additem sequence.",
			"high", dataSource, menuSource,
		),
		menuCommand(
			"formtex", nil, compile,
			[]CommandForm{menuForm("formtex <texture-file>", reviewed,
				menuRequiredArgument(1, "texture-file", "texture resource name", "Model-form texture recorded into exportModelFormTextureName."),
			)},
			"The compile-time catalog maps the value into the exported model-form texture name.",
			"Keep an existing value as editor metadata only.",
			"medium", dataSource,
		),
		menuCommand(
			"腹揺れ対応", nil, compile,
			[]CommandForm{menuForm("腹揺れ対応 <mode>", reviewed,
				menuRequiredArgument(1, "mode", "Menu.HaraYureLimitType", "Belly-sway availability recorded into isHarayureAvailable; additem copies it onto the slot."),
			)},
			"additem copies the recorded limit onto the freshly loaded slot; the record itself is compile-time menu metadata.",
			"Use an enum name from the reviewed value set.",
			"medium", dataSource, menuSource,
		),
		menuCommand(
			"skirt_phys", nil, compile,
			[]CommandForm{menuForm("skirt_phys <version>", reviewed,
				menuRequiredArgument(1, "version", "int", "Skirt-physics version passed to every additem model load in this menu."),
			)},
			"Exec passes the stored value into every additem model load as the skirt-physics version.",
			"Preserve known values from working menus unless the target model's expected mode is verified.",
			"high", dataSource, menuSource,
		),
		menuCommand(
			"ネイル合成", nil, compile,
			[]CommandForm{menuForm("ネイル合成 <items>", reviewed,
				menuRequiredArgument(1, "items", "opaque string(s)", "Editor-compiled nail composite referenced later by the runtime hash form."),
			)},
			"The editor compiler pre-compiles nail composites into preMulTexDatas; the runtime del or hash form consumes that data.",
			"Keep compile-time and runtime forms consistent: the runtime form uses del or a precompiled hash.",
			"high", dataSource,
		),
		menuCommand(
			"タトゥ合成", nil, compile,
			[]CommandForm{menuForm("タトゥ合成 <items>", reviewed,
				menuRequiredArgument(1, "items", "opaque string(s)", "Editor-compiled tattoo composite referenced later by the runtime hash form."),
			)},
			"The editor compiler pre-compiles tattoo composites into preMulTexDatas for the runtime hash form.",
			"Keep compile-time and runtime forms consistent as above.",
			"high", dataSource,
		),
		menuCommand(
			"ほくろ合成", nil, compile,
			[]CommandForm{menuForm("ほくろ合成 <items>", reviewed,
				menuRequiredArgument(1, "items", "opaque string(s)", "Editor-compiled mole composite referenced later by the runtime hash form."),
			)},
			"The editor compiler pre-compiles mole composites into preMulTexDatas for the runtime hash form.",
			"Keep compile-time and runtime forms consistent as above.",
			"high", dataSource,
		),
		menuCommand(
			"そばかす合成", nil, compile,
			[]CommandForm{menuForm("そばかす合成 <items>", reviewed,
				menuRequiredArgument(1, "items", "opaque string(s)", "Editor-compiled freckle composite referenced later by the runtime hash form."),
			)},
			"The editor compiler pre-compiles freckle composites into preMulTexDatas for the runtime hash form.",
			"Keep compile-time and runtime forms consistent as above.",
			"high", dataSource,
		),
		menuCommand(
			"ひげ合成", nil, compile,
			[]CommandForm{menuForm("ひげ合成 <items>", reviewed,
				menuRequiredArgument(1, "items", "opaque string(s)", "Editor-compiled beard composite referenced later by the runtime hash form."),
			)},
			"The editor compiler pre-compiles beard composites into preMulTexDatas for the runtime hash form.",
			"Keep compile-time and runtime forms consistent as above.",
			"high", dataSource,
		),
		menuCommand(
			"しみ合成", nil, compile,
			[]CommandForm{menuForm("しみ合成 <items>", reviewed,
				menuRequiredArgument(1, "items", "opaque string(s)", "Editor-compiled blemish composite referenced later by the runtime hash form."),
			)},
			"The editor compiler pre-compiles blemish composites into preMulTexDatas for the runtime hash form.",
			"Keep compile-time and runtime forms consistent as above.",
			"high", dataSource,
		),
		menuCommand(
			"しわ合成", nil, compile,
			[]CommandForm{menuForm("しわ合成 <items>", reviewed,
				menuRequiredArgument(1, "items", "opaque string(s)", "Editor-compiled wrinkle composite referenced later by the runtime hash form."),
			)},
			"The editor compiler pre-compiles wrinkle composites into preMulTexDatas for the runtime hash form.",
			"Keep compile-time and runtime forms consistent as above.",
			"high", dataSource,
		),
		menuCommand(
			"体毛合成", nil, compile,
			[]CommandForm{menuForm("体毛合成 <items>", reviewed,
				menuRequiredArgument(1, "items", "opaque string(s)", "Editor-compiled body-hair composite referenced later by the runtime hash form."),
			)},
			"The editor compiler pre-compiles body-hair composites into preMulTexDatas for the runtime hash form.",
			"Keep compile-time and runtime forms consistent as above.",
			"high", dataSource,
		),
	}

	commands = append(commands,
		// 流程控制与条件命令。// Stream control and conditional execution.
		menuCommand(
			"endcommand", nil, runtime,
			[]CommandForm{menuForm("endcommand", reviewed)},
			"Terminates command execution immediately; any command records after it are ignored by Exec.",
			"Keep it at the end of the compiled stream; a shorter stream with no terminator is also valid in editing JSON.",
			"high", menuSource,
		),
		menuCommand(
			"ver", nil, runtime,
			[]CommandForm{menuForm("ver <version>", reviewed,
				menuRequiredArgument(1, "version", "int", "Becomes the version passed to later additem operations; the initial state is 100."),
				menuOptionalArgument(2, "slot", "TBody.SlotID name", "", "When exactly two arguments exist, the second argument is taken as the version and the first is unused."),
			)},
			"Changes the additem version state; the two-argument form reads only the second argument.",
			"Keep it before the additem records it controls and prefer the one-argument form for authored files.",
			"critical", menuSource,
		),
		menuCommand(
			"ifdef", nil, runtime,
			[]CommandForm{menuForm("ifdef <condition> [== <operand>]", reviewed,
				menuRequiredArgument(1, "condition", "condition selector", "Selector: mpn, isplugin, ismanhead, ismanbody, or a DEFINE flag name. The mpn keyword itself is compared case-sensitively.", "mpn", "isplugin", "ismanhead", "ismanbody"),
				menuOptionalArgument(2, "relation", "relational token", "", "The second token is == for mpn and body-type conditions or in for the plugin condition."),
				menuOptionalArgument(3, "operand", "MPN, plugin name, boolean, or DEFINE name", "", "MPN and DEFINE names parse case-sensitively here; body-type booleans and plugin names compare case-insensitively."),
			)},
			"Skips later commands until a matching elseifdef or endifdef when the condition does not hold; elseifdef reevaluates and endifdef clears the skip state.",
			"Prefer plain mpn and plugin conditions for authored files. Do not assume nested conditionals: the interpreter tracks one skip state.",
			"critical", menuSource,
		),
		menuCommand(
			"elseifdef", nil, runtime,
			[]CommandForm{menuForm("elseifdef <condition> [== <operand>]", reviewed,
				menuRequiredArgument(1, "condition", "condition selector", "Same selectors as ifdef.", "mpn", "isplugin", "ismanhead", "ismanbody"),
				menuOptionalArgument(2, "relation", "relational token", "", "== or in depending on the selector."),
				menuOptionalArgument(3, "operand", "MPN, plugin name, boolean, or DEFINE name", "", "The compared value; parsing rules match ifdef."),
			)},
			"Reevaluates the skip state for the alternate branch of the current conditional region.",
			"Keep it between ifdef and endifdef and use the same argument layout as the matched ifdef.",
			"critical", menuSource,
		),
		menuCommand(
			"endifdef", nil, runtime,
			[]CommandForm{menuForm("endifdef", reviewed)},
			"Clears the conditional skip state.",
			"Do not remove it from a conditional region; later commands may remain skipped.",
			"critical", menuSource,
		),
		menuCommand(
			"アイテム", nil, runtime,
			[]CommandForm{menuForm("アイテム <menu-file> [<option>...]", reviewed,
				menuRequiredArgument(1, "menu-file", "menu resource name", "The child menu executed for the current maid or sub-slot."),
				menuOptionalRepeatableArgument(2, "option", "key=value token", "Optional colvari, def, mpn, and sub options described below."),
			)},
			"Executes a child menu, optionally restricted to a sub-slot range, with overridden MPN and defines; a one-character colvari value derives the color menu name from the current file name and refreshes the color state on match.",
			"Use colvari=<one-char> or a full name, def=<DEFINE>, mpn=<MPN>, and sub=all or sub=<start>-<end> (sub slots run 0 to 4). Verify the child menu exists.",
			"critical", menuSource,
		),
		menuCommand(
			"アイテム条件", nil, runtime,
			[]CommandForm{
				menuForm("アイテム条件 <slot> に何か <presence> なら <menu-file>", reviewed,
					menuRequiredArgument(1, "slot", "TBody.SlotID name", "The slot whose loaded-object presence is tested at the current sub-slot index."),
					menuRequiredArgument(3, "presence", "literal enum", "有る succeeds when the slot has an object and 無い when it is empty; other values assert.", "有る", "無い"),
					menuRequiredArgument(5, "menu-file", "menu resource name", "Executed when the presence test succeeds."),
				),
				menuForm("アイテム条件 <slot> が <model-file> なら <menu-file>", reviewed,
					menuRequiredArgument(1, "slot", "TBody.SlotID name", "The slot whose current model file name is compared."),
					menuRequiredArgument(3, "model-file", "model resource name", "Must equal the current model file name, compared case-sensitively."),
					menuRequiredArgument(5, "menu-file", "menu resource name", "Executed when the model-name test succeeds."),
				),
				menuForm("アイテム条件 <slot> のアイテムパラメータの <parameter-name> が <value> なら <menu-file>", reviewed,
					menuRequiredArgument(1, "slot", "TBody.SlotID name", "The slot whose item parameter is read."),
					menuRequiredArgument(3, "parameter-name", "string", "The parameter key, lower-cased before lookup."),
					menuRequiredArgument(5, "value", "string", "Lower-cased and compared with the current parameter value."),
					menuRequiredArgument(7, "menu-file", "menu resource name", "Executed when the parameter test succeeds."),
				),
			},
			"Conditionally executes another menu based on slot presence, current model identity, or an item parameter.",
			"Preserve the grammar literals at their exact positions and verify every referenced slot, model, parameter, and menu.",
			"critical", menuSource,
		),
		menuCommand(
			"ifcommand", nil, runtime,
			[]CommandForm{menuForm("ifcommand maidprop[<test-mpn>] == nothing ? setprop[<target-mpn>] = <value-expression>", reviewed,
				menuRequiredArgument(1, "test-expression", "maidprop[MPN] expression", "Tests whether the selected maid property has no assigned file."),
				menuRequiredArgument(5, "target-expression", "setprop[MPN] expression", "Selects the property to assign when the test succeeds."),
				menuRequiredArgument(7, "value-expression", "resource name or getprop[MPN] expression", "Provides a literal resource name or copies another property's file name; an empty value skips the assignment."),
			)},
			"Assigns a maid property from a resource name or another property's file when the tested property is empty.",
			"Use only the reviewed expression grammar; every operator and bracketed prefix is positional.",
			"critical", menuSource,
		),
		menuCommand(
			"アイテムパラメーター", nil, runtime,
			[]CommandForm{menuForm("アイテムパラメーター <slot> <parameter-name> <value>", reviewed,
				menuRequiredArgument(1, "slot", "TBody.SlotID name", "The loaded slot receiving the parameter."),
				menuRequiredArgument(2, "parameter-name", "string", "Parameter key stored without case normalization."),
				menuRequiredArgument(3, "value", "string", "Parameter value stored without case normalization."),
			)},
			"Queues exactly three arguments and applies them to the slot after every other command has executed.",
			"Supply exactly three arguments; other counts are diagnosed and the record is not queued.",
			"high", menuSource,
		),
		menuCommand(
			"半脱ぎ", nil, runtime,
			[]CommandForm{menuForm("半脱ぎ <resource-name>", reviewed,
				menuRequiredArgument(1, "resource-name", "resource name", "Stored under the fixed 半脱ぎ lookup key for this menu file."),
			)},
			"Registers a half-undressed resource reference in the menu resource-reference table.",
			"Keep the resource available and preserve this command when the item supports a half-undressed variant.",
			"high", menuSource,
		),
		menuCommand(
			"リソース参照", nil, runtime,
			[]CommandForm{menuForm("リソース参照 <key> <resource-name>", reviewed,
				menuRequiredArgument(1, "key", "string", "A named entry in this menu file's resource-reference table."),
				menuRequiredArgument(2, "resource-name", "resource name", "The referenced resource value."),
			)},
			"Adds or replaces a named resource reference associated with this menu file.",
			"Keep keys unique unless replacement is intentional and verify the resource exists.",
			"high", menuSource,
		),
		menuCommand(
			"setslotitem", nil, runtime,
			[]CommandForm{menuForm("setslotitem <mpn> <resource-id>", reviewed,
				menuRequiredArgument(1, "mpn", "MPN enum name", "Maid property selected by name; parsing is case-sensitive and falls back to null_mpn on failure."),
				menuRequiredArgument(2, "resource-id", "uint32", "Parsed as uint then cast to int and clamped to the property min/max range."),
			)},
			"Writes a numeric resource ID into a maid property rather than equipping a file.",
			"Use a valid MPN spelling and an ID valid in the target build.",
			"critical", menuSource, maidSetPropSource,
		))

	commands = append(commands,
		// 物品加载、可见性与遮罩。// Item loading, visibility, and masking.
		menuCommand(
			"additem", nil, runtime,
			[]CommandForm{
				menuForm("additem <model-file> [<slot>] [ボーンにアタッチ <bone-name>]", reviewed,
					menuRequiredArgument(1, "model-file", "model resource name", "The model loaded into the target slot."),
					menuOptionalArgument(2, "slot", "TBody.SlotID name", "current category", "Destination slot; it also becomes the current slot for later attach-point, morph, and state commands."),
					menuOptionalArgument(4, "bone-name", "bone name", "", "Direct bone attachment target after the fixed ボーンにアタッチ literal."),
				),
				menuForm("additem <model-file> [<slot>] アタッチ <attach-slot> <attach-point>", reviewed,
					menuRequiredArgument(1, "model-file", "model resource name", "The model loaded into the target slot."),
					menuOptionalArgument(2, "slot", "TBody.SlotID name", "current category", "Destination slot and current-slot state."),
					menuRequiredArgument(4, "attach-slot", "attach kind", "Attachment kind recorded with the model load."),
					menuRequiredArgument(5, "attach-point", "attachment-point name", "Destination position within the attach-slot."),
				),
				menuFormWithNotes("additem <model-file> [<slot>] [ボーンにアタッチ <bone-name> | アタッチ <attach-slot> <attach-point>] split:<slot>=<rule>[&<slot>=<rule>...]", reviewed,
					"Each rule is slot=x<value, slot=x>value, slot=y<value, slot=y>value, slot=z<value, slot=z>value, or slot=boneA|boneB, and rules are joined with ampersands. The interpreter finds the first argument starting with the split prefix (case-insensitively) and reads everything after its first colon; a missing colon raises an index exception.",
					menuRequiredArgument(1, "model-file", "model resource name", "The model loaded into one or more split target slots."),
					menuOptionalArgument(2, "slot", "TBody.SlotID name", "current category", "Ordinary destination slot and current-slot state."),
					menuOptionalArgument(3, "split-option", "split:<slot>=<rule>[&<slot>=<rule>...] token", "", "Defines target slots and either a clipping plane or split-part bone names."),
				),
			},
			"Loads a model with the current category, version, sub-slot, and body state, optional attachment, and optional split rules; loading into body also reloads the body, and hand-item slots attach to their hand IK bones. The current slot updates for later commands and all hidden nodes on it are restored.",
			"Verify the model, slot, attachment target, and all state established by preceding commands. Use special slots body, handitemr, and handiteml only when their behavior is intended.",
			"critical", menuSource,
		),
		menuCommand(
			"nofloory", nil, runtime,
			[]CommandForm{menuFormWithNotes("nofloory <ignored> <slot>", reviewed,
				"The interpreter reads only the second argument as the slot. The first argument is a required placeholder and its content is never inspected; omitting it causes an index exception.",
				menuRequiredArgument(1, "ignored", "placeholder", "Unused marker whose content has no runtime meaning."),
				menuRequiredArgument(2, "slot", "TBody.SlotID name", "The slot whose floor-Y collision flag is disabled."),
			)},
			"Disables floor-height collision handling for the selected slot.",
			"Use only for models authored to ignore floor-Y collision; this persists on the slot state.",
			"high", menuSource,
		),
		menuCommand(
			"maskitem", nil, runtime,
			[]CommandForm{menuForm("maskitem [<slot>]", reviewed,
				menuOptionalArgument(1, "slot", "TBody.SlotID name", "no mask", "Adds a mask relationship from the current category to this slot. A name that is not a real slot is silently ignored."),
			)},
			"Adds a body-slot mask associated with the current category; nothing happens when the argument is absent or is not a known slot name.",
			"Keep category immediately before it and verify that hiding the target slot is intended.",
			"high", menuSource, tbodyMaskSource,
		),
		menuCommand(
			"delitem", nil, runtime,
			[]CommandForm{menuForm("delitem [<slot>]", reviewed,
				menuOptionalArgument(1, "slot", "TBody.SlotID name", "current category", "Slot to delete; omission uses the current category. A name that is not a real slot is silently ignored."),
			)},
			"Deletes the item from the selected slot under the current MPN context and restores all hidden nodes on that slot.",
			"Confirm both the current category and optional slot; an unrecognized slot name deletes nothing.",
			"critical", menuSource, tbodyMaskSource,
		),
		menuCommand(
			"delitemnewattach", nil, runtime,
			[]CommandForm{menuForm("delitemnewattach", reviewed)},
			"Unloads every new-attach part registered under the current parent MPN.",
			"Use only when the parent MPN uses new-attach accessories (accAcc1 through accAcc24).",
			"high", menuSource,
		),
		menuCommand(
			"node消去", nil, runtime,
			[]CommandForm{menuForm("node消去 <node-name> [slot=<slot>]", reviewed,
				menuRequiredArgument(1, "node-name", "transform name", "Hides this node in the selected slot using name IndexOf matching; the _ALL_ marker affects the whole subtree."),
				menuOptionalArgument(2, "slot-override", "slot=<TBody.SlotID> token", "current category", "Overrides the current category slot for this operation."),
			)},
			"Hides matched model nodes in the current slot or override.",
			"Use an exact node name and do not add slot= when the current category is the intended target.",
			"high", menuSource, tbodyMaskSource,
		),
		menuCommand(
			"node表示", nil, runtime,
			[]CommandForm{menuForm("node表示 <node-name> [slot=<slot>]", reviewed,
				menuRequiredArgument(1, "node-name", "transform name", "Shows a previously hidden node matched with the same partial-name rules."),
				menuOptionalArgument(2, "slot-override", "slot=<TBody.SlotID> token", "current category", "Overrides the current category slot for this operation."),
			)},
			"Shows matched model nodes in the current slot or override.",
			"Keep hide and show operations ordered intentionally.",
			"high", menuSource, tbodyMaskSource,
		),
		menuCommand(
			"パーツnode消去", nil, runtime,
			[]CommandForm{menuFormWithNotes("パーツnode消去 <parts-slot> <node-name> [slot=<source-slot>]", reviewed,
				"The first argument is the key of the parts-visibility dictionary, so it must be an existing slot name; the runtime consumer looks entries up by other slots' category names. The second argument matches node names by IndexOf on the executing item and the matched names hide same-named bones of the parts slot. Writing a non-slot name as the key makes the entry permanently unreachable.",
				menuRequiredArgument(1, "parts-slot", "TBody.SlotID name", "The slot whose same-named bones are hidden."),
				menuRequiredArgument(2, "node-name", "transform name", "Node-name pattern matched inside the executing item; the _ALL_ marker selects everything."),
				menuOptionalArgument(3, "source-slot-override", "slot=<TBody.SlotID> token", "current category", "Overrides the current category used as the executing slot."),
			)},
			"Hides same-named bones of the parts slot through the parts-visibility mapping.",
			"Verify both slot roles and the node name; keep the key an existing slot name.",
			"high", menuSource, tbodyPartsNodeSource, tbodySkinPartsNodeSource,
		),
		menuCommand(
			"パーツnode表示", nil, runtime,
			[]CommandForm{menuFormWithNotes("パーツnode表示 <parts-slot> <node-name> [slot=<source-slot>]", reviewed,
				"Mirror of the hide form with the visibility flag set; the parts-slot key and node-name matching rules are identical.",
				menuRequiredArgument(1, "parts-slot", "TBody.SlotID name", "The slot whose same-named bones are shown."),
				menuRequiredArgument(2, "node-name", "transform name", "Node-name pattern matched inside the executing item."),
				menuOptionalArgument(3, "source-slot-override", "slot=<TBody.SlotID> token", "current category", "Overrides the current category used as the executing slot."),
			)},
			"Shows previously hidden same-named bones of the parts slot.",
			"Preserve ordering relative to matching hide commands.",
			"high", menuSource, tbodyPartsNodeSource, tbodySkinPartsNodeSource,
		),
		menuCommand(
			"mask消去", nil, runtime,
			[]CommandForm{menuForm("mask消去 <slot> <mask-name>", reviewed,
				menuRequiredArgument(1, "slot", "TBody.SlotID name", "The slot whose skin mask is removed at the current sub-slot index."),
				menuRequiredArgument(2, "mask-name", "string", "The skin-mask texture name registered for the selected slot."),
			)},
			"Registers a skin-mask removal for the slot.",
			"Verify the exact mask name; an unknown slot name raises an assert callback.",
			"critical", menuSource,
		),
		menuCommand(
			"cutout消去", nil, runtime,
			[]CommandForm{menuForm("cutout消去 <slot> <cutout-name>", reviewed,
				menuRequiredArgument(1, "slot", "TBody.SlotID name", "The slot whose skin-mask cutout is removed at the current sub-slot index."),
				menuRequiredArgument(2, "cutout-name", "string", "The skin-mask cutout texture name registered for the selected slot."),
			)},
			"Registers a skin-mask cutout removal for the slot.",
			"Verify the exact cutout name; an unknown slot name raises an assert callback.",
			"critical", menuSource,
		),
		menuCommand(
			"color", nil, runtime,
			[]CommandForm{menuForm("color <slot> <material-index> <property-name> <r> <g> <b> <a>", reviewed,
				menuRequiredArgument(1, "slot", "TBody.SlotID name", "The target slot."),
				menuRequiredArgument(2, "material-index", "int", "The material on the target slot."),
				menuRequiredArgument(3, "property-name", "shader color property name", "The color property to change."),
				menuRequiredArgument(4, "r", "float in byte-color units", "Red divided by 255 before assignment."),
				menuRequiredArgument(5, "g", "float in byte-color units", "Green divided by 255 before assignment."),
				menuRequiredArgument(6, "b", "float in byte-color units", "Blue divided by 255 before assignment."),
				menuRequiredArgument(7, "a", "float in byte-color units", "Alpha divided by 255 before assignment."),
			)},
			"Changes one color property on one slot material.",
			"Use the model's actual material index and shader property; ordinary channel values are 0 to 255.",
			"high", menuSource,
		),
		menuCommand(
			"mancolor", nil, runtime,
			[]CommandForm{menuFormWithNotes("mancolor <ignored-1> <ignored-2> <ignored-3> <r> <g> <b>", reviewed,
				"Only the last three arguments are read as red, green, and blue; the first three positional values are a required but unread legacy prefix and alpha is fixed to 1.",
				menuRequiredArgument(1, "ignored-1", "placeholder", "Legacy slot-like token that is never read."),
				menuRequiredArgument(2, "ignored-2", "placeholder", "Legacy material-like token that is never read."),
				menuRequiredArgument(3, "ignored-3", "placeholder", "Legacy property-like token that is never read."),
				menuRequiredArgument(4, "r", "float in byte-color units", "Red divided by 255."),
				menuRequiredArgument(5, "g", "float in byte-color units", "Green divided by 255."),
				menuRequiredArgument(6, "b", "float in byte-color units", "Blue divided by 255; alpha is fixed to 1."),
			)},
			"Sets the male body color from the last three arguments and immediately refreshes it.",
			"Provide all six arguments so the prefix positions exist, and use ordinary channel values from 0 to 255.",
			"high", menuSource,
		),
		menuCommand(
			"gradacolordef", nil, runtime,
			[]CommandForm{menuForm("gradacolordef <slot> <definition-name> <range-or-texture> <rates> <ranges> <colors>", reviewed,
				menuRequiredArgument(1, "slot", "TBody.SlotID name", "The slot receiving the gradation definition at the current sub-slot index."),
				menuRequiredArgument(2, "definition-name", "string", "The gradation definition name."),
				menuRequiredArgument(3, "range-or-texture", "x1:y1~x2:y2 range or texture name", "A two-point colon range becomes gradation lines; any other value is treated as a rate texture name."),
				menuRequiredArgument(4, "rates", "float~float...", "Gradation rate values joined by tildes."),
				menuRequiredArgument(5, "ranges", "x:y~x:y...", "One colon pair per rate value, joined by tildes."),
				menuRequiredArgument(6, "colors", "HSL~HSL...", "One HSL color per rate value parsed by the standard H,S,L,C,SH,SS,SL,SC,T fields."),
			)},
			"Defines or replaces a gradation color curve on the selected slot.",
			"Keep the count of rates, ranges, and colors identical and within the game's gradation point maximum.",
			"high", menuSource,
		),
		menuCommand(
			"tex", []string{"テクスチャ変更"}, runtime,
			[]CommandForm{menuForm("tex <slot> <material-selector> <property-name> <texture-file> [<parts-color> [<color-reference> <definition-name>] [<save-layer-tag>]]", reviewed,
				menuRequiredArgument(1, "slot", "TBody.SlotID name", "The target slot."),
				menuRequiredArgument(2, "material-selector", "int or MPN=int[&MPN=int...] mapping", "Direct material index or an ampersand mapping resolved by the current parent MPN; an unmatched mapping asserts and returns null."),
				menuRequiredArgument(3, "property-name", "shader texture property name", "The texture property to replace."),
				menuRequiredArgument(4, "texture-file", "texture resource name", "The replacement texture."),
				menuOptionalArgument(5, "parts-color", "PARTS_COLOR enum name", "NONE", "Binds an infinite-color channel; GRADA_COLOR may append |MUGEN_COLOR as its grada-is-mugen subtype."),
				menuOptionalArgument(6, "color-reference", "color selector", "", "Selects the definition for argument 7: grada, grada|mugen, or mugen."),
				menuOptionalArgument(7, "definition-name", "NAME or NAME:ALPHA_TYPE=PERCENT", "", "Color definition name with an optional alpha selector and percent suffix."),
				menuOptionalArgument(8, "save-layer-tag", "TAG or TAG:LinkColor=NAME or TAG:LinkColorAlpha=NAME", "main", "Saved-layer tag; when parts-color is bound, a trailing link-color assignment is parsed behind the first colon."),
			)},
			"Replaces a material texture, optionally selecting the material by MPN and binding an infinite-color channel with alpha and link-color handling; skin category textures may also trigger an implicit shader restoration.",
			"Verify every mapped MPN, material index, property, texture, and parts-color enum. tex and テクスチャ変更 are exact aliases; when an MPN mapping is used, every condition must cover the parent MPN or the missing match asserts.",
			"critical", menuSource, parseSource, materialMgrTexSource,
		),
		menuCommand(
			"partcolordef", nil, runtime,
			[]CommandForm{menuForm("partcolordef <slot> (<color-name> <hsl>)+", reviewed,
				menuRequiredArgument(1, "slot", "TBody.SlotID name", "The slot receiving the part-color definitions at the current sub-slot index."),
				menuRequiredRepeatableArgument(2, "color-name", "string", "Names one part-color definition; it repeats in pairs with the HSL value."),
				menuRequiredRepeatableArgument(3, "hsl", "H=..,S=..,L=..,C=..,SH=..,SS=..,SL=..,SC=..,T=..", "The HSL description whose fields map to main and shadow hue, chroma, brightness, contrast, and shadow rate."),
			)},
			"Defines named part-color entries consumed by partcolor and partcolorrgb.",
			"Keep name and HSL tokens paired and use field spellings exactly as listed.",
			"high", menuSource,
		),
		menuCommand(
			"partcolor", nil, runtime,
			[]CommandForm{menuForm("partcolor <slot> <material-index> <property-name> <texture-file> <id-textures> (<color-name>[:ALPHA_TYPE])+", reviewed,
				menuRequiredArgument(1, "slot", "TBody.SlotID name", "The target slot."),
				menuRequiredArgument(2, "material-index", "int", "The target material."),
				menuRequiredArgument(3, "property-name", "shader texture property name", "The texture property to change."),
				menuRequiredArgument(4, "texture-file", "texture resource name", "The main color texture."),
				menuRequiredArgument(5, "id-textures", "texture&texture&...", "Ampersand-separated ID textures; a lone underscore marks an empty slot."),
				menuRequiredRepeatableArgument(6, "color-name", "NAME or NAME:ALPHA_TYPE", "References a partcolordef color name with an optional alpha selector; when several selectors appear, the last one wins."),
			)},
			"Binds a part-color texture with ID lookup channels and color definitions, refreshing the part-color state.",
			"Reference only partcolordef names defined earlier in the same menu.",
			"high", menuSource,
		),
		menuCommand(
			"partcolorrgb", nil, runtime,
			[]CommandForm{menuForm("partcolorrgb <slot> <material-index> <property-name> <texture-file> <id-textures> (<color-name>[:ALPHA_TYPE])+", reviewed,
				menuRequiredArgument(1, "slot", "TBody.SlotID name", "The target slot."),
				menuRequiredArgument(2, "material-index", "int", "The target material."),
				menuRequiredArgument(3, "property-name", "shader texture property name", "The texture property to change."),
				menuRequiredArgument(4, "texture-file", "texture resource name", "The main color texture."),
				menuRequiredArgument(5, "id-textures", "texture&texture&...", "Ampersand-separated ID textures that also participate in RGB channel lookup."),
				menuRequiredRepeatableArgument(6, "color-name", "NAME or NAME:ALPHA_TYPE", "References a partcolordef color name; alpha selectors behave as in partcolor."),
			)},
			"Binds a part-color texture whose ID textures use RGB channel lookup and refreshes the part-color state.",
			"Use it only when the ID textures are authored for RGB channel color lookup.",
			"high", menuSource,
		),
		menuCommand(
			"pattern", nil, runtime,
			[]CommandForm{menuForm("pattern <texture-or-del> [<parts-color>]", reviewed,
				menuRequiredArgument(1, "texture-or-del", "texture name or del", "A texture name, or the literal del marker."),
				menuOptionalArgument(2, "parts-color", "PARTS_COLOR enum name", "NONE", "Parsed when present but the branch performs no further work."),
			)},
			"Parses the parts-color argument and then performs nothing; the opcode is a vestigial rest-and-asset branch in the reviewed runtime.",
			"Preserve existing arguments for round-tripping; do not rely on it for any visible effect.",
			"low", menuSource,
		),
		menuCommand(
			"mugencolordef", nil, runtime,
			[]CommandForm{menuForm("mugencolordef <slot> <layer-name> <hsl>", reviewed,
				menuRequiredArgument(1, "slot", "TBody.SlotID name", "The slot at the current sub-slot index."),
				menuRequiredArgument(2, "layer-name", "string", "The infinite-color layer name."),
				menuRequiredArgument(3, "hsl", "HSL description", "H,S,L,C,SH,SS,SL,SC,T fields used by the common HSL parser."),
			)},
			"Defines a named infinite-color layer on the selected slot.",
			"Keep the layer name unique within its slot color set.",
			"high", menuSource,
		),
		menuCommand(
			"prop", nil, runtime,
			[]CommandForm{menuForm("prop <mpn> <value>", reviewed,
				menuRequiredArgument(1, "mpn", "MPN enum name", "Maid property selected by name; parsing is case-sensitive and falls back to null_mpn on failure."),
				menuRequiredArgument(2, "value", "int", "Assigned to the property after min/max clamping."),
			)},
			"Sets a maid property's integer value through the case-sensitive property-by-name path.",
			"Spell the MPN exactly as declared and use a value valid for that property's own range.",
			"critical", menuSource, maidSetPropSource,
		),
		menuCommand(
			"テクスチャ合成", nil, runtime,
			[]CommandForm{
				menuForm("テクスチャ合成 <slot> <material-index> <property-name> <layer-index> <texture-file> <blend-mode>", reviewed,
					menuRequiredArgument(1, "slot", "TBody.SlotID name", "The target slot."),
					menuRequiredArgument(2, "material-index", "int or MPN=int[&MPN=int...] mapping", "Direct material index or MPN mapping like tex."),
					menuRequiredArgument(3, "property-name", "shader texture property name", "The texture property to composite."),
					menuRequiredArgument(4, "layer-index", "int", "The composition layer."),
					menuRequiredArgument(5, "texture-file", "texture resource name", "The layer texture."),
					menuRequiredArgument(6, "blend-mode", "GameUtility.SystemMaterial enum name", "Selects the system material used for composition.", "Alpha", "BlendSelf", "Multiply", "AddNormal", "AlphaDstAlpha", "Screen"),
				),
				menuForm("テクスチャ合成 del <slot> <material-index> <property-name> <layer-id>", reviewed,
					menuRequiredArgument(2, "slot", "TBody.SlotID name", "The slot whose composite layer is removed."),
					menuRequiredArgument(3, "material-index", "int", "The material."),
					menuRequiredArgument(4, "property-name", "shader texture property name", "The property."),
					menuRequiredArgument(5, "layer-id", "int", "The layer ID to remove."),
				),
			},
			"Composites a texture layer without any color binding; the deletion form removes a layer by ID. Fewer than the six main arguments raises an index exception.",
			"Supply the full main form or the del form; this opcode never applies color-channel bindings.",
			"critical", menuSource, materialMgrGroupSource,
		),
		menuCommand(
			"テクスチャセット合成", nil, runtime,
			[]CommandForm{
				menuForm("テクスチャセット合成 <slot> <material-index> <property-name> <layer-index> <texture-file> <blend-mode> [<parts-color>|GRADA_COLOR|MUGEN_COLOR] [<layer-no-in-group>] [<definition-name>:ALPHA_TYPE=PERCENT] [<save-layer-tag>] [<trans-tex-data>]", reviewed,
					menuRequiredArgument(1, "slot", "TBody.SlotID name", "The target slot."),
					menuRequiredArgument(2, "material-index", "int or MPN=int[&MPN=int...] mapping", "Direct material index or MPN mapping like tex."),
					menuRequiredArgument(3, "property-name", "shader texture property name", "The texture property to composite."),
					menuRequiredArgument(4, "layer-index", "int", "The composition layer."),
					menuRequiredArgument(5, "texture-file", "texture resource name", "The layer texture."),
					menuRequiredArgument(6, "blend-mode", "GameUtility.SystemMaterial enum name", "Selects the system material used for composition.", "Alpha", "BlendSelf", "Multiply", "AddNormal", "AlphaDstAlpha", "Screen"),
					menuOptionalArgument(7, "parts-color", "PARTS_COLOR enum name", "NONE", "Binds the infinite-color channel; GRADA_COLOR without a |MUGEN_COLOR subtype logs an error."),
					menuOptionalArgument(8, "layer-no-in-group", "int", "-1", "Group layer index applied when the tex-group path is active."),
					menuOptionalArgument(9, "definition-name", "NAME or NAME:ALPHA_TYPE=PERCENT", "", "Color definition with optional alpha selector and percent."),
					menuOptionalArgument(10, "save-layer-tag", "TAG or TAG:LinkColor=NAME", "", "Saved-layer tag; the tex-group path expands the infinite-color tag into tag:material:property."),
					menuOptionalArgument(11, "trans-tex-data", "TransTex token", "", "One ampersand-joined transformation set parsed into position, scale, rotation, and UV data."),
				),
				menuForm("テクスチャセット合成 del <slot> <material-index> <property-name> <layer-id>", reviewed,
					menuRequiredArgument(2, "slot", "TBody.SlotID name", "The slot whose composite layer is removed."),
					menuRequiredArgument(3, "material-index", "int", "The material."),
					menuRequiredArgument(4, "property-name", "shader texture property name", "The property."),
					menuRequiredArgument(5, "layer-id", "int", "The layer ID to remove."),
				),
			},
			"Composites and retains a texture-set layer with the full infinite-color, alpha, group, and transformation bindings; the deletion form removes a layer by ID.",
			"Supply the full form or the del form; the color system actually applies here, unlike plain テクスチャ合成.",
			"critical", menuSource, materialMgrGroupSource,
		),
		menuCommand(
			"munekagergb", nil, runtime,
			[]CommandForm{menuForm("munekagergb <slot> <material-index> <property-name> <shadow-texture> <blend-mode> <rgb-id-textures>", reviewed,
				menuRequiredArgument(1, "slot", "TBody.SlotID name", "The slot receiving the chest-shadow layer at the current sub-slot index."),
				menuRequiredArgument(2, "material-index", "int", "The target material."),
				menuRequiredArgument(3, "property-name", "shader texture property name", "The texture property to composite."),
				menuRequiredArgument(4, "shadow-texture", "texture resource name", "The chest-shadow texture."),
				menuRequiredArgument(5, "blend-mode", "GameUtility.SystemMaterial enum name", "The composition blend mode; a transparent target shader combined with Alpha logs an error advising AlphaDstAlpha."),
				menuRequiredArgument(6, "rgb-id-textures", "texture&texture&...", "Ampersand-separated ID textures marking the parts-color region."),
			)},
			"Composites the chest-shadow layer with RGB parts-color ID textures and enables the wear chest-shadow flag.",
			"Match the blend mode to the target shader and keep the ID texture list aligned with the color texture.",
			"high", menuSource,
		),
		menuCommand(
			"munekage", nil, runtime,
			[]CommandForm{menuForm("munekage <slot> <material-index> <property-name> <shadow-texture> <blend-mode>", reviewed,
				menuRequiredArgument(1, "slot", "TBody.SlotID name", "The slot receiving the chest-shadow layer at the current sub-slot index."),
				menuRequiredArgument(2, "material-index", "int", "The target material."),
				menuRequiredArgument(3, "property-name", "shader texture property name", "The texture property to composite."),
				menuRequiredArgument(4, "shadow-texture", "texture resource name", "The chest-shadow texture."),
				menuRequiredArgument(5, "blend-mode", "GameUtility.SystemMaterial enum name", "The composition blend mode."),
			)},
			"Composites the chest-shadow layer without ID textures and enables the wear chest-shadow flag.",
			"Use munekagergb when the authored color texture needs RGB ID lookup.",
			"high", menuSource,
		),
		menuCommand(
			"マテリアル変更", nil, runtime,
			[]CommandForm{menuForm("マテリアル変更 <slot> <material-index> <material-file>", reviewed,
				menuRequiredArgument(1, "slot", "TBody.SlotID name", "The target slot; under new-attach MPNs the virtual slot converts to the real slot."),
				menuRequiredArgument(2, "material-index", "int", "The material to replace."),
				menuRequiredArgument(3, "material-file", "material resource name", "The replacement .mate resource."),
			)},
			"Replaces one material on a loaded slot model at the current sub-slot index.",
			"Verify the index against the target model and ensure the material and referenced textures and shaders exist.",
			"critical", menuSource,
		),
		menuCommand(
			"マテリアル参照", nil, runtime,
			[]CommandForm{menuForm("マテリアル参照 <source-slot> <source-material-index> <target-slot> <target-material-index>", reviewed,
				menuRequiredArgument(1, "source-slot", "TBody.SlotID name", "The slot whose material instance is shared."),
				menuRequiredArgument(2, "source-material-index", "int", "The source material."),
				menuRequiredArgument(3, "target-slot", "TBody.SlotID name", "The slot that receives the shared material."),
				menuRequiredArgument(4, "target-material-index", "int", "The target material index."),
			)},
			"Shares one loaded material instance between two slots at the current sub-slot index.",
			"Both models must have matching material slots and the source material must already be loaded.",
			"high", menuSource,
		),
		menuCommand(
			"shader", nil, runtime,
			[]CommandForm{menuForm("shader <slot> <material-index> <shader-name>", reviewed,
				menuRequiredArgument(1, "slot", "TBody.SlotID name", "The target slot."),
				menuRequiredArgument(2, "material-index", "int", "The material whose shader changes."),
				menuRequiredArgument(3, "shader-name", "Unity shader name", "The replacement shader."),
			)},
			"Changes one material's shader and marks the menu as having made an explicit shader change, suppressing skin shader restoration.",
			"Use a shader present in the target build and verify all existing material properties remain compatible.",
			"critical", menuSource,
		),
		menuCommand(
			"アタッチポイントの設定", nil, runtime,
			[]CommandForm{
				menuForm("アタッチポイントの設定 <point-name> <x> <y> <z>", reviewed,
					menuRequiredArgument(1, "point-name", "attachment-point name", "The attachment point in the current additem slot."),
					menuRequiredArgument(2, "x", "float", "Local position X."),
					menuRequiredArgument(3, "y", "float", "Local position Y."),
					menuRequiredArgument(4, "z", "float", "Local position Z."),
				),
				menuFormWithNotes("アタッチポイントの設定 <point-name> <x> <y> <z> <rx> <ry> <rz>", reviewed,
					"The seven-argument form is the complete layout. Four to six arguments log a missing-angle error and apply identity rotation; fewer than four arguments logs an error and performs nothing.",
					menuRequiredArgument(1, "point-name", "attachment-point name", "The attachment point in the current additem slot."),
					menuRequiredArgument(2, "x", "float", "Local position X."),
					menuRequiredArgument(3, "y", "float", "Local position Y."),
					menuRequiredArgument(4, "z", "float", "Local position Z."),
					menuOptionalArgument(5, "rx", "float degrees", "0", "Euler rotation X."),
					menuOptionalArgument(6, "ry", "float degrees", "0", "Euler rotation Y."),
					menuOptionalArgument(7, "rz", "float degrees", "0", "Euler rotation Z."),
				),
			},
			"Sets an attachment point's local transform on the current additem slot at the current sub-slot index.",
			"Use the seven-argument form for authored files; the shorter form is accepted but logs a missing-angle error.",
			"high", menuSource,
		),
		menuCommand(
			"blendset", nil, runtime,
			[]CommandForm{menuForm("blendset <set-name> (<morph-name> <weight>)+", reviewed,
				menuRequiredArgument(1, "set-name", "string", "The face-morph blend set name."),
				menuRequiredRepeatableArgument(2, "morph-name", "morph key", "A face morph entry name, lower-cased before lookup; repeats in pairs with weight."),
				menuRequiredRepeatableArgument(3, "weight", "float", "The morph value; repeats in pairs with morph-name."),
			)},
			"Creates a face blend set and assigns each named morph weight.",
			"Keep morph-name and weight tokens paired and preserve the set name used by consumers.",
			"high", menuSource,
		),
		menuCommand(
			"paramset", nil, runtime,
			[]CommandForm{menuForm("paramset <raw-parameters>...", reviewed,
				menuRequiredRepeatableArgument(1, "raw-parameters", "string", "Tokens appended verbatim to the command text passed to the face parameter-set parser."),
			)},
			"Forwards the raw command text to the face parameter-set parser; the interpreter performs no key/value parsing itself.",
			"Author it exactly as the face parameter-set consumer expects; the runtime does not validate the token shape.",
			"high", menuSource,
		),
		menuCommand(
			"useredit", nil, runtime,
			[]CommandForm{menuForm("useredit <label> material <destination-slot> <material-index> <property-name> <type-name> <value>", reviewed,
				menuRequiredArgument(1, "label", "editor label", "Identifies the user-edit entry; any value is accepted and stored."),
				menuRequiredArgument(3, "destination-slot", "TBody.SlotID name", "The destination slot for the material property."),
				menuRequiredArgument(4, "material-index", "int", "The destination material."),
				menuRequiredArgument(5, "property-name", "shader property name", "The material property to change."),
				menuRequiredArgument(6, "type-name", "Unity material property type", "Selects the parser for the property value."),
				menuRequiredArgument(7, "value", "type-encoded string", "The value encoded according to type-name."),
			)},
			"Applies a material property through the user-edit path when the literal second token is material; other second tokens are silently ignored.",
			"Keep material at position 2 and use a type/value encoding accepted by TBody.SetMaterialProperty.",
			"critical", menuSource,
		),
		menuCommand(
			"material", nil, runtime,
			[]CommandForm{menuForm("material <slot> <material-index> <property-name> <type-name> <value>", reviewed,
				menuRequiredArgument(1, "slot", "TBody.SlotID name", "The target slot."),
				menuRequiredArgument(2, "material-index", "int", "The target material."),
				menuRequiredArgument(3, "property-name", "shader property name", "The material property to change."),
				menuRequiredArgument(4, "type-name", "Unity material property type", "Selects the parser for the property value."),
				menuRequiredArgument(5, "value", "type-encoded string", "The value encoded according to type-name."),
			)},
			"Applies a typed material property directly without an editor label.",
			"Use a type/value encoding accepted by TBody.SetMaterialProperty.",
			"high", menuSource,
		),
		menuCommand(
			"bonemorph", nil, runtime,
			[]CommandForm{
				menuForm("bonemorph <bone-name> <morph-name> <min-x> <min-y> <min-z> <max-x> <max-y> <max-z>", reviewed,
					menuRequiredArgument(1, "bone-name", "bone name", "The bone whose positional morph is changed."),
					menuRequiredArgument(2, "morph-name", "morph name", "The bone morph entry."),
					menuRequiredArgument(3, "min-x", "float", "Minimum positional X."),
					menuRequiredArgument(4, "min-y", "float", "Minimum positional Y."),
					menuRequiredArgument(5, "min-z", "float", "Minimum positional Z."),
					menuRequiredArgument(6, "max-x", "float", "Maximum positional X."),
					menuRequiredArgument(7, "max-y", "float", "Maximum positional Y."),
					menuRequiredArgument(8, "max-z", "float", "Maximum positional Z."),
				),
				menuFormWithNotes("bonemorph <transform-kind> <bone-name> <morph-name> <min-x> <min-y> <min-z> <max-x> <max-y> <max-z>", reviewed,
					"The nine-argument form selects pos, rot, or scl case-insensitively; any other kind logs an error and performs nothing. Other argument counts are diagnosed as invalid.",
					menuRequiredArgument(1, "transform-kind", "literal enum", "Selects which transform channel is changed.", "pos", "rot", "scl"),
					menuRequiredArgument(2, "bone-name", "bone name", "The bone whose morph is changed."),
					menuRequiredArgument(3, "morph-name", "morph name", "The bone morph entry."),
					menuRequiredArgument(4, "min-x", "float", "Minimum channel X."),
					menuRequiredArgument(5, "min-y", "float", "Minimum channel Y."),
					menuRequiredArgument(6, "min-z", "float", "Minimum channel Z."),
					menuRequiredArgument(7, "max-x", "float", "Maximum channel X."),
					menuRequiredArgument(8, "max-y", "float", "Maximum channel Y."),
					menuRequiredArgument(9, "max-z", "float", "Maximum channel Z."),
				),
			},
			"Changes a bone morph's position, rotation, or scale range; the eight-argument form is positional only.",
			"Keep all six vector components finite and use the form supported by the target model's authored menu.",
			"critical", menuSource,
		),
		menuCommand(
			"length", nil, runtime,
			[]CommandForm{menuFormWithNotes("length <slot> <group-name> <bone-search-type> <bone-name> <min-x> <min-y> <min-z> <max-x> <max-y> <max-z>", reviewed,
				"Exactly ten arguments are expected; other counts log an error. The search selector accepts only fbrother, fchild, or all with case-sensitive comparison, and the bone name converts * to a regular-expression wildcard.",
				menuRequiredArgument(1, "slot", "TBody.SlotID name", "The hair slot whose length data changes at the current sub-slot index."),
				menuRequiredArgument(2, "group-name", "string", "The hair-length group name."),
				menuRequiredArgument(3, "bone-search-type", "literal enum", "Bone-search mode selector.", "fbrother", "fchild", "all"),
				menuRequiredArgument(4, "bone-name", "bone name", "The bone pattern searched by the group; * becomes a regular-expression wildcard."),
				menuRequiredArgument(5, "min-x", "float", "Minimum scale X."),
				menuRequiredArgument(6, "min-y", "float", "Minimum scale Y."),
				menuRequiredArgument(7, "min-z", "float", "Minimum scale Z."),
				menuRequiredArgument(8, "max-x", "float", "Maximum scale X."),
				menuRequiredArgument(9, "max-y", "float", "Maximum scale Y."),
				menuRequiredArgument(10, "max-z", "float", "Maximum scale Z."),
			)},
			"Sets the min/max scale vectors used by a hair-length data group.",
			"Supply exactly ten arguments and keep the slot, group, search mode, and bone name coherent.",
			"critical", menuSource, hairLengthSource,
		),
		menuCommand(
			"anime", nil, runtime,
			[]CommandForm{menuForm("anime <slot> <animation-file> [loop]", reviewed,
				menuRequiredArgument(1, "slot", "TBody.SlotID name", "The item slot receiving the animation; new-attach MPNs convert the virtual slot."),
				menuRequiredArgument(2, "animation-file", "animation resource name", "The animation loaded and played; a missing extension loads as .anm."),
				menuOptionalArgument(3, "loop", "literal flag", "false", "Loop when the exact literal loop is present.", "loop"),
			)},
			"Loads and plays an item animation at the current sub-slot index, optionally looping it.",
			"Verify the animation exists for the selected slot and use loop only when repeated playback is intended.",
			"high", menuSource, animationSource,
		),
		menuCommand(
			"param2", nil, runtime,
			[]CommandForm{menuForm("param2 <slot> <key> <value>", reviewed,
				menuRequiredArgument(1, "slot", "TBody.SlotID name", "The loaded slot receiving the secondary parameter."),
				menuRequiredArgument(2, "key", "string", "The secondary parameter key, stored without normalization."),
				menuRequiredArgument(3, "value", "string", "The secondary parameter value."),
			)},
			"Sets a secondary string parameter on a loaded slot; other argument counts are diagnosed.",
			"Supply exactly three arguments and preserve the key spelling expected by the target slot implementation.",
			"high", menuSource,
		),
		menuCommand(
			"animematerial", nil, runtime,
			[]CommandForm{menuForm("animematerial <slot> <material-index>", reviewed,
				menuRequiredArgument(1, "slot", "TBody.SlotID name", "The slot whose material is animated; new-attach MPNs convert the virtual slot."),
				menuRequiredArgument(2, "material-index", "int", "The material added to the material animator."),
			)},
			"Adds one slot material to the material-animation controller at the current sub-slot index.",
			"Verify the material index and ensure the selected slot has a compatible animation controller.",
			"high", menuSource,
		),
		menuCommand(
			"uv定義", nil, runtime,
			[]CommandForm{menuForm("uv定義 <slot> <tag> <u>:<v>", reviewed,
				menuRequiredArgument(1, "slot", "TBody.SlotID name", "The slot owning the UV definition."),
				menuRequiredArgument(2, "tag", "string", "The definition tag used by later lookups."),
				menuRequiredArgument(3, "uv", "u:v pair", "The normalized UV coordinate split at the colon."),
			)},
			"Registers a named UV position for the mole/tattoo placement system.",
			"Use values in the normalized 0..1 range and keep the tag unique.",
			"medium", menuSource,
		),
		menuCommand(
			"ほくろ合成", []string{"ひげ合成", "しみ合成", "しわ合成", "体毛合成"}, runtime,
			[]CommandForm{menuForm("ほくろ合成 <del|hash> [<hash>]", reviewed,
				menuRequiredArgument(1, "mode", "del or hash token", "del removes the composite; hash adds the referenced precompiled composite.", "del", "hash"),
				menuOptionalArgument(2, "hash", "ulong", "", "The precompile hash resolved against the menu preMulTexDatas dictionary."),
			)},
			"Adds a precompiled skin composite by hash or removes the current one; the aliases select the matching multi-move texture group (mole, beard, blemish, wrinkle, or body hair).",
			"Runtime hash application requires the current property base to be a sub-slot prop; an unmatched hash leaves state unchanged.",
			"high", menuSource,
		),
		menuCommand(
			"タトゥ合成", nil, runtime,
			[]CommandForm{menuForm("タトゥ合成 <del|hash> [<hash>]", reviewed,
				menuRequiredArgument(1, "mode", "del or hash token", "del removes the tattoo composite; hash adds the referenced precompiled composite.", "del", "hash"),
				menuOptionalArgument(2, "hash", "ulong", "", "The precompile hash resolved against the menu preMulTexDatas dictionary."),
			)},
			"Adds a precompiled tattoo composite by hash or removes the current one.",
			"Runtime hash application requires the current property base to be a sub-slot prop.",
			"high", menuSource,
		),
		menuCommand(
			"そばかす合成", nil, runtime,
			[]CommandForm{menuForm("そばかす合成 <del|hash> [<hash>]", reviewed,
				menuRequiredArgument(1, "mode", "del or hash token", "del removes the freckle composite; hash adds the referenced precompiled composite.", "del", "hash"),
				menuOptionalArgument(2, "hash", "ulong", "", "The precompile hash resolved against the menu preMulTexDatas dictionary."),
			)},
			"Adds a precompiled freckle composite by hash or removes the current one.",
			"Runtime hash application requires the current property base to be a sub-slot prop.",
			"high", menuSource,
		),
		menuCommand(
			"ネイル合成", nil, runtime,
			[]CommandForm{menuForm("ネイル合成 <del|hash> [<hash>]", reviewed,
				menuRequiredArgument(1, "mode", "del or hash token", "del removes the nail composite; hash adds the referenced precompiled composite.", "del", "hash"),
				menuOptionalArgument(2, "hash", "ulong", "", "The precompile hash resolved against the menu preMulTexDatas dictionary."),
			)},
			"Adds a precompiled nail composite by hash or removes the current one.",
			"Runtime hash application requires the current property base to be a sub-slot prop.",
			"high", menuSource,
		),
		menuCommand(
			"メイク合成", nil, runtime,
			[]CommandForm{
				menuForm("メイク合成 <slot> <material-index> <property-name> <layer-index> <texture-file> <blend-mode> <color-type> <u>:<v> [<hsl>]", reviewed,
					menuRequiredArgument(1, "slot", "TBody.SlotID name", "The target slot; also selects the material index for the generated save tag."),
					menuRequiredArgument(2, "material-index", "int", "The target material."),
					menuRequiredArgument(3, "property-name", "shader texture property name", "The texture property to composite."),
					menuRequiredArgument(4, "layer-index", "int", "The composition layer."),
					menuRequiredArgument(5, "texture-file", "texture resource name", "The layer texture."),
					menuRequiredArgument(6, "blend-mode", "GameUtility.SystemMaterial enum name", "The composition blend mode."),
					menuRequiredArgument(7, "color-type", "COLOR_TYPE enum name", "NONE, INF_COLOR, PART_COLOR, or GRADA_COLOR; only INF_COLOR consumes the HSL argument.", "NONE", "INF_COLOR", "PART_COLOR", "GRADA_COLOR"),
					menuRequiredArgument(8, "uv", "u:v pair", "The layer UV position split at the colon."),
					menuOptionalArgument(9, "hsl", "HSL description", "", "Color data applied only when color-type is INF_COLOR."),
				),
				menuForm("メイク合成 del <slot> <material-index> <property-name> <layer-id>", reviewed,
					menuRequiredArgument(2, "slot", "TBody.SlotID name", "The slot whose make-up layer is removed."),
					menuRequiredArgument(3, "material-index", "int", "The material."),
					menuRequiredArgument(4, "property-name", "shader texture property name", "The property."),
					menuRequiredArgument(5, "layer-id", "int", "The layer ID to remove."),
				),
			},
			"Composites a make-up layer with a UV position and optional infinite color, using an automatically generated メイク<MPN><sub-slot> save tag; the deletion form removes a layer by ID.",
			"Keep the HSL argument only for INF_COLOR, and preserve the automatic tag naming rather than attempting to author it.",
			"high", menuSource,
		),
		menuCommand(
			"meshmorph", nil, runtime,
			[]CommandForm{menuForm("meshmorph <tag> <morph-name> def=<percent>", reviewed,
				menuRequiredArgument(1, "tag", "TMorphSkin.BaseBlendValue.Tag enum name", "Selects one concrete base-blend group.", "パンツ", "靴下"),
				menuRequiredArgument(2, "morph-name", "mesh morph name", "The mesh morph entry on the current additem slot."),
				menuRequiredArgument(3, "default-token", "def=<int> token", "Default value as an integer percent; the runtime multiplies it by 0.01."),
			)},
			"Adds a default mesh base-blend value to the current additem slot at the current sub-slot index.",
			"Use only after additem has established the current slot and keep the def= prefix and integer percent intact.",
			"critical", menuSource,
		),
		menuCommand(
			"addbonemorph", nil, runtime,
			[]CommandForm{menuFormWithNotes("addbonemorph <slot> 裾 (<target-bone> [pos=<vec3>~<vec3>] [rot=<vec3>~<vec3>] [scl=<vec3>~<vec3>])+", reviewed,
				"Both discriminators are hard-asserted: the slot must parse to wear and the group must be exactly 裾. Each plain target-bone token starts a new morph; following pos/rot/scl tokens attach ranges to it, each vector being one parser-accepted Vector3 text joined by ~.",
				menuRequiredArgument(1, "slot", "TBody.SlotID enum name", "Morph owner; the reviewed path requires wear.", "wear"),
				menuRequiredArgument(2, "group", "literal group name", "The reviewed skirt-hem group 裾.", "裾"),
				menuRequiredRepeatableArgument(3, "target-bone-or-transform-token", "bone name or pos/rot/scl=<vec3>~<vec3> token", "Defines one target bone and its optional position, rotation, and scale ranges."),
			)},
			"Adds custom bone morph records for the wear skirt hem from alternating bone and transform-range tokens.",
			"Keep each target bone followed by only valid pos, rot, or scl tokens and preserve both required discriminator literals.",
			"critical", menuSource,
		),
		menuCommand(
			"乳首", nil, runtime,
			[]CommandForm{menuForm("乳首 <state>", reviewed,
				menuRequiredArgument(1, "state", "TBodySkin.CHIKUBI_STATE enum name", "The nipple state applied to the current additem slot and sub-slot.", "None", "固定凸", "基本凹"),
			)},
			"Sets the nipple state on the current additem slot at the current sub-slot index.",
			"Use an enum value valid for the target body and place it after the additem that establishes the current slot.",
			"high", menuSource,
		),
		menuCommand(
			"adjcutoff", nil, runtime,
			[]CommandForm{menuForm("adjcutoff <index> <texture-name> (<threshold>:<tag>)+", reviewed,
				menuRequiredArgument(1, "index", "int", "The cutoff material slot index on the current additem slot."),
				menuRequiredArgument(2, "texture-name", "string", "The cutoff texture name."),
				menuRequiredRepeatableArgument(3, "threshold-tag", "float:tag token", "One cutoff threshold with an optional tag after the colon; tokens repeat without the tag."),
			)},
			"Configures cutoff-mask thresholds and optional tags on the current additem slot at the current sub-slot index.",
			"Use only after additem has established the current slot and keep thresholds ascending.",
			"high", menuSource,
		),
		menuCommand(
			"parthidemove", nil, runtime,
			[]CommandForm{menuForm("parthidemove <part-name> <mode> <hide-type> <slot> [hide=<flag>] [center=<bone-name>]", reviewed,
				menuRequiredArgument(1, "part-name", "part name", "The part entry the hide or move applies to."),
				menuRequiredArgument(2, "mode", "MOVE_HIDE_MODE flags", "Ampersand-combined MOVE and HIDE flags parsed case-sensitively.", "HIDE", "MOVE", "MOVE&HIDE"),
				menuRequiredArgument(3, "hide-type", "PART_HIDE_TYPE enum name", "Slot-visible or bone-weight hiding strategy.", "TYPE_SLOT_VISIBLE", "TYPE_BONE_WEIGHT"),
				menuRequiredArgument(4, "slot", "TBody.SlotID name", "The slot receiving the part-hide registration."),
				menuOptionalArgument(5, "hide-option", "hide=true or hide=false token", "", "Initial visibility override; the comparison is case-insensitive."),
				menuOptionalArgument(6, "center-option", "center=<bone-name> token", "", "Optional center bone for the move mode."),
			)},
			"Registers a part hide/move on the selected slot at the current sub-slot index.",
			"Write MOVE and HIDE exactly as declared and keep the part name synchronized with the saved attachment data.",
			"critical", menuSource,
		),
		menuCommand(
			"房tex", nil, runtime,
			[]CommandForm{menuFormWithNotes("房tex <slot> <number>=<tag> <mask-texture> <center>#<width> (<color-tag>=<texture-file>)+", reviewed,
				"Later 房tex records for the same slot reuse the first record's render target through the shared-target tag, so command order matters. The center and width accept 0..255 integers divided by 255 or plain floats, and the runtime requires a non-null property base.",
				menuRequiredArgument(1, "slot", "TBody.SlotID name", "The hair-tuft slot."),
				menuRequiredArgument(2, "number-tag", "int=string token", "The sub-slot number and tuft tag split at the equals sign."),
				menuRequiredArgument(3, "mask-texture", "texture resource name", "The tuft mask texture."),
				menuRequiredArgument(4, "center-width", "center#width token", "Mask center and width split at the hash mark."),
				menuRequiredRepeatableArgument(5, "color-definition", "tag=texture-file token", "One gradation color definition per tuft, split at the equals sign."),
			)},
			"Composites hair-tuft color layers with a shared mask on a sub-slot of the target hair slot.",
			"Keep the shared-render-target ordering in mind when several tufts target the same slot and keep every color tag unique.",
			"high", menuSource, materialMgrGroupSource,
		),
		menuCommand(
			"ちんこ", nil, runtime,
			[]CommandForm{menuForm("ちんこ <state>", reviewed,
				menuRequiredArgument(1, "state", "TBodySkin.CHINKO_STATE enum name", "The penis state applied to the current additem slot and sub-slot.", "None", "しまう"),
			)},
			"Sets the penis state on the current additem slot at the current sub-slot index.",
			"Use an enum value valid for the target body and preserve current-slot ordering.",
			"high", menuSource,
		),
		menuCommand(
			"タッチ範囲tex", nil, runtime,
			[]CommandForm{menuForm("タッチ範囲tex <slot> <material-index> <texture-file>", reviewed,
				menuRequiredArgument(1, "slot", "TBody.SlotID name", "The slot whose touch-area texture changes at the current sub-slot index."),
				menuRequiredArgument(2, "material-index", "int", "The material receiving the touch-area texture."),
				menuRequiredArgument(3, "texture-file", "texture resource name", "The touch-area texture."),
			)},
			"Sets the edit touch-area texture on one slot material.",
			"Verify the material index and that the texture exists in the target build.",
			"medium", menuSource,
		),
		menuCommand(
			"commenttype", nil, runtime,
			[]CommandForm{menuForm("commenttype <comment>...", reviewed,
				menuRequiredRepeatableArgument(1, "comment", "string", "Free-form comment tokens; nothing is executed."),
			)},
			"The reviewed runtime has no commenttype brunch, so the record is silently skipped.",
			"Preserve existing values for round-tripping; do not place stateful intent inside it.",
			"low", menuSource,
		),
		menuCommand(
			"saveitem", nil, runtime,
			[]CommandForm{menuForm("saveitem", reviewed)},
			"The reviewed runtime has no saveitem branch, so the record is silently skipped; it is a legacy opcode.",
			"Preserve existing records for round-tripping, but do not rely on it for any game effect.",
			"low", menuSource,
		),
		menuCommand(
			"set", nil, runtime,
			[]CommandForm{menuForm("set <opaque-argument>...", reviewed,
				menuRequiredRepeatableArgument(1, "opaque-argument", "string", "Arguments are never read by the reviewed runtime."),
			)},
			"The reviewed runtime has no set branch, so the record is silently skipped; it is a legacy opcode.",
			"Preserve existing arguments because another unreviewed producer or consumer may assign meaning to them.",
			"low", menuSource,
		),
		menuCommand(
			"setname", nil, runtime,
			[]CommandForm{menuForm("setname <opaque-argument>...", reviewed,
				menuRequiredRepeatableArgument(1, "opaque-argument", "string", "Arguments are never read by the reviewed runtime."),
			)},
			"The reviewed runtime has no setname branch, so the record is silently skipped; it is a legacy opcode.",
			"Preserve existing arguments because their authoring contract is not established by the reviewed path.",
			"low", menuSource,
		),
		menuCommand(
			"テクスチャ乗算", nil, runtime,
			[]CommandForm{menuForm("テクスチャ乗算 <opaque-argument>...", reviewed,
				menuRequiredRepeatableArgument(1, "opaque-argument", "string", "Arguments are never read by the reviewed runtime."),
			)},
			"The reviewed runtime has no multiplication branch and the opcode appears only in the type catalog.",
			"Preserve existing arguments; use the composition opcodes for compositing.",
			"low", menuSource))

	return linkKces2MenuArgumentValueSets(commands)
}

// linkKces2MenuArgumentValueSets 根据参数类型把已验证的 KCES2 精确值集合绑定到每个命令参数上
// linkKces2MenuArgumentValueSets binds exact reviewed KCES2 value sets onto command arguments according to argument type
func linkKces2MenuArgumentValueSets(commands []Command) []Command {
	for commandIndex := range commands {
		for formIndex := range commands[commandIndex].Forms {
			form := &commands[commandIndex].Forms[formIndex]
			for argumentIndex := range commands[commandIndex].Forms[formIndex].Arguments {
				argument := &form.Arguments[argumentIndex]
				switch {
				case strings.Contains(argument.Type, "TBody.SlotID enum") || strings.Contains(argument.Type, "TBody.SlotID name") || argument.Type == "TBody.SlotID name" || argument.Type == "TBody.SlotID enum name":
					argument.ValueSetRefs = []string{kces2SlotIDValueSetID}
				case strings.Contains(argument.Type, "MPN"):
					argument.ValueSetRefs = []string{kces2MPNValueSetID}
				case strings.Contains(argument.Type, "PARTS_COLOR"):
					argument.ValueSetRefs = []string{kces2PartsColorValueSetID}
				case strings.Contains(argument.Type, "GameUtility.SystemMaterial"):
					argument.ValueSetRefs = []string{kces2SystemMaterialValueSetID}
				case strings.Contains(argument.Type, "ALPHA_TYPE"):
					argument.ValueSetRefs = []string{kces2AlphaTypeValueSetID}
				case strings.Contains(argument.Type, "CHIKUBI_STATE"):
					argument.ValueSetRefs = []string{kces2ChikubiStateValueSetID}
				case strings.Contains(argument.Type, "CHINKO_STATE"):
					argument.ValueSetRefs = []string{kces2ChinkoStateValueSetID}
				case strings.Contains(argument.Type, "BaseBlendValue.Tag"):
					argument.ValueSetRefs = []string{kces2MeshMorphTagValueSetID}
				case strings.Contains(argument.Type, "TargetBodyType"):
					argument.ValueSetRefs = []string{kces2TargetBodyTypeValueSetID}
				case strings.Contains(argument.Type, "Menu.DEFINE"):
					argument.ValueSetRefs = []string{kces2DefineValueSetID}
				case strings.Contains(argument.Type, "Menu.Attribute"):
					argument.ValueSetRefs = []string{kces2AttributeValueSetID}
				case strings.Contains(argument.Type, "MOVE_HIDE_MODE"):
					argument.ValueSetRefs = []string{kces2MoveHideModeValueSetID}
				case strings.Contains(argument.Type, "PART_HIDE_TYPE"):
					argument.ValueSetRefs = []string{kces2PartHideTypeValueSetID}
				case strings.Contains(argument.Type, "HaraYureLimitType"):
					argument.ValueSetRefs = []string{kces2HaraYureValueSetID}
				case strings.Contains(argument.Type, "bone-search mode") || argument.Type == "literal enum" && strings.Contains(strings.ToLower(argument.Name), "search"):
					// 仅限 length 的骨骼搜索选择器，避免把其它 literal enum 误链接
					if strings.Contains(argument.Name, "bone-search") {
						argument.ValueSetRefs = []string{kces2HairSearchTypeValueSetID}
					}
				}
			}
		}
	}
	return commands
}
