package knowledgev1

import "strings"

func com3d2MenuCommands(compileSource, menuSource, sceneSource, compile3Source, menu3Source, scene3Source, materialMgr3Source Source) []Command {
	reviewedBoth := []string{"COM3D2 2.48.0", "COM3D2_5 3.48.0"}
	reviewed348 := []string{"COM3D2_5 3.48.0"}
	runtimeBoth := []string{"runtime interpreter (COM3D2 2.48.0)", "runtime interpreter (COM3D2_5 3.48.0)"}
	runtime348 := []string{"runtime interpreter (COM3D2_5 3.48.0)"}
	editorBoth := []string{"SceneEdit metadata scan (COM3D2 2.48.0)", "SceneEdit metadata scan (COM3D2_5 3.48.0)"}
	compilerBoth := []string{"official text-menu compiler (COM3D2 2.48.0)", "official text-menu compiler (COM3D2_5 3.48.0)"}

	commands := []Command{
		// Stream control and editor/compiler metadata.
		menuCommand(
			"end", nil, runtimeBoth,
			[]CommandForm{menuForm("end", reviewedBoth)},
			"Stops command interpretation immediately. The encoded zero-count record also terminates the stream.",
			"Normally let the serializer write the zero terminator. Keep an explicit end only when early termination is intentional.",
			"critical", menuSource, menu3Source,
		),
		menuCommand(
			"#if", nil, runtimeBoth,
			[]CommandForm{menuForm("#if isplugin in <plugin-expression>", reviewedBoth,
				menuRequiredArgument(3, "plugin-expression", "ampersand-separated plugin identifiers", "Each identifier is checked for availability; isCREditSystemSupport is handled as a special capability identifier."),
			)},
			"Skips subsequent records when any requested plugin or capability is unavailable, until the matching #else or #endif state change.",
			"Use only the reviewed isplugin in form. The interpreter stores one condition state, so do not assume nested conditionals are supported.",
			"critical", menuSource, menu3Source,
		),
		menuCommand(
			"#else", nil, runtimeBoth,
			[]CommandForm{menuForm("#else", reviewedBoth)},
			"Switches execution to the alternate branch of the current plugin condition.",
			"Keep it paired with a preceding #if and a following #endif; moving it changes which stateful commands execute.",
			"critical", menuSource, menu3Source,
		),
		menuCommand(
			"#endif", nil, runtimeBoth,
			[]CommandForm{menuForm("#endif", reviewedBoth)},
			"Clears the current plugin-condition skip state.",
			"Do not remove it from a conditional region; otherwise later commands may remain skipped.",
			"critical", menuSource, menu3Source,
		),
		menuCommand(
			"name", nil, append(append([]string{}, runtimeBoth...), append(editorBoth, compilerBoth...)...),
			[]CommandForm{menuForm("name <display-name>", reviewedBoth,
				menuRequiredArgument(1, "display-name", "string", "The first argument is copied into the compiled header; SceneEdit displays the portion before the first normal or full-width space."),
			)},
			"Supplies the item display name to the compiler and editor. The runtime interpreter recognizes the opcode but performs no body operation.",
			"Keep the command value synchronized with ItemName. Quote it as one argument when it contains spaces.",
			"medium", compileSource, sceneSource, compile3Source, scene3Source, menuSource, menu3Source,
		),
		menuCommand(
			"setumei", nil, append(editorBoth, compilerBoth...),
			[]CommandForm{menuForm("setumei <description>", reviewedBoth,
				menuRequiredArgument(1, "description", "string", "SceneEdit uses this text as the item description and expands the game's line-break marker."),
			)},
			"Supplies the item description to the compiler and SceneEdit metadata scan.",
			"Keep the command value synchronized with InfoText and quote the complete description as one argument.",
			"medium", compileSource, sceneSource, compile3Source, scene3Source,
		),
		menuCommand(
			"category", nil, append(append([]string{}, runtimeBoth...), append(editorBoth, compilerBoth...)...),
			[]CommandForm{menuForm("category <mpn>", reviewedBoth,
				menuRequiredArgument(1, "mpn", "MPN enum name", "Becomes the current source category for later item, mask, texture, and material commands and the editor category metadata."),
			)},
			"Changes the current MPN/category state used by subsequent runtime commands and by SceneEdit.",
			"Use an MPN present in the target build, place it before dependent commands, and keep Category synchronized.",
			"critical", compileSource, sceneSource, compile3Source, scene3Source, menuSource, menu3Source,
		),
		menuCommand(
			"icon", []string{"icons"}, editorBoth,
			[]CommandForm{menuForm("icon <texture-file>", reviewedBoth,
				menuRequiredArgument(1, "texture-file", "texture resource name", "Names the icon texture loaded for the SceneEdit item."),
			)},
			"Selects the item's SceneEdit icon; icons is processed identically.",
			"Keep the texture resource available in the target game archives. Use either opcode without changing its argument layout.",
			"medium", sceneSource, scene3Source,
		),
		menuCommand(
			"iconl", nil, editorBoth,
			[]CommandForm{menuForm("iconl [<opaque-argument>...]", reviewedBoth,
				menuOptionalRepeatableArgument(1, "opaque-argument", "string", "The reviewed SceneEdit scanners recognize and ignore this legacy opcode without reading its arguments."),
			)},
			"Acts as a legacy metadata marker in the reviewed SceneEdit path; no argument is consumed there.",
			"Preserve existing arguments byte-for-byte. The reviewed source does not establish an authoring contract for them.",
			"low", sceneSource, scene3Source,
		),
		menuCommand(
			"setstr", nil, editorBoth,
			[]CommandForm{menuForm("setstr [<opaque-argument>...]", reviewedBoth,
				menuOptionalRepeatableArgument(1, "opaque-argument", "string", "The reviewed SceneEdit scanners recognize and ignore this legacy opcode without reading its arguments."),
			)},
			"Acts as a legacy metadata marker in the reviewed SceneEdit path; no argument is consumed there.",
			"Preserve existing arguments byte-for-byte because their meaning is not established by the reviewed readers.",
			"low", sceneSource, scene3Source,
		),
		menuCommand(
			"catno", nil, editorBoth,
			[]CommandForm{menuForm("catno [<opaque-argument>...]", reviewedBoth,
				menuOptionalRepeatableArgument(1, "opaque-argument", "string", "The reviewed SceneEdit scanners explicitly skip this legacy opcode without reading its arguments."),
			)},
			"Has no observed effect in the reviewed SceneEdit metadata path.",
			"Preserve existing arguments; do not infer that this value replaces category.",
			"low", sceneSource, scene3Source,
		),
		menuCommand(
			"unsetitem", nil, editorBoth,
			[]CommandForm{menuForm("unsetitem", reviewedBoth)},
			"Marks the SceneEdit item as deletion-only.",
			"Use only for an item intended to remove an equipped category entry.",
			"high", sceneSource, scene3Source,
		),
		menuCommand(
			"priority", nil, editorBoth,
			[]CommandForm{menuForm("priority <value>", reviewedBoth,
				menuRequiredArgument(1, "value", "float", "Sets the SceneEdit item's sorting priority."),
			)},
			"Changes the ordering priority recorded for the SceneEdit item.",
			"Use a finite float and compare nearby items before changing established ordering.",
			"medium", sceneSource, scene3Source,
		),
		menuCommand(
			"メニューフォルダ", nil, append(editorBoth, compilerBoth...),
			[]CommandForm{menuForm("メニューフォルダ <folder>", reviewedBoth,
				menuRequiredArgument(1, "folder", "string", "The compiler uses this as menu-folder metadata; SceneEdit additionally treats man as a male-item marker."),
			)},
			"Supplies the menu folder to the compiler and marks the item as male in SceneEdit when the value is man.",
			"Keep the value consistent with the source directory and use man only for male-targeted entries.",
			"high", compileSource, sceneSource, compile3Source, scene3Source,
		),
		menuCommand(
			"collabo", nil, editorBoth,
			[]CommandForm{menuForm("collabo", reviewedBoth)},
			"Marks the SceneEdit item as collaboration content.",
			"Preserve it when editing collaboration items; removing it changes editor metadata classification.",
			"medium", sceneSource, scene3Source,
		),
		menuCommand(
			"color_set", nil, editorBoth,
			[]CommandForm{menuForm("color_set <mpn> [<menu-name>]", reviewedBoth,
				menuRequiredArgument(1, "mpn", "MPN enum name", "Selects the category whose color-set metadata this item belongs to."),
				menuOptionalArgument(2, "menu-name", "string", "", "Optionally records a lower-cased menu name within the color set."),
			)},
			"Associates the item with SceneEdit color-set metadata and an optional member menu name.",
			"Use a valid MPN and keep the optional menu name synchronized with the referenced item.",
			"high", sceneSource, scene3Source,
		),
		menuCommand(
			"saveitem", nil, append(runtimeBoth, editorBoth...),
			[]CommandForm{menuForm("saveitem <identifier>", reviewedBoth,
				menuRequiredArgument(1, "identifier", "string", "A legacy save-item identifier. SceneEdit only checks that it is nonempty; the reviewed runtime stores it without a later observed read."),
			)},
			"Carries legacy save-item metadata; it does not directly add or remove a body item in the reviewed paths.",
			"Keep an existing nonempty value. Do not rely on it to replace category or additem.",
			"medium", sceneSource, scene3Source, menuSource, menu3Source,
		),
		menuCommand(
			"set", nil, runtimeBoth,
			[]CommandForm{menuForm("set [<opaque-argument>...]", reviewedBoth,
				menuOptionalRepeatableArgument(1, "opaque-argument", "string", "The reviewed runtime explicitly accepts this opcode but does not inspect its arguments."),
			)},
			"Performs no operation in the reviewed runtime interpreter.",
			"Preserve existing arguments because another unreviewed producer or consumer may assign meaning to them.",
			"low", menuSource, menu3Source,
		),
		menuCommand(
			"setname", nil, runtimeBoth,
			[]CommandForm{menuForm("setname [<opaque-argument>...]", reviewedBoth,
				menuOptionalRepeatableArgument(1, "opaque-argument", "string", "The reviewed runtime explicitly accepts this opcode but does not inspect its arguments."),
			)},
			"Performs no operation in the reviewed runtime interpreter.",
			"Preserve existing arguments because their authoring contract is not established by the reviewed path.",
			"low", menuSource, menu3Source,
		),
		menuCommand(
			"ver", nil, runtimeBoth,
			[]CommandForm{
				menuForm("ver <slot> <parts-version>", reviewedBoth,
					menuRequiredArgument(1, "slot", "TBody.SlotID name", "Selects or validates the slot whose model version context is being established."),
					menuRequiredArgument(2, "parts-version", "int", "Becomes the version passed to a later additem operation."),
				),
				menuForm("ver <parts-version>", reviewed348,
					menuRequiredArgument(1, "parts-version", "int", "Sets the additem version while retaining the current CRC target-slot context."),
				),
			},
			"Changes the version state passed into subsequent model loading. The one-argument form exists only in the reviewed 3.48 interpreter.",
			"Keep it before the additem records it controls. Do not collapse the two forms across target game versions.",
			"critical", menuSource, menu3Source,
		),
	}

	commands = append(commands,
		// COM3D2_5 CRC-body state and conditional resource loading.
		menuCommand(
			"crc_exp", nil, runtime348,
			[]CommandForm{menuForm("crc_exp", reviewed348)},
			"Enables the CRC explicit-part loading mode used by later additem records.",
			"Place it before the additem records that require CRC explicit handling; it is not recognized by the reviewed 2.48 interpreter.",
			"critical", menu3Source,
		),
		menuCommand(
			"crc_def_exp", nil, runtime348,
			[]CommandForm{menuForm("crc_def_exp", reviewed348)},
			"Marks the current CRC loading sequence as the default explicit case, affecting which split slots are loaded.",
			"Preserve its position relative to crc_exp and split-enabled additem commands.",
			"critical", menu3Source,
		),
		menuCommand(
			"crc_target_slotno", nil, runtime348,
			[]CommandForm{menuForm("crc_target_slotno <slot-index>", reviewed348,
				menuRequiredArgument(1, "slot-index", "int", "Sets the sub-slot index supplied to later CRC slot and item operations."),
			)},
			"Changes the current CRC target sub-slot index.",
			"Keep it before every command group that targets a non-default sub-slot and restore the intended index for later groups.",
			"critical", menu3Source,
		),
		menuCommand(
			"crc_part_hide_slot", nil, runtime348,
			[]CommandForm{menuForm("crc_part_hide_slot <slot> <visible>", reviewed348,
				menuRequiredArgument(1, "slot", "TBody.SlotID name", "Selects the slot at the current crc_target_slotno index."),
				menuRequiredArgument(2, "visible", "bool", "Sets the slot's CRC part-hide visibility flag."),
			)},
			"Sets whether the selected CRC slot participates visibly in part hiding.",
			"Use a bool accepted by bool.Parse and verify the current target sub-slot index.",
			"high", menu3Source,
		),
		menuCommand(
			"crc_part_hide_move", nil, runtime348,
			[]CommandForm{menuForm("crc_part_hide_move <slot> <saved-attach-file>", reviewed348,
				menuRequiredArgument(1, "slot", "TBody.SlotID name", "Selects the slot at the current crc_target_slotno index."),
				menuRequiredArgument(2, "saved-attach-file", "SAVED_ATTACH_DATA resource name", "Loads saved attachment records into the selected slot."),
			)},
			"Imports saved CRC attachment positions for the selected slot.",
			"Verify the resource exists, has a SAVED_ATTACH_DATA header, and matches the target model and sub-slot.",
			"critical", menu3Source,
		),
		menuCommand(
			"crc_mayu_front", nil, runtime348,
			[]CommandForm{menuForm("crc_mayu_front <enabled>", reviewed348,
				menuRequiredArgument(1, "enabled", "bool", "Selects the eyebrow material ZTest value used for front rendering."),
			)},
			"Changes the eyebrow materials' _ZTest2 property to render in front or with the normal comparison mode.",
			"Use a bool accepted by bool.Parse and test eyebrow ordering with hair and face materials.",
			"high", menu3Source,
		),
		menuCommand(
			"crc_mayu_alpha", nil, runtime348,
			[]CommandForm{menuForm("crc_mayu_alpha <alpha>", reviewed348,
				menuRequiredArgument(1, "alpha", "float", "Becomes the alpha component of the eyebrow materials' _Color value."),
			)},
			"Sets eyebrow material alpha on the two reviewed head material indices.",
			"Use a finite value appropriate for a Unity color alpha, normally in the 0 to 1 range.",
			"high", menu3Source,
		),
		menuCommand(
			"crc_hair_length", nil, runtime348,
			[]CommandForm{menuForm("crc_hair_length <slot> <group-name> <value>", reviewed348,
				menuRequiredArgument(1, "slot", "TBody.SlotID name", "Selects the hair slot at the current target sub-slot index."),
				menuRequiredArgument(2, "group-name", "string", "Selects the registered hair-length group."),
				menuRequiredArgument(3, "value", "float", "Forces the selected hair-length group to this value."),
			)},
			"Overrides a hair-length group on the selected CRC slot.",
			"Use an existing group name and a finite value within the model's authored morph range.",
			"high", menu3Source,
		),
		menuCommand(
			"crc_mat_alpha", nil, runtime348,
			[]CommandForm{menuForm("crc_mat_alpha <slot> <material-index> <alpha>", reviewed348,
				menuRequiredArgument(1, "slot", "TBody.SlotID name", "Selects the slot at the current target sub-slot index. Its model must already have been loaded by an earlier command."),
				menuRequiredArgument(2, "material-index", "int", "Indexes the loaded slot's material array directly; an out-of-range value can raise a runtime exception."),
				menuRequiredArgument(3, "alpha", "float", "Immediately replaces the selected material color's alpha component."),
			)},
			"Immediately sets one already-loaded female CRC slot material's alpha. An unloaded slot object is a silent no-op, and a male slot is always a no-op; the command is not queued for later application.",
			"Place it after the command that loads the target slot model. Verify the material index against that exact model to avoid an out-of-range runtime exception, and use a finite alpha, normally in the 0 to 1 range.",
			"critical", menu3Source, materialMgr3Source,
		),
		menuCommand(
			"crc_target_body_type", nil, runtime348,
			[]CommandForm{menuForm("crc_target_body_type <body-type>", reviewed348,
				menuRequiredArgument(1, "body-type", "TBodySkin.TargetBodyType enum name", "Sets the body-type selector passed to later additem records.", "None", "Woman", "Man"),
			)},
			"Changes the target body-type state for subsequent CRC model loading.",
			"Keep it adjacent to the additem group it controls and use an enum name with exact reviewed spelling.",
			"critical", menu3Source,
		),
		menuCommand(
			"parthidemove", nil, runtime348,
			[]CommandForm{menuFormWithNotes("parthidemove <part-name> <reserved-2> <reserved-3> <slot>", reviewed348,
				"The reviewed interpreter reads positions 1 and 4 only; positions 2 and 3 remain required for this observed four-argument layout but their meaning is not established by this path.",
				menuRequiredArgument(1, "part-name", "saved attachment part name", "Finds and applies the matching enabled SavedAttachData entry."),
				menuRequiredArgument(2, "reserved-2", "opaque string", "Serialized compatibility token not read by the reviewed interpreter."),
				menuRequiredArgument(3, "reserved-3", "opaque string", "Serialized compatibility token not read by the reviewed interpreter."),
				menuRequiredArgument(4, "slot", "TBody.SlotID name", "Selects the slot at the current target sub-slot index."),
			)},
			"Applies a previously imported saved attachment position to a CRC slot.",
			"Preserve the two opaque compatibility tokens and ensure crc_part_hide_move imported the named part before this command.",
			"critical", menu3Source,
		),
		menuCommand(
			"skirt_phys", nil, runtime348,
			[]CommandForm{menuForm("skirt_phys <mode>", reviewed348,
				menuRequiredArgument(1, "mode", "int", "Sets the skirt-physics mode value passed to subsequent additem model loading."),
			)},
			"Changes the skirt-physics state supplied to later model loads.",
			"Preserve known values from working menus unless the target model's expected mode is verified.",
			"high", menu3Source,
		),
		menuCommand(
			"アイテム", nil, runtimeBoth,
			[]CommandForm{menuForm("アイテム <menu-file>", reviewedBoth,
				menuRequiredArgument(1, "menu-file", "menu resource name", "Loads and executes the referenced compiled menu for the current maid."),
			)},
			"Applies another menu file immediately, with CRC deletion tracking in the reviewed 3.48 path.",
			"Verify the referenced menu exists and avoid recursive reference cycles.",
			"critical", menuSource, menu3Source,
		),
		menuCommand(
			"alldelmenu", nil, runtime348,
			[]CommandForm{menuForm("alldelmenu", reviewed348)},
			"Executes every menu registered in the game's global category-to-deletion-menu table.",
			"Use only when a full category cleanup is intended; it can remove many equipped items.",
			"critical", menu3Source,
		),
		menuCommand(
			"アイテム条件", nil, runtimeBoth,
			[]CommandForm{
				menuForm("アイテム条件 <slot> に何か <presence> なら <menu-file>", reviewedBoth,
					menuRequiredArgument(1, "slot", "TBody.SlotID name", "Selects the slot whose loaded-object presence is tested."),
					menuRequiredArgument(3, "presence", "literal enum", "Selects whether the condition succeeds when an object exists or is absent.", "有る", "無い"),
					menuRequiredArgument(5, "menu-file", "menu resource name", "Executes this menu when the presence test succeeds."),
				),
				menuForm("アイテム条件 <slot> が <model-file> なら <menu-file>", reviewedBoth,
					menuRequiredArgument(1, "slot", "TBody.SlotID name", "Selects the slot whose current model file is tested."),
					menuRequiredArgument(3, "model-file", "model resource name", "Must equal the slot's current model file name."),
					menuRequiredArgument(5, "menu-file", "menu resource name", "Executes this menu when the model-name test succeeds."),
				),
				menuForm("アイテム条件 <slot> のアイテムパラメータの <parameter-name> が <value> なら <menu-file>", reviewedBoth,
					menuRequiredArgument(1, "slot", "TBody.SlotID name", "Selects the slot whose item parameter is tested."),
					menuRequiredArgument(3, "parameter-name", "string", "Names the lower-cased item parameter to read."),
					menuRequiredArgument(5, "value", "string", "Is lower-cased and compared with the current parameter value."),
					menuRequiredArgument(7, "menu-file", "menu resource name", "Executes this menu when the parameter test succeeds."),
				),
			},
			"Conditionally executes another menu based on slot presence, current model identity, or an item parameter.",
			"Preserve the Japanese grammar literals at their exact positions and verify every referenced slot, model, parameter, and menu.",
			"critical", menuSource, menu3Source,
		),
		menuCommand(
			"if", nil, runtimeBoth,
			[]CommandForm{
				menuForm("if maidprop[<test-mpn>] == nothing ? setprop[<target-mpn>] = <value-expression>", reviewedBoth,
					menuRequiredArgument(1, "test-expression", "maidprop[MPN] expression", "Tests whether the selected maid property has no assigned file."),
					menuRequiredArgument(5, "target-expression", "setprop[MPN] expression", "Selects the property to assign when the test succeeds."),
					menuRequiredArgument(7, "value-expression", "resource name or getprop[MPN] expression", "Provides a literal resource name or copies another property's file name."),
				),
				menuForm("if slot[<slot>].ver < <parts-version> ? skip", reviewedBoth,
					menuRequiredArgument(1, "slot-version-expression", "slot[SlotID].ver expression", "Selects the slot whose PartsVersion is compared."),
					menuRequiredArgument(3, "parts-version", "int", "Stops processing the remainder of this menu when the slot version is lower."),
				),
			},
			"Either conditionally assigns a maid property or skips the rest of the current menu based on a slot version.",
			"Use only the two exact reviewed expression grammars; every operator and bracketed prefix is positional and case-sensitive after compilation.",
			"critical", menuSource, menu3Source,
		),
		menuCommand(
			"setprop", nil, runtime348,
			[]CommandForm{menuForm("setprop setprop[<target-mpn>] = <value-expression>", reviewed348,
				menuRequiredArgument(1, "target-expression", "setprop[MPN] expression", "Selects the maid property to assign."),
				menuRequiredArgument(3, "value-expression", "resource name or getprop[MPN] expression", "Provides a literal resource name or copies another property's file name."),
			)},
			"Assigns a maid property from a resource name or another property's file name when the value is nonempty.",
			"This standalone opcode is reviewed only in 3.48. Preserve the setprop[...] and optional getprop[...] expression spelling.",
			"critical", menu3Source,
		),
		menuCommand(
			"アイテムパラメータ", nil, append(runtimeBoth, compilerBoth...),
			[]CommandForm{menuForm("アイテムパラメータ <slot> <parameter-name> <value>", reviewedBoth,
				menuRequiredArgument(1, "slot", "TBody.SlotID name", "Selects the slot that receives the parameter."),
				menuRequiredArgument(2, "parameter-name", "string", "Names the parameter; the runtime normalizes it to lower case."),
				menuRequiredArgument(3, "value", "string", "Supplies the parameter value; the runtime normalizes it to lower case."),
			)},
			"Queues a named parameter to be applied to the selected loaded item.",
			"Supply exactly three arguments; the official compiler and runtime both diagnose any other count.",
			"high", compileSource, compile3Source, menuSource, menu3Source,
		),
		menuCommand(
			"半脱ぎ", nil, runtimeBoth,
			[]CommandForm{menuForm("半脱ぎ <resource-name>", reviewedBoth,
				menuRequiredArgument(1, "resource-name", "resource name", "Stores the resource under the fixed half-undressed lookup key for this menu file."),
			)},
			"Registers a half-undressed resource reference in the menu resource-reference table.",
			"Keep the resource available and preserve this command when the item supports a half-undressed variant.",
			"high", menuSource, menu3Source,
		),
		menuCommand(
			"リソース参照", nil, runtimeBoth,
			[]CommandForm{menuForm("リソース参照 <key> <resource-name>", reviewedBoth,
				menuRequiredArgument(1, "key", "string", "Names an entry in this menu file's resource-reference table."),
				menuRequiredArgument(2, "resource-name", "resource name", "Supplies the referenced resource value."),
			)},
			"Adds or replaces a named resource reference associated with this menu file.",
			"Keep keys unique unless replacement is intentional and verify the resource exists.",
			"high", menuSource, menu3Source,
		),
		menuCommand(
			"setslotitem", nil, runtimeBoth,
			[]CommandForm{menuForm("setslotitem <property-name> <resource-id>", reviewedBoth,
				menuRequiredArgument(1, "property-name", "maid property name", "Selects the maid property by name."),
				menuRequiredArgument(2, "resource-id", "uint32", "Assigns the numeric resource ID to that property."),
			)},
			"Sets a maid property directly from a numeric resource ID.",
			"Use a property name and resource ID valid in the target build; malformed or stale IDs can equip the wrong asset.",
			"critical", menuSource, menu3Source,
		),
	)

	commands = append(commands,
		// Model loading, visibility, masking, textures, and materials.
		menuCommand(
			"additem", nil, append(append([]string{}, runtimeBoth...), append(editorBoth, compilerBoth...)...),
			[]CommandForm{
				menuForm("additem <model-file> <slot>", reviewedBoth,
					menuRequiredArgument(1, "model-file", "model resource name", "Names the model loaded into the target slot."),
					menuRequiredArgument(2, "slot", "TBody.SlotID name", "Selects the destination slot; it also becomes the current slot for later attachment and morph commands."),
				),
				menuForm("additem <model-file> <slot> ボーンにアタッチ <bone-name>", reviewedBoth,
					menuRequiredArgument(1, "model-file", "model resource name", "Names the model loaded into the target slot."),
					menuRequiredArgument(2, "slot", "TBody.SlotID name", "Selects the destination slot."),
					menuRequiredArgument(4, "bone-name", "bone name", "Attaches the loaded model directly to this bone."),
				),
				menuForm("additem <model-file> <slot> アタッチ <attach-slot> <attach-point>", reviewedBoth,
					menuRequiredArgument(1, "model-file", "model resource name", "Names the model loaded into the target slot."),
					menuRequiredArgument(2, "slot", "TBody.SlotID name", "Selects the destination slot."),
					menuRequiredArgument(4, "attach-slot", "TBody.SlotID name", "Selects the slot that owns the destination attachment point."),
					menuRequiredArgument(5, "attach-point", "transform or attachment-point name", "Selects the destination position within attach-slot."),
				),
				menuFormWithNotes("additem <model-file> <slot> split:<split-spec>", reviewed348,
					"A split rule is slot=x<value, slot=x>value, slot=y<value, slot=y>value, slot=z<value, slot=z>value, or slot=boneA|boneB; multiple rules are joined with ampersands.",
					menuRequiredArgument(1, "model-file", "model resource name", "Names the model loaded into one or more split target slots."),
					menuRequiredArgument(2, "slot", "TBody.SlotID name", "Supplies the ordinary destination slot and CRC explicit-mode comparison slot."),
					menuRequiredArgument(3, "split-option", "split:<slot>=<rule>[&<slot>=<rule>...] token", "Defines target slots and either a clipping plane or split-part bone names."),
				),
				menuFormWithNotes("additem <model-file> <slot> ボーンにアタッチ <bone-name> split:<split-spec>", reviewed348,
					"The 3.48 interpreter independently detects the reviewed bone-attachment tokens and searches option tokens for the split prefix.",
					menuRequiredArgument(1, "model-file", "model resource name", "Names the model loaded into one or more split target slots."),
					menuRequiredArgument(2, "slot", "TBody.SlotID name", "Supplies the ordinary destination slot and CRC explicit-mode comparison slot."),
					menuRequiredArgument(4, "bone-name", "bone name", "Attaches each loaded split model directly to this bone."),
					menuRequiredArgument(5, "split-option", "split:<slot>=<rule>[&<slot>=<rule>...] token", "Defines target slots and either a clipping plane or split-part bone names."),
				),
				menuFormWithNotes("additem <model-file> <slot> アタッチ <attach-slot> <attach-point> split:<split-spec>", reviewed348,
					"The 3.48 interpreter independently detects the reviewed slot-attachment tokens and searches option tokens for the split prefix.",
					menuRequiredArgument(1, "model-file", "model resource name", "Names the model loaded into one or more split target slots."),
					menuRequiredArgument(2, "slot", "TBody.SlotID name", "Supplies the ordinary destination slot and CRC explicit-mode comparison slot."),
					menuRequiredArgument(4, "attach-slot", "TBody.SlotID name", "Selects the slot that owns the destination attachment point."),
					menuRequiredArgument(5, "attach-point", "transform or attachment-point name", "Selects the destination position within attach-slot."),
					menuRequiredArgument(6, "split-option", "split:<slot>=<rule>[&<slot>=<rule>...] token", "Defines target slots and either a clipping plane or split-part bone names."),
				),
			},
			"Loads a model with the current category, version, CRC sub-slot/body-type/skirt state, optional attachment, and optional 3.48 split rules. SceneEdit also counts additem records.",
			"Verify the model, slot, attachment target, and all state established by preceding commands. The official 2.48 compiler accepts total token counts 3, 5, or 6 for the non-split forms.",
			"critical", compileSource, sceneSource, compile3Source, scene3Source, menuSource, menu3Source,
		),
		menuCommand(
			"nofloory", nil, runtimeBoth,
			[]CommandForm{menuForm("nofloory <slot>", reviewedBoth,
				menuRequiredArgument(1, "slot", "TBody.SlotID name", "Selects the slot whose floor-Y collision flag is disabled."),
			)},
			"Disables floor-height collision handling for the selected slot.",
			"Use only for models authored to ignore floor-Y collision; this persists on the slot state.",
			"high", menuSource, menu3Source,
		),
		menuCommand(
			"maskitem", nil, runtimeBoth,
			[]CommandForm{menuForm("maskitem [<slot>]", reviewedBoth,
				menuOptionalArgument(1, "slot", "TBody.SlotID name", "no operation", "Adds a mask relationship from the current category to this slot when present."),
			)},
			"Adds a body-slot mask associated with the current category; the command does nothing when the optional slot is absent.",
			"Keep category immediately before it and verify that hiding the target slot is intended.",
			"critical", menuSource, menu3Source,
		),
		menuCommand(
			"delitem", nil, runtimeBoth,
			[]CommandForm{menuForm("delitem [<slot>]", reviewedBoth,
				menuOptionalArgument(1, "slot", "TBody.SlotID name", "current category", "Selects the slot to delete; omission uses the current category string."),
			)},
			"Deletes an item from the selected slot under the current MPN context.",
			"Confirm both the current category and optional slot. The official compiler validates an explicit slot when present.",
			"critical", compileSource, compile3Source, menuSource, menu3Source,
		),
		menuCommand(
			"node消去", nil, runtimeBoth,
			[]CommandForm{
				menuForm("node消去 <node-name>", reviewedBoth,
					menuRequiredArgument(1, "node-name", "transform name", "Hides this node in the current category slot."),
				),
				menuForm("node消去 <node-name> slot=<slot>", reviewed348,
					menuRequiredArgument(1, "node-name", "transform name", "Hides this node."),
					menuRequiredArgument(2, "slot-override", "slot=<TBody.SlotID> token", "Overrides the current category slot for this operation."),
				),
			},
			"Hides a named model node in the current slot or a 3.48 slot override.",
			"Use an exact node name and do not add slot= when targeting 2.48.",
			"high", menuSource, menu3Source,
		),
		menuCommand(
			"node表示", nil, runtimeBoth,
			[]CommandForm{
				menuForm("node表示 <node-name>", reviewedBoth,
					menuRequiredArgument(1, "node-name", "transform name", "Shows this node in the current category slot."),
				),
				menuForm("node表示 <node-name> slot=<slot>", reviewed348,
					menuRequiredArgument(1, "node-name", "transform name", "Shows this node."),
					menuRequiredArgument(2, "slot-override", "slot=<TBody.SlotID> token", "Overrides the current category slot for this operation."),
				),
			},
			"Shows a named model node in the current slot or a 3.48 slot override.",
			"Use an exact node name and keep hide/show operations ordered intentionally.",
			"high", menuSource, menu3Source,
		),
		menuCommand(
			"パーツnode消去", nil, runtimeBoth,
			[]CommandForm{
				menuForm("パーツnode消去 <parts-slot> <node-name>", reviewedBoth,
					menuRequiredArgument(1, "parts-slot", "TBody.SlotID name", "Selects the parts slot whose node visibility mapping is changed."),
					menuRequiredArgument(2, "node-name", "transform name", "Names the node to hide."),
				),
				menuForm("パーツnode消去 <parts-slot> <node-name> slot=<source-slot>", reviewed348,
					menuRequiredArgument(1, "parts-slot", "TBody.SlotID name", "Selects the parts slot whose node is hidden."),
					menuRequiredArgument(2, "node-name", "transform name", "Names the node to hide."),
					menuRequiredArgument(3, "source-slot-override", "slot=<TBody.SlotID> token", "Overrides the current category used as the visibility source."),
				),
			},
			"Hides a named node through the parts-slot visibility mapping.",
			"Verify both slot roles and the exact model node name; the optional override is reviewed only in 3.48.",
			"high", menuSource, menu3Source,
		),
		menuCommand(
			"パーツnode表示", nil, runtimeBoth,
			[]CommandForm{
				menuForm("パーツnode表示 <parts-slot> <node-name>", reviewedBoth,
					menuRequiredArgument(1, "parts-slot", "TBody.SlotID name", "Selects the parts slot whose node visibility mapping is changed."),
					menuRequiredArgument(2, "node-name", "transform name", "Names the node to show."),
				),
				menuForm("パーツnode表示 <parts-slot> <node-name> slot=<source-slot>", reviewed348,
					menuRequiredArgument(1, "parts-slot", "TBody.SlotID name", "Selects the parts slot whose node is shown."),
					menuRequiredArgument(2, "node-name", "transform name", "Names the node to show."),
					menuRequiredArgument(3, "source-slot-override", "slot=<TBody.SlotID> token", "Overrides the current category used as the visibility source."),
				),
			},
			"Shows a named node through the parts-slot visibility mapping.",
			"Verify both slot roles and preserve ordering relative to matching hide commands.",
			"high", menuSource, menu3Source,
		),
		menuCommand(
			"mask消去", nil, runtime348,
			[]CommandForm{menuForm("mask消去 <slot> <mask-name>", reviewed348,
				menuRequiredArgument(1, "slot", "TBody.SlotID name", "Selects the slot at the current CRC target sub-slot index."),
				menuRequiredArgument(2, "mask-name", "string", "Names the skin mask registered for the selected slot."),
			)},
			"Registers a skin-mask removal for a CRC slot.",
			"Verify crc_target_slotno and the exact mask name; this opcode is not reviewed in 2.48.",
			"critical", menu3Source,
		),
		menuCommand(
			"cutout消去", nil, runtime348,
			[]CommandForm{menuForm("cutout消去 <slot> <cutout-name>", reviewed348,
				menuRequiredArgument(1, "slot", "TBody.SlotID name", "Selects the slot at the current CRC target sub-slot index."),
				menuRequiredArgument(2, "cutout-name", "string", "Names the skin-mask cutout registered for the selected slot."),
			)},
			"Registers a skin-mask cutout removal for a CRC slot.",
			"Verify crc_target_slotno and the exact cutout name; this opcode is not reviewed in 2.48.",
			"critical", menu3Source,
		),
		menuCommand(
			"cutout消去cc", nil, runtimeBoth,
			[]CommandForm{menuForm("cutout消去cc <slot> <cutout-name> [<owner>]", reviewedBoth,
				menuRequiredArgument(1, "slot", "TBody.SlotID name", "Selects the base sub-slot-zero slot for the cutout."),
				menuRequiredArgument(2, "cutout-name", "string", "Names the skin-mask cutout."),
				menuOptionalArgument(3, "owner", "string selector", "maid", "The operation runs only when omitted or equal to maid, ignoring case.", "maid"),
			)},
			"Registers a sub-slot-zero skin-mask cutout when the optional owner selects the maid.",
			"Omit owner or use maid for an active command; any other value intentionally makes this branch a no-op.",
			"critical", menuSource, menu3Source,
		),
		menuCommand(
			"color", nil, runtimeBoth,
			[]CommandForm{menuForm("color <slot> <material-index> <property-name> <r> <g> <b> <a>", reviewedBoth,
				menuRequiredArgument(1, "slot", "TBody.SlotID name", "Selects the target slot."),
				menuRequiredArgument(2, "material-index", "int", "Selects a material on the target slot."),
				menuRequiredArgument(3, "property-name", "shader color property name", "Selects the color property to change."),
				menuRequiredArgument(4, "r", "float in byte-color units", "Red is divided by 255 before assignment."),
				menuRequiredArgument(5, "g", "float in byte-color units", "Green is divided by 255 before assignment."),
				menuRequiredArgument(6, "b", "float in byte-color units", "Blue is divided by 255 before assignment."),
				menuRequiredArgument(7, "a", "float in byte-color units", "Alpha is divided by 255 before assignment."),
			)},
			"Changes a color property on one slot material.",
			"Use the model's actual material index and shader property; ordinary channel values are 0 to 255.",
			"high", menuSource, menu3Source,
		),
		menuCommand(
			"mancolor", nil, runtimeBoth,
			[]CommandForm{menuForm("mancolor <r> <g> <b>", reviewedBoth,
				menuRequiredArgument(1, "r", "float in byte-color units", "Red is divided by 255."),
				menuRequiredArgument(2, "g", "float in byte-color units", "Green is divided by 255."),
				menuRequiredArgument(3, "b", "float in byte-color units", "Blue is divided by 255; alpha is fixed to 1."),
			)},
			"Sets the male body color and immediately refreshes it.",
			"Use ordinary channel values from 0 to 255 and verify all male-body materials after the change.",
			"high", menuSource, menu3Source,
		),
		menuCommand(
			"tex", []string{"テクスチャ変更"}, append(append([]string{}, runtimeBoth...), append(editorBoth, compilerBoth...)...),
			[]CommandForm{menuForm("tex <slot> <material-selector> <property-name> <texture-file> [<parts-color>]", reviewedBoth,
				menuRequiredArgument(1, "slot", "TBody.SlotID name", "Selects the target slot."),
				menuRequiredArgument(2, "material-selector", "int or MPN=int[&MPN=int...] mapping", "Selects one material index directly or chooses an index by the current maid-property MPN."),
				menuRequiredArgument(3, "property-name", "shader texture property name", "Selects the texture property to replace."),
				menuRequiredArgument(4, "texture-file", "texture resource name", "Names the replacement texture."),
				menuOptionalArgument(5, "parts-color", "MaidParts.PARTS_COLOR enum name", "NONE", "Associates the texture with an infinite-color channel and triggers a color refresh."),
			)},
			"Replaces a material texture, optionally selecting the material by MPN and binding an infinite-color channel. SceneEdit also records the optional color channel.",
			"Verify every mapped MPN, material index, property, texture, and parts-color enum. Both reviewed opcodes are exact aliases.",
			"critical", compileSource, sceneSource, compile3Source, scene3Source, menuSource, menu3Source,
		),
		menuCommand(
			"prop", nil, runtimeBoth,
			[]CommandForm{menuForm("prop <mpn> <value>", reviewedBoth,
				menuRequiredArgument(1, "mpn", "MPN enum or maid property name", "Selects the maid property."),
				menuRequiredArgument(2, "value", "int", "Assigns the property's numeric value."),
			)},
			"Sets a maid property's integer value.",
			"Use a property present in the target build and a value valid for that property's own range.",
			"critical", menuSource, menu3Source,
		),
		menuCommand(
			"テクスチャ乗算", nil, runtimeBoth,
			[]CommandForm{menuForm("テクスチャ乗算 [<opaque-argument>...]", reviewedBoth,
				menuOptionalRepeatableArgument(1, "opaque-argument", "string", "The reviewed runtime recognizes this opcode but performs no operation and reads no arguments."),
			)},
			"Performs no operation in the reviewed runtime interpreter.",
			"Preserve existing arguments; use the reviewed six-argument texture-composition opcode for compositing.",
			"low", menuSource, menu3Source,
		),
		menuCommand(
			"テクスチャ合成", nil, runtimeBoth,
			[]CommandForm{menuForm("テクスチャ合成 <slot> <material-index> <property-name> <layer-index> <texture-file> <blend-mode>", reviewedBoth,
				menuRequiredArgument(1, "slot", "TBody.SlotID name", "Selects the target slot."),
				menuRequiredArgument(2, "material-index", "int", "Selects the target material."),
				menuRequiredArgument(3, "property-name", "shader texture property name", "Selects the texture property to composite."),
				menuRequiredArgument(4, "layer-index", "int", "Selects the composition layer."),
				menuRequiredArgument(5, "texture-file", "texture resource name", "Names the layer texture."),
				menuRequiredArgument(6, "blend-mode", "GameUty.SystemMaterial enum name", "Selects the system material used for composition.", "Alpha", "Multiply", "InfinityColor", "TexTo8bitTex"),
			)},
			"Composites a texture layer into a material property, with special additive/sub-property handling for tattoo and mole categories.",
			"Supply exactly six arguments and verify the target material, layer order, texture, and blend mode.",
			"critical", menuSource, menu3Source,
		),
		menuCommand(
			"テクスチャセット合成", nil, runtimeBoth,
			[]CommandForm{menuForm("テクスチャセット合成 <slot> <material-index> <property-name> <layer-index> <texture-file> <blend-mode>", reviewedBoth,
				menuRequiredArgument(1, "slot", "TBody.SlotID name", "Selects the target slot."),
				menuRequiredArgument(2, "material-index", "int", "Selects the target material."),
				menuRequiredArgument(3, "property-name", "shader texture property name", "Selects the texture property to composite."),
				menuRequiredArgument(4, "layer-index", "int", "Selects the composition layer."),
				menuRequiredArgument(5, "texture-file", "texture resource name", "Names the layer texture."),
				menuRequiredArgument(6, "blend-mode", "GameUty.SystemMaterial enum name", "Selects the system material used for composition.", "Alpha", "Multiply", "InfinityColor", "TexTo8bitTex"),
			)},
			"Composites and retains a texture-set layer using the add/no-transform path.",
			"Supply exactly six arguments and preserve layer ordering across related composition commands.",
			"critical", menuSource, menu3Source,
		),
		menuCommand(
			"マテリアル変更", nil, runtimeBoth,
			[]CommandForm{menuForm("マテリアル変更 <slot> <material-index> <material-file>", reviewedBoth,
				menuRequiredArgument(1, "slot", "TBody.SlotID name", "Selects the target slot."),
				menuRequiredArgument(2, "material-index", "int", "Selects the material to replace."),
				menuRequiredArgument(3, "material-file", "material resource name", "Names the replacement material."),
			)},
			"Replaces one material on a loaded slot model.",
			"Verify the index against the target model and ensure the material and all referenced textures and shaders exist.",
			"critical", menuSource, menu3Source,
		),
		menuCommand(
			"shader", nil, runtimeBoth,
			[]CommandForm{menuForm("shader <slot> <material-index> <shader-name>", reviewedBoth,
				menuRequiredArgument(1, "slot", "TBody.SlotID name", "Selects the target slot."),
				menuRequiredArgument(2, "material-index", "int", "Selects the material whose shader changes."),
				menuRequiredArgument(3, "shader-name", "Unity shader name", "Selects the replacement shader."),
			)},
			"Changes one material's shader and marks the menu as having made an explicit shader change.",
			"Use a shader present in the target build and verify all existing material properties remain compatible.",
			"critical", menuSource, menu3Source,
		),
	)

	commands = append(commands,
		// Attachment points, face/body morphs, animation, and 3.48 body state.
		menuCommand(
			"アタッチポイントの設定", nil, runtimeBoth,
			[]CommandForm{
				menuForm("アタッチポイントの設定 <point-name> <x> <y> <z>", reviewedBoth,
					menuRequiredArgument(1, "point-name", "attachment-point name", "Names the attachment point in the current slot."),
					menuRequiredArgument(2, "x", "float", "Sets the local position X component."),
					menuRequiredArgument(3, "y", "float", "Sets the local position Y component."),
					menuRequiredArgument(4, "z", "float", "Sets the local position Z component."),
				),
				menuForm("アタッチポイントの設定 <point-name> <x> <y> <z> <rx> <ry> <rz>", reviewedBoth,
					menuRequiredArgument(1, "point-name", "attachment-point name", "Names the attachment point in the current slot."),
					menuRequiredArgument(2, "x", "float", "Sets the local position X component."),
					menuRequiredArgument(3, "y", "float", "Sets the local position Y component."),
					menuRequiredArgument(4, "z", "float", "Sets the local position Z component."),
					menuRequiredArgument(5, "rx", "float degrees", "Sets the local Euler rotation X component."),
					menuRequiredArgument(6, "ry", "float degrees", "Sets the local Euler rotation Y component."),
					menuRequiredArgument(7, "rz", "float degrees", "Sets the local Euler rotation Z component."),
				),
			},
			"Sets an attachment point's local position and, in the seven-argument form, Euler rotation.",
			"Use the seven-argument form for authored files; the shorter form is accepted but logs a missing-angle error and uses identity rotation.",
			"high", menuSource, menu3Source,
		),
		menuCommand(
			"blendset", nil, runtimeBoth,
			[]CommandForm{menuForm("blendset <set-name> (<morph-name> <weight>)+", reviewedBoth,
				menuRequiredArgument(1, "set-name", "string", "Names or replaces the face morph blend set."),
				menuRequiredRepeatableArgument(2, "morph-name", "morph key", "Names a face morph entry; it repeats in pairs with weight."),
				menuRequiredRepeatableArgument(3, "weight", "float", "Sets the corresponding morph value; it repeats in pairs with morph-name."),
			)},
			"Creates a face blend set and assigns each named morph weight.",
			"Keep morph-name and weight tokens paired and preserve the set name used by consumers.",
			"high", menuSource, menu3Source,
		),
		menuCommand(
			"paramset", nil, runtimeBoth,
			[]CommandForm{menuForm("paramset <set-name> (<threshold> <value>)+", reviewedBoth,
				menuRequiredArgument(1, "set-name", "string", "Names the parameter set stored on the current face slot."),
				menuRequiredRepeatableArgument(2, "threshold", "float", "Stores a float threshold paired with the following value string."),
				menuRequiredRepeatableArgument(3, "value", "string", "Stores the value paired with the preceding threshold."),
			)},
			"Creates or replaces a face parameter set from threshold/value pairs.",
			"Keep threshold and value tokens paired; the runtime derives the form from the raw command text, not from a fixed argument count.",
			"high", menuSource, menu3Source,
		),
		menuCommand(
			"commenttype", nil, runtimeBoth,
			[]CommandForm{menuForm("commenttype <key> <value>", reviewedBoth,
				menuRequiredArgument(1, "key", "string", "Names the parts-status dictionary entry."),
				menuRequiredArgument(2, "value", "string", "Stores the associated comment/type value."),
			)},
			"Writes a key/value entry to the maid parts-status dictionary.",
			"Avoid reusing keys unless replacement is intended; preserve values expected by downstream UI or plugins.",
			"medium", menuSource, menu3Source,
		),
		menuCommand(
			"useredit", nil, runtimeBoth,
			[]CommandForm{menuForm("useredit <label> material <destination-slot> <material-index> <property-name> <type-name> <value>", reviewedBoth,
				menuRequiredArgument(1, "label", "editor label", "Identifies the user-edit entry; the special eyebrow-order label rewrites the property to _ZTest2."),
				menuRequiredArgument(3, "destination-slot", "TBody.SlotID name", "Selects the destination slot for the material property."),
				menuRequiredArgument(4, "material-index", "int", "Selects the destination material."),
				menuRequiredArgument(5, "property-name", "shader property name", "Names the material property, subject to the eyebrow-order special case."),
				menuRequiredArgument(6, "type-name", "Unity material property type", "Selects the parser for the property value."),
				menuRequiredArgument(7, "value", "type-encoded string", "Encodes the value according to type-name."),
			)},
			"Applies a material property through the editor's user-edit path when the literal second token is material.",
			"Keep material at position 2 and use a type/value encoding accepted by TBody.SetMaterialProperty.",
			"critical", menuSource, menu3Source,
		),
		menuCommand(
			"bonemorph", nil, runtimeBoth,
			[]CommandForm{
				menuForm("bonemorph <bone-name> <morph-name> <min-x> <min-y> <min-z> <max-x> <max-y> <max-z>", reviewedBoth,
					menuRequiredArgument(1, "bone-name", "bone name", "Selects the bone whose positional morph is changed."),
					menuRequiredArgument(2, "morph-name", "morph name", "Selects the bone morph entry."),
					menuRequiredArgument(3, "min-x", "float", "Sets the minimum positional X component."),
					menuRequiredArgument(4, "min-y", "float", "Sets the minimum positional Y component."),
					menuRequiredArgument(5, "min-z", "float", "Sets the minimum positional Z component."),
					menuRequiredArgument(6, "max-x", "float", "Sets the maximum positional X component."),
					menuRequiredArgument(7, "max-y", "float", "Sets the maximum positional Y component."),
					menuRequiredArgument(8, "max-z", "float", "Sets the maximum positional Z component."),
				),
				menuForm("bonemorph <transform-kind> <bone-name> <morph-name> <min-x> <min-y> <min-z> <max-x> <max-y> <max-z>", reviewedBoth,
					menuRequiredArgument(1, "transform-kind", "literal enum", "Selects which transform channel is changed.", "pos", "rot", "scl"),
					menuRequiredArgument(2, "bone-name", "bone name", "Selects the bone whose morph is changed."),
					menuRequiredArgument(3, "morph-name", "morph name", "Selects the bone morph entry."),
					menuRequiredArgument(4, "min-x", "float", "Sets the minimum channel X component."),
					menuRequiredArgument(5, "min-y", "float", "Sets the minimum channel Y component."),
					menuRequiredArgument(6, "min-z", "float", "Sets the minimum channel Z component."),
					menuRequiredArgument(7, "max-x", "float", "Sets the maximum channel X component."),
					menuRequiredArgument(8, "max-y", "float", "Sets the maximum channel Y component."),
					menuRequiredArgument(9, "max-z", "float", "Sets the maximum channel Z component."),
				),
			},
			"Changes a bone morph's position, rotation, or scale range. The eight-argument form is positional-only; the nine-argument form selects pos, rot, or scl explicitly.",
			"Keep all six vector components finite and use the form supported by the target build's authored menu.",
			"critical", menuSource, menu3Source,
		),
		menuCommand(
			"length", nil, runtimeBoth,
			[]CommandForm{menuForm("length <slot> <group-name> <bone-search-type> <bone-name> <min-x> <min-y> <min-z> <max-x> <max-y> <max-z>", reviewedBoth,
				menuRequiredArgument(1, "slot", "TBody.SlotID name", "Selects the hair slot whose length data is changed."),
				menuRequiredArgument(2, "group-name", "string", "Names the hair-length group."),
				menuRequiredArgument(3, "bone-search-type", "string", "Selects the game's bone-search mode."),
				menuRequiredArgument(4, "bone-name", "bone name", "Names the bone used by the group."),
				menuRequiredArgument(5, "min-x", "float", "Sets minimum scale X."),
				menuRequiredArgument(6, "min-y", "float", "Sets minimum scale Y."),
				menuRequiredArgument(7, "min-z", "float", "Sets minimum scale Z."),
				menuRequiredArgument(8, "max-x", "float", "Sets maximum scale X."),
				menuRequiredArgument(9, "max-y", "float", "Sets maximum scale Y."),
				menuRequiredArgument(10, "max-z", "float", "Sets maximum scale Z."),
			)},
			"Sets the min/max scale vectors used by a hair-length data group.",
			"Supply exactly ten arguments and keep the slot, group, search mode, and bone name coherent.",
			"critical", menuSource, menu3Source,
		),
		menuCommand(
			"anime", nil, runtimeBoth,
			[]CommandForm{menuForm("anime <slot> <animation-file> [loop]", reviewedBoth,
				menuRequiredArgument(1, "slot", "TBody.SlotID name", "Selects the item slot receiving the animation."),
				menuRequiredArgument(2, "animation-file", "animation resource name", "Names the animation loaded and played."),
				menuOptionalArgument(3, "loop", "literal flag", "false", "When present, loop is true only for the exact literal loop.", "loop"),
			)},
			"Loads and plays an item animation, optionally looping it.",
			"Verify the animation exists for the selected slot and use loop only when repeated playback is intended.",
			"high", menuSource, menu3Source,
		),
		menuCommand(
			"param2", nil, runtimeBoth,
			[]CommandForm{menuForm("param2 <slot> <key> <value>", reviewedBoth,
				menuRequiredArgument(1, "slot", "TBody.SlotID name", "Selects the slot receiving the secondary parameter."),
				menuRequiredArgument(2, "key", "string", "Names the secondary slot parameter."),
				menuRequiredArgument(3, "value", "string", "Stores the secondary parameter value."),
			)},
			"Sets a secondary string parameter on a loaded slot.",
			"Supply exactly three arguments and preserve the key spelling expected by the target slot implementation.",
			"high", menuSource, menu3Source,
		),
		menuCommand(
			"animematerial", nil, runtimeBoth,
			[]CommandForm{menuForm("animematerial <slot> <material-index>", reviewedBoth,
				menuRequiredArgument(1, "slot", "TBody.SlotID name", "Selects the slot whose material is animated."),
				menuRequiredArgument(2, "material-index", "int", "Selects the material added to the material animator."),
			)},
			"Adds one slot material to the material-animation controller.",
			"Verify the material index and ensure the selected slot has a compatible animation controller.",
			"high", menuSource, menu3Source,
		),
		menuCommand(
			"meshmorph", nil, runtime348,
			[]CommandForm{menuForm("meshmorph <tag> <morph-name> def=<percent>", reviewed348,
				menuRequiredArgument(1, "tag", "TMorphSkin.BaseBlendValue.Tag enum name", "Selects one of the concrete base-blend groups listed in the referenced value set.", "パンツ", "靴下"),
				menuRequiredArgument(2, "morph-name", "mesh morph name", "Names the mesh morph entry."),
				menuRequiredArgument(3, "default-token", "def=<int> token", "Provides the default percentage; the runtime multiplies it by 0.01."),
			)},
			"Adds a default mesh base-blend value to the current additem slot.",
			"Use only after additem has established the current slot and keep the def= prefix and integer percentage intact.",
			"critical", menu3Source,
		),
		menuCommand(
			"addbonemorph", nil, runtime348,
			[]CommandForm{menuFormWithNotes("addbonemorph <slot> 裾 (<target-bone> [pos=<vec3>~<vec3>] [rot=<vec3>~<vec3>] [scl=<vec3>~<vec3>])+", reviewed348,
				"The reviewed interpreter requires slot=wear and the literal group shown in the syntax. Each target-bone token starts a new morph record; following pos/rot/scl tokens attach ranges to that record. Vector syntax is the parser's accepted Vector3 text joined by ~.",
				menuRequiredArgument(1, "slot", "TBody.SlotID enum name", "Selects the morph owner; the reviewed path requires wear.", "wear"),
				menuRequiredArgument(2, "group", "literal group name", "Selects the reviewed skirt-hem group.", "裾"),
				menuRequiredRepeatableArgument(3, "target-bone-or-transform-token", "bone name or pos/rot/scl=<vec3>~<vec3> token", "Defines one target bone and its optional position, rotation, and scale ranges."),
			)},
			"Adds custom bone morph records for the wear skirt hem.",
			"Keep each target bone followed by only valid pos, rot, or scl tokens and preserve both required discriminator literals.",
			"critical", menu3Source,
		),
		menuCommand(
			"乳首", nil, runtime348,
			[]CommandForm{menuForm("乳首 <state>", reviewed348,
				menuRequiredArgument(1, "state", "TBodySkin.CHIKUBI_STATE enum name", "Sets the nipple state on the current additem slot and CRC sub-slot.", "None", "固定凸", "基本凹"),
			)},
			"Sets the reviewed CRC body's nipple state.",
			"Use an enum value valid for the target body and place it after the additem that establishes the intended current slot.",
			"high", menu3Source,
		),
		menuCommand(
			"ちんこ", nil, runtime348,
			[]CommandForm{menuForm("ちんこ <state>", reviewed348,
				menuRequiredArgument(1, "state", "TBodySkin.CHINKO_STATE enum name", "Sets the penis state on the current additem slot and CRC sub-slot.", "None", "しまう"),
			)},
			"Sets the reviewed CRC body's penis state.",
			"Use an enum value valid for the target body and preserve current-slot ordering.",
			"high", menu3Source,
		),
		menuCommand(
			"toelock", nil, runtimeBoth,
			[]CommandForm{menuForm("toelock <slot>", reviewedBoth,
				menuRequiredArgument(1, "slot", "TBody.SlotID enum name", "Adds the slot to the toe-lock controller; a following additem consumes the pending lock in 3.48."),
			)},
			"Locks toe behavior for the selected slot while subsequent item state is applied.",
			"Place it immediately before the intended additem and verify the slot supports toe locking.",
			"high", menuSource, menu3Source,
		),
	)

	return linkCom3d2MenuArgumentValueSets(commands)
}

func menuCommand(name string, aliases, contexts []string, forms []CommandForm, gameEffect, editGuidance, risk string, evidence ...Source) Command {
	return Command{
		Name:         name,
		Aliases:      aliases,
		Contexts:     contexts,
		Forms:        forms,
		GameEffect:   gameEffect,
		EditGuidance: editGuidance,
		Risk:         risk,
		Evidence:     evidence,
	}
}

func menuForm(syntax string, reviewedIn []string, arguments ...CommandArgument) CommandForm {
	return CommandForm{Syntax: syntax, ReviewedIn: reviewedIn, Arguments: arguments}
}

func menuFormWithNotes(syntax string, reviewedIn []string, notes string, arguments ...CommandArgument) CommandForm {
	return CommandForm{Syntax: syntax, ReviewedIn: reviewedIn, Arguments: arguments, Notes: notes}
}

func menuRequiredArgument(position int, name, valueType, description string, allowedValues ...string) CommandArgument {
	return CommandArgument{Position: position, Name: name, Type: valueType, Required: true, AllowedValues: allowedValues, Description: description}
}

func menuOptionalArgument(position int, name, valueType, defaultValue, description string, allowedValues ...string) CommandArgument {
	return CommandArgument{Position: position, Name: name, Type: valueType, Default: defaultValue, AllowedValues: allowedValues, Description: description}
}

func menuRequiredRepeatableArgument(position int, name, valueType, description string) CommandArgument {
	return CommandArgument{Position: position, Name: name, Type: valueType, Required: true, Repeatable: true, Description: description}
}

func menuOptionalRepeatableArgument(position int, name, valueType, description string) CommandArgument {
	return CommandArgument{Position: position, Name: name, Type: valueType, Repeatable: true, Description: description}
}

func linkCom3d2MenuArgumentValueSets(commands []Command) []Command {
	for commandIndex := range commands {
		for formIndex := range commands[commandIndex].Forms {
			form := &commands[commandIndex].Forms[formIndex]
			for argumentIndex := range commands[commandIndex].Forms[formIndex].Arguments {
				argument := &form.Arguments[argumentIndex]
				switch {
				case strings.Contains(argument.Type, "TBody.SlotID") || strings.Contains(argument.Type, "SlotID"):
					argument.ValueSetRefs = menuBuildValueSetRefs(form.ReviewedIn, com3d2SlotID248ValueSetID, com3d2SlotID348ValueSetID)
				case strings.Contains(argument.Type, "TBodySkin.CHIKUBI_STATE"):
					argument.ValueSetRefs = []string{com3d2ChikubiStateValueSetID}
				case strings.Contains(argument.Type, "TBodySkin.CHINKO_STATE"):
					argument.ValueSetRefs = []string{com3d2ChinkoStateValueSetID}
				case strings.Contains(argument.Type, "MaidParts.PARTS_COLOR"):
					argument.ValueSetRefs = []string{com3d2PartsColorValueSetID}
				case strings.Contains(argument.Type, "GameUty.SystemMaterial"):
					argument.ValueSetRefs = []string{com3d2SystemMaterialValueSetID}
				case strings.Contains(argument.Type, "TBodySkin.TargetBodyType"):
					argument.ValueSetRefs = []string{com3d2TargetBodyTypeValueSetID}
				case strings.Contains(argument.Type, "TMorphSkin.BaseBlendValue.Tag"):
					argument.ValueSetRefs = []string{com3d2MeshMorphTagValueSetID}
				case strings.Contains(argument.Type, "maid property name") || strings.Contains(argument.Type, "maidprop[") || strings.Contains(argument.Type, "setprop[") || strings.Contains(argument.Type, "getprop["):
					argument.ValueSetRefs = menuBuildValueSetRefs(form.ReviewedIn, com3d2MPN248ValueSetID, com3d2MPN348ValueSetID)
				case strings.Contains(argument.Type, "MPN"):
					argument.ValueSetRefs = menuBuildValueSetRefs(form.ReviewedIn, com3d2MPN248ValueSetID, com3d2MPN348ValueSetID)
				}
			}
		}
	}
	return commands
}

func menuBuildValueSetRefs(reviewedIn []string, legacyID, currentID string) []string {
	refs := make([]string, 0, 2)
	for _, build := range reviewedIn {
		switch build {
		case "COM3D2 2.48.0":
			refs = append(refs, legacyID)
		case "COM3D2_5 3.48.0":
			refs = append(refs, currentID)
		}
	}
	return refs
}
