package knowledgev1

// kcesPayloadProfiles 构建共享 KCESPayloadEnvelope 及各原生后缀载荷语义的审核指南
// kcesPayloadProfiles builds reviewed guides for the shared KCESPayloadEnvelope and native-suffix payload semantics
func kcesPayloadProfiles() map[string]Guide {
	payloadSource := implementationSource("KCES 1.34.4", "serialization/KCES/payload.go", "KCESPayloadEnvelope and DecodeKCESPayload/EncodeKCESPayload", 20, 560, "The dispatcher binds every supported extension to a known payload kind and storage variant, fully decodes that typed root, and rejects unknown kinds or trailing MessagePack data.")
	dynamicMgrSource := source("KCES 1.34.4", "KCES 1.34.4/Assembly-CSharp/DynamicBoneMgr.cs", "DynamicBoneMgr.LoadDynamicYureBoneSetting/LoadMagica2DynamicYureBoneSetting", 212, 485, "DynamicBoneMgr selects .dbconf/.dbcol, .db2conf, .dsbconf/.dsb2conf, .dslconf/.dsl2conf/.dslcol, and default fallback names for the corresponding physics components.")
	dynamicSource := source("KCES 1.34.4", "KCES 1.34.4/Assembly-CSharp/DynamicYureBone.cs", "DynamicYureBone.Save/Load/SaveCollider/LoadCollider", 281, 400, "DynamicYureBone serializes DynamicBoneStatus and DynamicBoneColliderData using MessagePack Lz4BlockArray and reads an Int32 compressed-byte length before deserializing.")
	sleeveSource := source("KCES 1.34.4", "KCES 1.34.4/Assembly-CSharp/DynamicSleeveBone.cs", "DynamicSleeveBone.SaveParams/LoadParams/LoadCollider", 1080, 1180, "DynamicSleeveBone loads ClothParams from .dslconf, optional MagicaCloth2 JSON from .dsl2conf, and collider data from .dslcol.")
	skirtSource := source("KCES 1.34.4", "KCES 1.34.4/Assembly-CSharp/DynamicKCESSkirtBone.cs", "DynamicKCESSkirtBone.SaveParams/LoadParams/LoadMagica2Params", 120, 150, "DynamicKCESSkirtBone uses ClothParams for .dsbconf and a JSON string for .dsb2conf.")
	ikSource := source("KCES 1.34.4", "KCES 1.34.4/Assembly-CSharp/kt/ik/IKColliderSaveLoader.cs", "IKColliderSaveLoader.Save/Load", 66, 145, "IKColliderSaveLoader reads a length-prefixed Lz4BlockArray IKColliderDataPackage and creates collider objects for each effector group.")
	limbSource := source("KCES 1.34.4", "KCES 1.34.4/Assembly-CSharp/LimbColliderMgr.cs", "LimbColliderMgr.Save/Load", 108, 140, "LimbColliderMgr reads a length-prefixed Lz4BlockArray LimbColliderPackage and applies each target limb collider status to the generated limb collider.")
	colliderSource := implementationSource("KCES 1.34.4", "serialization/KCES/collider_payload.go", "ColliderPackage/ColliderRef and collider status unions", 17, 850, "The codec models the four game-defined plane, capsule, sphere, and maid-property collider tags and rejects every other union tag.")
	clothSource := implementationSource("KCES 1.34.4", "serialization/KCES/cloth_params.go", "ClothParams", 107, 230, "ClothParams mirrors MagicaCloth's indexed keys 0..82, including sparse holes at keys 4, 5, and 56, Bezier parameters, constraints, and mode enums.")

	commonFields := func(ext, expectedKind, expectedStorage string, src Source, rootField string, rootTitle, rootDescription, rootUsage, rootRole, rootGuidance, rootRisk string) []Field {
		field := fieldFrom(src, payloadSource)
		serializationField := serializationFieldFrom(payloadSource)
		fields := []Field{
			field("/format", "Payload envelope format", "The envelope family marker for native KCES MessagePack or an ExportCM sidecar.", "The dispatcher uses kces-msgpack-lz4 for native resources and kces-exportcm-sidecar for JSON sidecars.", "wire_variant", "Use the format matching storageVariant; do not label a native payload as an ExportCM sidecar.", "critical"),
			field("/extension", "Payload extension", "The extension descriptor used to select the expected payload kind and wire rules.", "KCESPayloadEnvelope dispatches decoding and encoding from the complete extension, including the compound .ikcol.bytes suffix.", "format_marker", "Keep the exact extension "+ext+".", "critical"),
			field("/storageVariant", "Storage variant", "The exact wire representation selected for this extension.", "The dispatcher distinguishes int32-length-lz4-messagepack from ExportCM Unity JSON and ExportCM .NET-string JSON variants.", "wire_variant", "Use "+expectedStorage+" for the primary native profile and select an explicitly supported sidecar variant only when the source file came from ExportCM.", "critical"),
			field("/kind", "Payload kind discriminator", "The union discriminator for the typed root object.", "The decoder selects the corresponding MessagePack or JSON model from this value and rejects extension/kind mismatches.", "union_discriminator", "Use "+expectedKind+" for the native "+ext+" contract; do not populate a different typed root.", "critical"),
			field("/"+rootField, rootTitle, rootDescription, rootUsage, rootRole, rootGuidance, rootRisk),
		}
		if rootField != "json" {
			fields = append(fields, serializationField("/json", "Semantic JSON payload", "The normalized semantic JSON value selected only by a JSON payload kind.", "The encoder regenerates the MessagePack string or ExportCM sidecar directly from this value.", "opaque_domain_data", "Leave this field absent for non-JSON kinds and edit only members documented by the selected Unity JSON consumer.", "high"))
		}
		for _, unionField := range []string{"dynamicBoneStatus", "colliderPackage", "clothParams", "ikColliderPackage", "limbColliderPackage"} {
			if unionField == rootField {
				continue
			}
			fields = append(fields, serializationField("/"+unionField, "Inactive union field "+unionField, "A typed union alternative not selected by the "+ext+" descriptor.", "The payload dispatcher rejects an extension/kind combination that does not match the descriptor.", "union_alternative", "Omit this field completely unless a supported kind explicitly selects it.", "critical"))
		}
		_ = src
		return fields
	}

	dynamicFields := func() []FieldPattern {
		return []FieldPattern{
			pattern("/dynamicBoneStatus/{version,damping,elasticity,stiffness,inert,radius}", "DynamicBone scalar status", "The indexed DynamicBoneStatus version and base damping, elasticity, stiffness, inertia, and radius values.", "DynamicYureBone applies these values to its DynamicBone solver before simulation.", "runtime_physics", "Edit a base value together with its optional keyframe curve and test the resulting motion at the target scale.", dynamicSource),
			pattern("/dynamicBoneStatus/{endLength,endOffset,gravity,force,freezeAxis}", "DynamicBone terminal and force settings", "Virtual-end geometry, gravity, external force, and freeze-axis values.", "DynamicBone uses these values during particle integration and terminal-particle creation.", "runtime_physics", "Keep EndLength/EndOffset mutually coherent, use finite vectors, and use FreezeAxis values supported by the target build.", dynamicSource),
			pattern("/dynamicBoneStatus/*KeyFrames/*/{time,value,inTangent,outTangent}", "DynamicBone keyframe", "A time/value/tangent record for one distributed DynamicBone parameter.", "The solver evaluates these curves along the particle chain.", "runtime_curve", "Keep keyframe times ordered and edit tangents conservatively to avoid unstable overshoot.", dynamicSource),
		}
	}

	colliderFields := func() []FieldPattern {
		return []FieldPattern{
			pattern("/colliderPackage/{version,colliders,limbEnableList}", "Collider package root", "The indexed collider-package version, collider references, and optional limb enable list.", "DynamicYureBone applies collider statuses and limb toggles when loading .dbcol or a compatible sidecar.", "runtime_collision", "Keep the package version and list shapes coherent; preserve list order and nil-versus-empty state.", colliderSource),
			pattern("/colliderPackage/colliders/*/{type,collider}", "Collider union entry", "A type tag paired with one of the four collider status structures defined by the game.", "The loader creates a concrete collider component from the tag and status object.", "runtime_collision", "Change type and concrete payload together; unsupported tags must be rejected rather than retained as raw data.", colliderSource),
			pattern("/colliderPackage/colliders/*/collider/{version,parentName,selfName,localPosition,localRotation,localScale,center,bound}", "Collider transform and bounds", "Common collider status fields restored on the runtime collider object.", "The dynamic-bone solver resolves parent/self names and applies local transforms, center, and inside/outside bound mode.", "runtime_collision", "Use existing transform names, finite vectors/quaternions, and a supported bound value.", colliderSource),
			pattern("/colliderPackage/colliders/*/collider/{direction,isDirectionInverse,startRadius,endRadius,height,radius}", "Collider shape parameters", "Axis, reversal, capsule dimensions, and sphere radius for concrete collider types.", "DynamicYureBone uses these fields to construct plane, capsule, sphere, or maid-property geometry.", "runtime_geometry", "Only edit fields present for the selected type; keep dimensions non-negative and aligned with model scale.", colliderSource),
			pattern("/colliderPackage/colliders/*/collider/{centerMpnList,centerRateMax,startRadiusMpnList,maxStartRadius,endRadiusMpnList,maxEndRadius,centerMpnNameList,startRadiusMpnNameList,endRadiusMpnNameList}", "Maid-property collider scaling", "Body-property lists and maxima used by maid-property colliders to scale center and radii.", "The game recomputes these dimensions from maid MPN values when the body changes.", "runtime_body_dependent", "Keep enum lists and name lists paired and preserve values required by the target body type.", colliderSource),
			pattern("/colliderPackage/limbEnableList/*/{version,limbType,isEnable}", "Limb collider enable state", "A limb type and enabled flag carried alongside dynamic-bone collider records.", "DynamicYureBone toggles generated limb colliders from this list.", "runtime_collision", "Use limb enum values present in the target build and preserve list ordering.", colliderSource),
		}
	}

	clothFields := func() []FieldPattern {
		return []FieldPattern{
			pattern("/clothParams/{radius,mass,gravity,drag,maxVelocity,worldMoveInfluence,worldRotationInfluence,clampPositionLength,clampRotationAngle,structDistanceStiffness,bendDistanceStiffness,nearDistanceLength,nearDistanceStiffness,restoreRotation,triangleBend,volumeStretchStiffness,volumeShearStiffness,penetrationConnectDistance,penetrationDistance,penetrationRadius,springDirectionAtten,springDistanceAtten}", "Cloth Bezier parameter", "A BezierParam with start/end values and optional curve value switches.", "MagicaCloth evaluates these parameters along cloth particles when the corresponding constraint is enabled.", "runtime_cloth_parameter", "Keep use flags consistent with the supplied values and preserve the target cloth's scale and units.", clothSource),
			pattern("/clothParams/{useGravity,useDrag,useMaxVelocity,useDistanceDisable,useResetTeleport,useClampDistanceRatio,useClampPositionLength,useClampRotation,useBendDistance,useNearDistance,useRestoreRotation,useSpring,useTriangleBend,useVolume,useCollision,usePenetration,useLineAvarageRotation,useFixedNonRotation}", "Cloth constraint switch", "Boolean switches enabling individual MagicaCloth forces and constraints.", "DynamicSleeveBone and DynamicKCESSkirtBone pass these switches to the cloth solver.", "runtime_cloth_constraint", "Edit a switch together with its parameter block; preserve the game's Avarage spelling in useLineAvarageRotation.", clothSource),
			pattern("/clothParams/{massInfluence,windInfluence,windRandomScale,disableDistance,disableFadeDistance,teleportDistance,teleportRotation,clampDistanceMinRatio,clampDistanceMaxRatio,clampDistanceVelocityInfluence,clampPositionRatioX,clampPositionRatioY,clampPositionRatioZ,clampPositionVelocityInfluence,clampRotationVelocityInfluence,restoreDistanceVelocityInfluence,nearDistanceMaxDepth,restoreRotationVelocityInfluence,springPower,springRadius,springScaleX,springScaleY,springScaleZ,springIntensity,adjustRotationPower,maxVolumeLength,friction,penetrationMaxDepth,maxMoveSpeed,maxRotationSpeed,resetStabilizationTime,clampRotationVelocityLimit}", "Cloth scalar constraint value", "A numeric MagicaCloth force, distance, velocity, friction, or stabilization parameter.", "The cloth solver consumes these values when the related constraint or force is active.", "runtime_cloth_parameter", "Keep finite values in the target game's expected units and test both static and animated poses.", clothSource),
			pattern("/clothParams/{adjustMode,penetrationMode,penetrationAxis,teleportMode,bendDistanceMaxCount,nearDistanceMaxCount}", "Cloth mode or count", "An enum or bounded iteration count selecting cloth adjustment, penetration, teleport, or neighbor-distance behavior.", "MagicaCloth branches on these values while updating particles and collision constraints.", "runtime_enum", "Use enum values from the target KCES build and keep counts non-negative.", clothSource),
		}
	}

	ikFields := func() []FieldPattern {
		return []FieldPattern{
			pattern("/ikColliderPackage/{version,groups}", "IK collider package root", "The indexed package version and effector-group list.", "IKColliderSaveLoader iterates groups and creates collider objects for each full-body IK effector.", "runtime_ik_collision", "Preserve group order and use effector enum values from the target FullBodyIK build.", ikSource),
			pattern("/ikColliderPackage/groups/*/{version,target,colliders}", "IK effector collider group", "An effector target and its ordered collider references.", "The loader names and attaches colliders to the matching IK effector.", "runtime_ik_collision", "Keep target values and collider lists aligned with the target rig; edit union types with their payloads.", ikSource),
			pattern("/ikColliderPackage/groups/*/colliders/*/{type,collider}", "IK collider union entry", "A typed collider reference using one of the four game-defined union tags.", "IKColliderSaveLoader creates the corresponding native collider component from the status.", "runtime_collision", "Preserve type/payload agreement and reject unsupported union tags.", ikSource),
		}
	}

	limbFields := func() []FieldPattern {
		return []FieldPattern{
			pattern("/limbColliderPackage/{version,items}", "Limb collider package root", "The indexed package version and limb-item list.", "LimbColliderMgr reads the list and applies each status to its generated limb collider.", "runtime_limb_collision", "Preserve item order and use limb targets present in the target build.", limbSource),
			pattern("/limbColliderPackage/items/*/{version,target,collider}", "Limb collider item", "A limb enum target paired with the concrete NativeMaidPropColliderStatus structure used by LimbColliderMgr.", "LimbColliderMgr looks up the target limb and calls SetStatus with the collider data.", "runtime_limb_collision", "Keep target and collider geometry matched and reject any incompatible collider representation.", limbSource),
		}
	}

	makeProfile := func(id, ext, title, summary, verificationNotes, expectedKind, storage, rootField, rootTitle, rootDescription, rootUsage, rootRole, rootGuidance, rootRisk string, sources []Source, patterns []FieldPattern) Guide {
		g := guide(title, summary, FormatVerificationSerializationVerified, verificationNotes, sources, commonFields(ext, expectedKind, storage, sources[0], rootField, rootTitle, rootDescription, rootUsage, rootRole, rootGuidance, rootRisk))
		g.FieldPatterns = patterns
		g.Rules = []Rule{{ID: "payload-discriminator-coherence", AppliesTo: []string{"/extension", "/storageVariant", "/kind"}, Severity: "error", Summary: "The envelope discriminator must match the native wire variant.", Details: "The same extension can be used by different storage variants in the exporter ecosystem. Keep extension, format, storageVariant, and kind as one coherent tuple; the encoder derives fixed length framing from that tuple.", Evidence: []Source{payloadSource}}}
		g.Invariants = []string{"extension is " + ext + ".", "The native variant uses " + storage + ".", "Only the union field selected by kind is authoritative."}
		_ = id
		return g
	}

	dbconf := makeProfile("kces.dbconf", ".dbconf", "KCES .dbconf DynamicBone guide", "A DynamicBoneStatus configuration for DynamicYureBone, with an ExportCM Unity-JSON sidecar variant also accepted by the shared envelope.", "DynamicBoneMgr selects .dbconf for legacy dynamic-yure settings; DynamicYureBone reads the native status through a length-prefixed LZ4 MessagePack payload. ExportCM may emit a JSON sidecar with the same extension.", "dynamic-bone-status", "int32-length-lz4-messagepack", "dynamicBoneStatus", "DynamicBone status", "The typed DynamicBoneStatus indexed object containing version, scalar physics values, curves, terminal geometry, forces, and freeze axis.", "DynamicYureBone applies this object to the legacy DynamicBone solver.", "runtime_physics", "Edit the typed fields confirmed by the DynamicBoneStatus profile; the current fixed indexed width and keys are validated automatically.", "critical", []Source{dynamicMgrSource, dynamicSource, payloadSource}, dynamicFields())
	dbconf.FieldPatterns = append(dbconf.FieldPatterns, pattern("/json/*", "ExportCM DynamicBone JSON member", "A member of the Unity JSON sidecar accepted for .dbconf by ExportCM.", "ExportCM passes this JSON to the Unity dynamic-bone configuration path instead of the native MessagePack reader.", "runtime_json_sidecar", "Edit only with the matching ExportCM source; the encoder regenerates text from this semantic JSON value.", dynamicMgrSource))
	dbconf.Rules = append(dbconf.Rules, Rule{ID: "dbconf-storage-choice", AppliesTo: []string{"/storageVariant", "/dynamicBoneStatus", "/json"}, Severity: "error", Summary: "Native and ExportCM .dbconf payloads are different wires.", Details: "The native form is int32-length-LZ4 MessagePack DynamicBoneStatus; the ExportCM form is direct Unity JSON. Select exactly one representation and do not mix fields from both.", Evidence: []Source{payloadSource, dynamicMgrSource}})

	dbcol := makeProfile("kces.dbcol", ".dbcol", "KCES .dbcol collider guide", "A ColliderPackage for DynamicYureBone's dynamic-bone and limb collider state, with an ExportCM Unity-JSON sidecar variant.", "DynamicBoneMgr pairs .dbcol with .dbconf and DynamicYureBone applies the typed collider package to generated collider components.", "collider-package", "int32-length-lz4-messagepack", "colliderPackage", "DynamicBone collider package", "The typed ColliderPackage containing collider union entries and optional limb-enable states.", "DynamicYureBone reconstructs collider objects, transforms, geometry, and limb toggles from this package.", "runtime_collision", "Edit collider type and concrete status together; verify every parent bone and body-dependent MPN list.", "critical", []Source{dynamicMgrSource, dynamicSource, colliderSource, payloadSource}, colliderFields())
	dbcol.FieldPatterns = append(dbcol.FieldPatterns, pattern("/json/*", "ExportCM collider JSON member", "A member of the Unity JSON sidecar accepted for .dbcol.", "ExportCM writes collider JSON instead of the native MessagePack package.", "runtime_json_sidecar", "Edit only with the matching ExportCM collider schema.", dynamicMgrSource))
	dbcol.Rules = append(dbcol.Rules, Rule{ID: "collider-union-coherence", AppliesTo: []string{"/colliderPackage/colliders"}, Severity: "error", Summary: "Collider type tags and concrete objects must agree.", Details: "The decoder selects plane, capsule, sphere, or maid-property status from each type tag and rejects every unsupported tag.", Evidence: []Source{colliderSource}})

	db2conf := makeProfile("kces.db2conf", ".db2conf", "KCES .db2conf MagicaCloth2 JSON guide", "A length-prefixed LZ4 MessagePack string containing the Unity JSON document used by the newer DynamicYureBone MagicaCloth2 path.", "DynamicBoneMgr selects .db2conf for MagicaCloth2 dynamic-yure settings; the payload itself is a string and its domain JSON is Unity/version specific.", "msgpack-json-string", "int32-length-lz4-messagepack", "json", "MagicaCloth2 JSON view", "The normalized JSON value decoded from the MessagePack string payload.", "DynamicYureBone passes the string to the MagicaCloth2 configuration path.", "runtime_json_configuration", "Edit only fields confirmed by the target MagicaCloth2 version and preserve unknown JSON members.", "critical", []Source{dynamicMgrSource, dynamicSource, payloadSource}, []FieldPattern{pattern("/json/*", "MagicaCloth2 configuration member", "A member of the Unity JSON document stored as a MessagePack string.", "The MagicaCloth2 runtime consumes this member according to its own serialized data schema.", "runtime_json_configuration", "Use a source sample from the same KCES build; do not infer types from names alone.", dynamicSource)})

	dsbconf := makeProfile("kces.dsbconf", ".dsbconf", "KCES .dsbconf skirt ClothParams guide", "A ClothParams object for DynamicKCESSkirtBone's legacy MagicaCloth skirt simulation.", "DynamicBoneMgr selects .dsbconf for legacy skirt physics and DynamicKCESSkirtBone deserializes ClothParams from the length-prefixed LZ4 MessagePack payload.", "cloth-params", "int32-length-lz4-messagepack", "clothParams", "Skirt ClothParams", "The typed ClothParams indexed object containing Bezier parameters, constraints, forces, and mode enums.", "DynamicKCESSkirtBone applies this object to its MagicaCloth parameters.", "runtime_cloth_configuration", "Edit switches and their parameter blocks together; sparse keys 4, 5, and 56 must remain nil and unsupported widths are rejected.", "critical", []Source{dynamicMgrSource, skirtSource, clothSource, payloadSource}, clothFields())
	dsb2conf := makeProfile("kces.dsb2conf", ".dsb2conf", "KCES .dsb2conf skirt JSON guide", "A length-prefixed LZ4 MessagePack string containing the newer MagicaCloth2 skirt configuration JSON.", "DynamicBoneMgr selects .dsb2conf for MagicaCloth2 skirts and DynamicKCESSkirtBone passes the decoded string to the Unity JSON configuration path.", "msgpack-json-string", "int32-length-lz4-messagepack", "json", "MagicaCloth2 skirt JSON view", "The normalized JSON document carried inside the MessagePack string.", "DynamicKCESSkirtBone consumes this JSON for its MagicaCloth2 setup.", "runtime_json_configuration", "Edit only fields documented by the matching MagicaCloth2 version and preserve unknown members.", "critical", []Source{dynamicMgrSource, skirtSource, payloadSource}, []FieldPattern{pattern("/json/*", "MagicaCloth2 skirt member", "A member of the JSON configuration string.", "The MagicaCloth2 skirt runtime interprets it while creating the cloth solver.", "runtime_json_configuration", "Use a same-build sample and preserve the original JSON shape.", skirtSource)})

	dslconf := makeProfile("kces.dslconf", ".dslconf", "KCES .dslconf sleeve ClothParams guide", "A ClothParams object for DynamicSleeveBone's legacy MagicaCloth sleeve simulation.", "DynamicBoneMgr selects .dslconf for sleeve physics and DynamicSleeveBone applies the typed ClothParams object.", "cloth-params", "int32-length-lz4-messagepack", "clothParams", "Sleeve ClothParams", "The typed ClothParams indexed object used by the legacy sleeve cloth solver.", "DynamicSleeveBone applies these forces, constraints, and collision settings to sleeve cloth.", "runtime_cloth_configuration", "Edit switches and Bezier parameters as coherent groups; sparse keys 4, 5, and 56 must remain nil and unsupported widths are rejected.", "critical", []Source{dynamicMgrSource, sleeveSource, clothSource, payloadSource}, clothFields())
	dsl2conf := makeProfile("kces.dsl2conf", ".dsl2conf", "KCES .dsl2conf sleeve JSON guide", "A length-prefixed LZ4 MessagePack string containing the newer MagicaCloth2 sleeve configuration JSON.", "DynamicBoneMgr selects .dsl2conf for MagicaCloth2 sleeve parameters and DynamicSleeveBone forwards the string to its Unity JSON configuration path.", "msgpack-json-string", "int32-length-lz4-messagepack", "json", "MagicaCloth2 sleeve JSON view", "The normalized JSON document carried inside the MessagePack string.", "DynamicSleeveBone consumes this JSON for its MagicaCloth2 setup.", "runtime_json_configuration", "Edit only fields documented by the matching MagicaCloth2 version and preserve unknown members.", "critical", []Source{dynamicMgrSource, sleeveSource, payloadSource}, []FieldPattern{pattern("/json/*", "MagicaCloth2 sleeve member", "A member of the JSON configuration string.", "The MagicaCloth2 sleeve runtime interprets it while creating the cloth solver.", "runtime_json_configuration", "Use a same-build sample and preserve the original JSON shape.", sleeveSource)})

	dslcol := makeProfile("kces.dslcol", ".dslcol", "KCES .dslcol sleeve collider guide", "A ColliderPackage for DynamicSleeveBone's cloth colliders, with a BinaryWriter-string Unity JSON sidecar emitted by ExportCM.", "DynamicBoneMgr pairs .dslcol with .dslconf or .dsl2conf. Native KCES uses the common collider package; ExportCM writes the JSON sidecar as a .NET BinaryWriter string.", "collider-package", "int32-length-lz4-messagepack", "colliderPackage", "Sleeve collider package", "The typed collider package applied to sleeve cloth and its optional limb colliders.", "DynamicSleeveBone reconstructs native or MagicaCloth2 collider components from this data.", "runtime_collision", "Edit concrete collider status and body-dependent values together; select the .NET-string sidecar only for ExportCM output.", "critical", []Source{dynamicMgrSource, sleeveSource, colliderSource, payloadSource}, colliderFields())
	dslcol.FieldPatterns = append(dslcol.FieldPatterns, pattern("/json/*", "ExportCM sleeve collider JSON member", "A member of the Unity JSON sidecar stored inside a BinaryWriter string.", "DynamicSleeveBone's ExportCM path consumes this JSON rather than the native MessagePack package.", "runtime_json_sidecar", "Edit only with the matching ExportCM serializer and preserve the string framing.", sleeveSource))
	dslcol.Rules = append(dslcol.Rules, Rule{ID: "dslcol-sidecar-framing", AppliesTo: []string{"/storageVariant", "/json"}, Severity: "error", Summary: "The ExportCM sleeve collider sidecar has .NET string framing.", Details: "Unlike dbcol, the ExportCM dslcol variant wraps UTF-8 Unity JSON in a BinaryWriter string. The encoder derives this framing from storageVariant.", Evidence: []Source{payloadSource, sleeveSource}})

	ikcol := makeProfile("kces.ikcol", ".ikcol", "KCES .ikcol IK collider guide", "An IKColliderPackage used by full-body IK to restore collider groups for each IK effector.", "IKColliderSaveLoader reads .ikcol as a length-prefixed LZ4 MessagePack package and creates native collider components for each effector group.", "ik-collider-package", "int32-length-lz4-messagepack", "ikColliderPackage", "IK collider package", "The typed IKColliderPackage containing effector targets and collider references.", "IKColliderSaveLoader uses these groups to populate full-body IK effector collider lists.", "runtime_ik_collision", "Keep effector targets, collider union tags, and collider geometry aligned with the target rig.", "critical", []Source{ikSource, colliderSource, payloadSource}, ikFields())
	ikcolBytes := makeProfile("kces.ikcol.bytes", ".ikcol.bytes", "KCES .ikcol.bytes IK collider guide", "The compound-extension Unity resource form of .ikcol. Its wire payload is identical to the standalone IK collider file.", "IKColliderSaveLoader's default resource name is ik_collider.ikcol.bytes; the complete compound extension must be preserved when dispatching this payload.", "ik-collider-package", "int32-length-lz4-messagepack", "ikColliderPackage", "IK collider package", "The same typed IKColliderPackage used by .ikcol.", "IKColliderSaveLoader loads the package from the system resource and creates effector collider objects.", "runtime_ik_collision", "Keep the complete .ikcol.bytes extension and edit the shared IK package rules.", "critical", []Source{ikSource, colliderSource, payloadSource}, ikFields())

	limbcol := makeProfile("kces.limbcol", ".limbcol", "KCES .limbcol limb collider guide", "A LimbColliderPackage used by LimbColliderMgr to restore generated arm and leg collider statuses.", "LimbColliderMgr loads limbconf.limbcol as a length-prefixed LZ4 MessagePack package and applies each target status to the corresponding limb collider.", "limb-collider-package", "int32-length-lz4-messagepack", "limbColliderPackage", "Limb collider package", "The typed package of limb targets and collider statuses.", "LimbColliderMgr looks up each limb enum and calls SetStatus on its generated collider.", "runtime_limb_collision", "Keep target enum values, collider union tags, and geometry coherent with the target body.", "critical", []Source{limbSource, colliderSource, payloadSource}, limbFields())

	return map[string]Guide{
		"kces.dbconf":      dbconf,
		"kces.dbcol":       dbcol,
		"kces.db2conf":     db2conf,
		"kces.dsbconf":     dsbconf,
		"kces.dsb2conf":    dsb2conf,
		"kces.dslconf":     dslconf,
		"kces.dsl2conf":    dsl2conf,
		"kces.dslcol":      dslcol,
		"kces.ikcol":       ikcol,
		"kces.ikcol.bytes": ikcolBytes,
		"kces.limbcol":     limbcol,
	}
}
