name: Auto Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # 支持手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version: '1.26.5'
          cache: true

      - name: Build Binaries
        env:
          CGO_ENABLED: 0 
          GOARCH: amd64
        run: |
          mkdir -p dist
          # 编译 Linux
          GOOS=linux go build -trimpath -ldflags="-s -w" -o dist/app-linux-amd64 .
          # 编译 Windows
          GOOS=windows go build -trimpath -ldflags="-s -w" -o dist/app-windows-amd64.exe .

      # 独立上传 Linux 产物
      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v7
        with:
          name: linux-amd64          
          path: dist/app-linux-amd64     # 对应的文件路径

      # 独立上传 Windows 产物
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v7
        with:
          name: windows-amd64
          path: dist/app-windows-amd64.exe # 对应的文件路径
